import type { LessonSeed } from "../types.js";

/**
 * Electric Circuits (intro university). Algebra-based DC circuit analysis:
 * current, resistance and Ohm's law; series & parallel combinations; EMF and
 * power; Kirchhoff's rules; and RC charging/discharging. Lesson 1 reuses the
 * existing "circuits-and-ohms-law" slug from electromagnetism.ts so learner
 * progress on that node is preserved.
 */
export const circuitsLessons: LessonSeed[] = [
  // ─────────────── 1. Current, Resistance & Ohm's Law ───────────────
  {
    slug: "circuits-and-ohms-law",
    title: "Current, Resistance & Ohm's Law",
    tagline: "Voltage, current, resistance — and the law that ties them together",
    estMinutes: 15,
    xpReward: 160,
    difficulty: 2,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Charge in Motion", sub: "Give charges a push and a path, and they flow — a current, governed by one beautifully simple law." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Static charge is dramatic but fleeting. Channel charge into a steady **flow** through wires and you get a **circuit** — the basis of every device you own, from a flashlight to a phone.\n\nThree quantities — **voltage**, **current**, and **resistance** — and one remarkably simple law connect them. Master that relationship and you can predict how any simple circuit behaves before you ever pick up a wire." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Current** $I$ is the *rate* at which charge flows past a point. If a charge $Q$ passes in a time $t$,\n\n$$I = \\frac{Q}{t}$$\n\nUnits are **amperes** (A): $1\\,\\text{A} = 1\\,\\text{C/s}$. (By convention, current points in the direction *positive* charge would flow — opposite to the actual electron drift.)\n\n**Voltage** $V$ (volts) is the energy delivered per unit charge — the 'push' that drives the flow.\n\n**Resistance** $R$ (ohms, $\\Omega$) measures how strongly a component opposes the flow.\n\n**Ohm's law** links all three:\n\n$$V = I\\,R$$\n\nso $I = \\dfrac{V}{R}$ and $R = \\dfrac{V}{I}$. More voltage drives more current; more resistance chokes it. The water analogy: voltage is pump pressure, current is the flow rate, and resistance is a narrow pipe.\n\nA device is **ohmic** when $R$ is constant — its current is strictly proportional to the voltage across it. (Filaments and diodes are *non-ohmic*; their resistance changes with conditions.)" } },
      { kind: "CONCEPT", title: "Derivation: what sets the resistance", content: { markdown: "Resistance is not arbitrary — it depends on the wire itself. For a uniform conductor of length $L$ and cross-sectional area $A$,\n\n$$R = \\rho\\,\\frac{L}{A}$$\n\nwhere $\\rho$ is the material's **resistivity**. The picture: a *longer* wire gives charges more atoms to collide with (more resistance), while a *thicker* wire ($A$ larger) opens more lanes for flow (less resistance) — exactly like water through a pipe. This is why long extension cords drop voltage and why high-current wiring is thick." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Current from charge", problem: "A charge of $6\\,\\text{C}$ flows past a point in $2\\,\\text{s}$. Find the current.", steps: ["$I = Q/t$.", "$I = 6/2 = 3\\,\\text{A}$."], answer: "$I = 3\\,\\text{A}$." },
        { title: "Find current with Ohm's law", problem: "A $12\\,\\text{V}$ battery drives a $4\\,\\Omega$ resistor. Find the current.", steps: ["$I = V/R$.", "$I = 12/4 = 3\\,\\text{A}$."], answer: "$I = 3\\,\\text{A}$." },
        { title: "Find resistance", problem: "A current of $2\\,\\text{A}$ flows when $10\\,\\text{V}$ is applied. Find the resistance.", steps: ["$R = V/I$.", "$R = 10/2 = 5\\,\\Omega$."], answer: "$R = 5\\,\\Omega$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Ohm's law: $V = IR$, and $I = Q/t$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Rearrange $V = IR$ as needed; use $I = Q/t$ for charge flow." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: drift speed vs. signal speed", content: { markdown: "A current of a few amps may sound fast, but the electrons themselves crawl. Their average **drift speed** in a copper wire is often less than a millimetre per second. So why does a light turn on instantly? Because the *electric field* that pushes the charges propagates through the wire at nearly the speed of light. Think of a pipe already full of water: open the tap and water leaves the far end immediately, even though any single molecule moves slowly. The 'signal' is fast; the carriers are slow." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Current gets used up as it goes around the circuit.\"** No — current is the same all the way around a single (series) loop. Charge is conserved; what gets used up is *energy* (voltage).\n\n**\"Voltage flows through a component.\"** Voltage is a difference *across* two points (a push), not something that flows. Current flows; voltage is applied.\n\n**\"Ohm's law works for everything.\"** It only holds when $R$ is constant. A light-bulb filament heats up and its resistance rises, so it is non-ohmic." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Current is the rate of charge flow: $I = Q/t$, in amperes ($1\\,\\text{A} = 1\\,\\text{C/s}$).", "Voltage pushes; current flows; resistance opposes.", "Ohm's law: $V = IR$, so $I = V/R$ and $R = V/I$.", "Resistance grows with length and shrinks with cross-section: $R = \\rho L/A$.", "An ohmic device has constant $R$; filaments and diodes are not ohmic."], formulas: [{ label: "Current", tex: "I = \\dfrac{Q}{t}" }, { label: "Ohm's law", tex: "V = IR" }, { label: "Resistance", tex: "R = \\rho\\dfrac{L}{A}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Ohm's law states that:", options: ["$V = I/R$", "$V = IR$", "$V = R/I$", "$V = I + R$"], answer: 1, difficulty: 1, explanation: "Voltage equals current times resistance: $V = IR$." },
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "A charge of $8\\,\\text{C}$ flows past a point in $4\\,\\text{s}$. Current in amperes?", answer: { value: 2, tolerance: 0 }, difficulty: 1, explanation: "$I = Q/t = 8/4 = 2\\,\\text{A}$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "In a single series loop, the current is the same at every point.", answer: true, difficulty: 2, explanation: "Charge is conserved, so the same current flows everywhere in a single loop." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $12\\,\\text{V}$ battery drives a $4\\,\\Omega$ resistor. Current in amperes?", answer: { value: 3, tolerance: 0 }, hint: "$I = V/R$.", explanation: "$I = 12/4 = 3\\,\\text{A}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A current of $2\\,\\text{A}$ flows through a $5\\,\\Omega$ resistor. Voltage across it in volts?", answer: { value: 10, tolerance: 0 }, hint: "$V = IR$.", explanation: "$V = 2 \\times 5 = 10\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $9\\,\\text{V}$ source pushes $0.5\\,\\text{A}$ through a resistor. Its resistance in ohms?", answer: { value: 18, tolerance: 0 }, hint: "$R = V/I$.", explanation: "$R = 9/0.5 = 18\\,\\Omega$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "Doubling the resistance while keeping the voltage fixed will:", options: ["double the current", "halve the current", "leave the current unchanged", "quadruple the current"], answer: 1, difficulty: 2, hint: "$I = V/R$.", explanation: "Current is inversely proportional to resistance, so it halves." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Solve Ohm's law for current $I$ in terms of voltage $V$ and resistance $R$. (Type like `V/R`.)", answer: { expr: "V/R", vars: ["V", "R"] }, difficulty: 2, hint: "Divide both sides of $V = IR$ by $R$.", explanation: "$I = V/R$." },
    ],
  },

  // ─────────────── 2. Series & Parallel Resistors ───────────────
  {
    slug: "series-and-parallel-resistors",
    title: "Series & Parallel Resistors",
    tagline: "Combining resistors into a single equivalent",
    estMinutes: 16,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Many Paths, One Network", sub: "Real circuits have more than one resistor. Two simple rules collapse any chain or fan-out into a single equivalent resistance." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "No useful device contains just one resistor. Strings of holiday lights, the voltage divider that sets a sensor's reading, the way household outlets share a supply — all are series or parallel combinations.\n\nKnowing how resistances combine lets you replace a tangle of components with a single number, then apply Ohm's law to the whole circuit at once." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Series** resistors sit one after another, so the *same current* passes through each. Their resistances simply add:\n\n$$R_\\text{series} = R_1 + R_2 + \\cdots$$\n\nThe equivalent is always **larger** than any single resistor — the current has more to fight through.\n\n**Parallel** resistors connect across the *same two nodes*, so each feels the *same voltage*. Their **reciprocals** add:\n\n$$\\frac{1}{R_\\text{parallel}} = \\frac{1}{R_1} + \\frac{1}{R_2} + \\cdots$$\n\nThe equivalent is always **smaller** than the smallest resistor — extra paths make it easier for current to flow. For just two in parallel there is a handy shortcut:\n\n$$R_\\text{parallel} = \\frac{R_1 R_2}{R_1 + R_2}.$$\n\n**Two rules of thumb to remember:**\n\n- Series: same **current**, voltages add.\n- Parallel: same **voltage**, currents add." } },
      { kind: "CONCEPT", title: "Derivation: why reciprocals add in parallel", content: { markdown: "Put resistors $R_1$ and $R_2$ across the same voltage $V$. Each carries its own current by Ohm's law: $I_1 = V/R_1$ and $I_2 = V/R_2$. Because charge is conserved at the node, the total current is the sum:\n\n$$I = I_1 + I_2 = \\frac{V}{R_1} + \\frac{V}{R_2}.$$\n\nThe equivalent resistance must satisfy $I = V/R_\\text{parallel}$, so dividing through by $V$,\n\n$$\\frac{1}{R_\\text{parallel}} = \\frac{1}{R_1} + \\frac{1}{R_2}.$$\n\nThe reciprocal rule falls straight out of 'currents add'." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Two in series", problem: "Resistors of $3\\,\\Omega$ and $6\\,\\Omega$ are wired in series. Find the equivalent resistance.", steps: ["Series resistances add.", "$R = 3 + 6 = 9\\,\\Omega$."], answer: "$R = 9\\,\\Omega$." },
        { title: "Two in parallel", problem: "The same $3\\,\\Omega$ and $6\\,\\Omega$ resistors are wired in parallel. Find the equivalent resistance.", steps: ["Use the product-over-sum shortcut for two: $R = \\dfrac{R_1 R_2}{R_1 + R_2}$.", "$R = \\dfrac{3 \\times 6}{3 + 6} = \\dfrac{18}{9} = 2\\,\\Omega$."], answer: "$R = 2\\,\\Omega$ — less than either resistor." },
        { title: "Total current", problem: "A $12\\,\\text{V}$ battery drives two $4\\,\\Omega$ resistors in parallel. Find the total current from the battery.", steps: ["Parallel equivalent: $\\dfrac1R = \\dfrac14 + \\dfrac14 = \\dfrac12$, so $R = 2\\,\\Omega$.", "$I = V/R = 12/2 = 6\\,\\text{A}$."], answer: "$I = 6\\,\\text{A}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Series adds; parallel adds reciprocals." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Combine resistances first, then apply Ohm's law to the whole." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: reducing a ladder network", content: { markdown: "Complex networks are tamed by **reduction**: find any pure series or pure parallel group, replace it with its single equivalent, and repeat. A four-resistor 'ladder' might collapse parallel-then-series-then-parallel until only one resistor remains, at which point Ohm's law gives the total current — and you can work *backwards* to find the current and voltage in each original branch. The same reduce-and-conquer idea reappears for capacitors and for springs in mechanics." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Parallel resistors add up like series ones.\"** No — in parallel the *reciprocals* add, and the result is smaller than the smallest resistor, not larger.\n\n**\"Adding a parallel resistor increases total resistance.\"** It always *decreases* it, because you've opened another path for current.\n\n**\"The voltage is the same across series resistors.\"** In series the *current* is shared and the voltages add; the *voltage* is shared in parallel." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Series: same current; resistances add, $R = R_1 + R_2 + \\cdots$.", "Parallel: same voltage; reciprocals add, $1/R = 1/R_1 + 1/R_2 + \\cdots$.", "A series total is larger than any resistor; a parallel total is smaller than the smallest.", "For two in parallel: $R = R_1 R_2/(R_1+R_2)$.", "Reduce a network by collapsing series/parallel groups one at a time."], formulas: [{ label: "Series", tex: "R = R_1 + R_2 + \\cdots" }, { label: "Parallel", tex: "\\dfrac{1}{R} = \\dfrac{1}{R_1} + \\dfrac{1}{R_2} + \\cdots" }, { label: "Two in parallel", tex: "R = \\dfrac{R_1 R_2}{R_1 + R_2}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "For resistors in series, the total resistance is:", options: ["the sum of the resistances", "the reciprocal of the sum of reciprocals", "always less than the smallest", "the product of the resistances"], answer: 0, difficulty: 1, explanation: "Series resistances add directly." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Adding a resistor in parallel always lowers the total resistance.", answer: true, difficulty: 2, explanation: "An extra parallel path gives current more room, so total resistance falls." },
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "Two resistors, $5\\,\\Omega$ and $7\\,\\Omega$, are in series. Total resistance in ohms?", answer: { value: 12, tolerance: 0 }, difficulty: 1, explanation: "$5 + 7 = 12\\,\\Omega$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Two $6\\,\\Omega$ resistors are in parallel. Equivalent resistance in ohms?", answer: { value: 3, tolerance: 0 }, hint: "Equal resistors in parallel: half of one.", explanation: "$1/R = 1/6 + 1/6 = 1/3$, so $R = 3\\,\\Omega$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Resistors of $2\\,\\Omega$ and $3\\,\\Omega$ are in parallel. Equivalent resistance in ohms?", answer: { value: 1.2, tolerance: 0.05 }, hint: "Use $R_1 R_2/(R_1+R_2)$.", explanation: "$\\dfrac{2 \\times 3}{2 + 3} = \\dfrac{6}{5} = 1.2\\,\\Omega$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $24\\,\\text{V}$ battery drives a $4\\,\\Omega$ and an $8\\,\\Omega$ resistor in series. Current in amperes?", answer: { value: 2, tolerance: 0 }, difficulty: 3, hint: "Add the series resistances first.", explanation: "$R = 12\\,\\Omega$, so $I = 24/12 = 2\\,\\text{A}$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "Three identical $9\\,\\Omega$ resistors in parallel give a total of:", options: ["$27\\,\\Omega$", "$9\\,\\Omega$", "$3\\,\\Omega$", "$1\\,\\Omega$"], answer: 2, difficulty: 2, hint: "Equal parallel resistors: divide by the count.", explanation: "$1/R = 3/9 = 1/3$, so $R = 3\\,\\Omega$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the equivalent resistance of two resistors $R_1$ and $R_2$ in parallel, using the product-over-sum form. (Type like `R_1*R_2/(R_1+R_2)`.)", answer: { expr: "R_1*R_2/(R_1+R_2)", vars: ["R_1", "R_2"] }, difficulty: 3, hint: "Product over sum.", explanation: "$R = \\dfrac{R_1 R_2}{R_1 + R_2}$." },
    ],
  },

  // ─────────────── 3. EMF & Power Dissipation ───────────────
  {
    slug: "emf-and-power-dissipation",
    title: "EMF & Power Dissipation",
    tagline: "Real sources, internal resistance, and where the energy goes",
    estMinutes: 16,
    xpReward: 165,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "The Engine of the Circuit", sub: "A battery does work to lift charge. Some of that energy reaches the load — and some is lost inside the battery itself." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Every circuit needs an energy source, and every real source falls short of the ideal. A fresh battery reads $1.5\\,\\text{V}$ on a meter but sags under load; a phone charger warms up; a toaster turns electrical energy into heat on purpose.\n\nUnderstanding **EMF**, **internal resistance**, and **power** tells you how much energy a source can actually deliver — and how fast components heat up." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "The **electromotive force** (EMF, symbol $\\varepsilon$) is the energy a source gives each unit of charge — its full 'open-circuit' voltage. Despite the name, EMF is not a force; it is measured in volts.\n\nA real source has a small **internal resistance** $r$. When it drives a current $I$, some voltage is lost inside it, so the **terminal voltage** actually delivered to the circuit is\n\n$$V_\\text{terminal} = \\varepsilon - I\\,r.$$\n\nThis is why a battery's voltage drops when you draw a large current (starting a car, say).\n\n**Power** is the rate of energy transfer. For any component carrying current $I$ with voltage $V$ across it,\n\n$$P = I\\,V.$$\n\nUsing Ohm's law ($V = IR$) gives two more equivalent forms for a resistor:\n\n$$P = I^2 R = \\frac{V^2}{R}.$$\n\nAll three are the same power, measured in **watts** ($1\\,\\text{W} = 1\\,\\text{J/s}$). In a resistor this power becomes heat — the **dissipated** power." } },
      { kind: "CONCEPT", title: "Derivation: the three power formulas", content: { markdown: "Start from the definition $P = IV$ — energy per charge ($V$) times charge per second ($I$) gives energy per second, which is power.\n\nFor a resistor, Ohm's law lets you eliminate whichever variable you don't have. Substitute $V = IR$:\n\n$$P = I(IR) = I^2 R.$$\n\nInstead substitute $I = V/R$:\n\n$$P = \\left(\\frac{V}{R}\\right)V = \\frac{V^2}{R}.$$\n\nThree expressions, one quantity — pick the form whose variables you already know." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Power from current and voltage", problem: "A bulb runs at $V = 12\\,\\text{V}$ and draws $I = 2\\,\\text{A}$. Find its power.", steps: ["$P = IV$.", "$P = 2 \\times 12 = 24\\,\\text{W}$."], answer: "$P = 24\\,\\text{W}$." },
        { title: "Power dissipated in a resistor", problem: "A current of $3\\,\\text{A}$ flows through a $4\\,\\Omega$ resistor. Find the power dissipated.", steps: ["Use $P = I^2 R$.", "$P = 3^2 \\times 4 = 9 \\times 4 = 36\\,\\text{W}$."], answer: "$P = 36\\,\\text{W}$." },
        { title: "Terminal voltage under load", problem: "A battery has EMF $\\varepsilon = 12\\,\\text{V}$ and internal resistance $r = 0.5\\,\\Omega$. It supplies $4\\,\\text{A}$. Find the terminal voltage.", steps: ["$V = \\varepsilon - Ir$.", "$V = 12 - 4(0.5) = 12 - 2 = 10\\,\\text{V}$."], answer: "$V_\\text{terminal} = 10\\,\\text{V}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "$P = IV = I^2R = V^2/R$; terminal voltage $= \\varepsilon - Ir$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Choose the power formula matching the quantities you're given." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: maximum power transfer", content: { markdown: "How much load resistance extracts the *most* power from a source with internal resistance $r$? Too small a load and almost all the voltage is lost inside the source; too large and little current flows. The sweet spot — derived by setting the derivative of the load power to zero — is when the **load matches the source**: $R_\\text{load} = r$. This **impedance matching** is why audio amplifiers, antennas, and power supplies are designed around their source resistance. At the match, exactly half the total power lands in the load and half is wasted as heat in the source." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"EMF is a force.\"** It is an energy-per-charge, measured in volts — not a force at all, despite the historical name.\n\n**\"A battery's voltage is fixed.\"** Its terminal voltage drops as it supplies current, by the amount $Ir$ lost across the internal resistance.\n\n**\"$P = I^2R$ and $P = V^2/R$ give different answers.\"** They are the same power — both equal $IV$ once you use Ohm's law to substitute." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["EMF $\\varepsilon$ is the energy per charge a source supplies (in volts).", "A real source has internal resistance $r$; terminal voltage $V = \\varepsilon - Ir$.", "Power is the rate of energy transfer: $P = IV$, in watts.", "For a resistor, $P = IV = I^2R = V^2/R$ — three forms of one quantity.", "Dissipated power becomes heat in the resistor."], formulas: [{ label: "Power", tex: "P = IV = I^2 R = \\dfrac{V^2}{R}" }, { label: "Terminal voltage", tex: "V = \\varepsilon - Ir" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Which is NOT an equivalent form of the power dissipated in a resistor?", options: ["$P = IV$", "$P = I^2 R$", "$P = V^2/R$", "$P = V/R^2$"], answer: 3, difficulty: 2, explanation: "$P = V/R^2$ is not valid; the correct forms are $IV$, $I^2R$, and $V^2/R$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "The terminal voltage of a real battery drops as it supplies more current.", answer: true, difficulty: 2, explanation: "More current means a larger $Ir$ drop inside, so $V = \\varepsilon - Ir$ falls." },
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "A device runs at $10\\,\\text{V}$ and draws $3\\,\\text{A}$. Power in watts?", answer: { value: 30, tolerance: 0 }, difficulty: 1, explanation: "$P = IV = 3 \\times 10 = 30\\,\\text{W}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A current of $2\\,\\text{A}$ flows through a $5\\,\\Omega$ resistor. Power dissipated in watts?", answer: { value: 20, tolerance: 0 }, hint: "$P = I^2 R$.", explanation: "$P = 2^2 \\times 5 = 20\\,\\text{W}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $12\\,\\text{V}$ supply is across a $6\\,\\Omega$ resistor. Power dissipated in watts?", answer: { value: 24, tolerance: 0 }, hint: "$P = V^2/R$.", explanation: "$P = 12^2/6 = 144/6 = 24\\,\\text{W}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A battery of EMF $9\\,\\text{V}$ and internal resistance $1\\,\\Omega$ supplies $2\\,\\text{A}$. Terminal voltage in volts?", answer: { value: 7, tolerance: 0 }, difficulty: 3, hint: "$V = \\varepsilon - Ir$.", explanation: "$V = 9 - 2(1) = 7\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "If the current through a resistor doubles, the power it dissipates:", options: ["doubles", "halves", "quadruples", "stays the same"], answer: 2, difficulty: 3, hint: "$P = I^2 R$ — power depends on current squared.", explanation: "Doubling $I$ multiplies $I^2$ by 4, so power quadruples." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the power dissipated in a resistor in terms of current $I$ and resistance $R$. (Type like `I^2*R`.)", answer: { expr: "I^2*R", vars: ["I", "R"] }, difficulty: 2, hint: "Substitute $V = IR$ into $P = IV$.", explanation: "$P = I^2 R$." },
    ],
  },

  // ─────────────── 4. Kirchhoff's Rules ───────────────
  {
    slug: "kirchhoffs-rules",
    title: "Kirchhoff's Rules",
    tagline: "Conservation of charge and energy, applied to any circuit",
    estMinutes: 17,
    xpReward: 165,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Two Laws for Any Network", sub: "When series-and-parallel tricks run out, two conservation rules — for charge and for energy — solve circuits no shortcut can." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Many real circuits — those with more than one battery, or resistors that are neither purely in series nor purely in parallel — can't be reduced by the simple combination rules.\n\n**Kirchhoff's rules** handle *every* circuit. They are nothing more than conservation of charge and conservation of energy, written for circuits, and they turn any network into a solvable set of equations." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Kirchhoff's junction rule (current law).** At any junction (node), the total current flowing *in* equals the total current flowing *out*:\n\n$$\\sum I_\\text{in} = \\sum I_\\text{out}.$$\n\nThis is **conservation of charge** — charge cannot pile up or vanish at a point.\n\n**Kirchhoff's loop rule (voltage law).** Around any closed loop, the sum of all voltage changes is zero:\n\n$$\\sum V = 0.$$\n\nThis is **conservation of energy** — a charge returning to its starting point must have gained exactly as much energy (from sources) as it lost (across resistors).\n\n**Sign conventions for the loop rule** as you walk around a loop:\n\n- Crossing a resistor *with* the current: voltage *drops* by $IR$ (count it negative).\n- Crossing a source from $-$ to $+$: voltage *rises* by $\\varepsilon$ (count it positive).\n\nSet up one junction equation per node and one loop equation per independent loop, then solve the simultaneous equations for the unknown currents." } },
      { kind: "CONCEPT", title: "Derivation: the loop rule is energy conservation", content: { markdown: "Voltage is energy per unit charge. Send one unit of charge once around a closed loop and return it to its exact starting point. Its energy at the end must equal its energy at the start — otherwise you'd create or destroy energy each lap.\n\nEvery rise (through a battery's EMF) adds energy; every drop (across a resistor) removes it as heat. For the charge to break even,\n\n$$\\sum (\\text{rises}) - \\sum (\\text{drops}) = 0 \\;\\Longrightarrow\\; \\sum V = 0.$$\n\nThe loop rule is simply the statement that energy is conserved per round trip." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Applying the junction rule", problem: "At a node, currents of $3\\,\\text{A}$ and $2\\,\\text{A}$ flow in, and a current $I$ flows out. Find $I$.", steps: ["Junction rule: in equals out.", "$3 + 2 = I$, so $I = 5\\,\\text{A}$."], answer: "$I = 5\\,\\text{A}$." },
        { title: "A single loop with two sources", problem: "A loop has a $12\\,\\text{V}$ battery, a $4\\,\\text{V}$ battery opposing it, and a $4\\,\\Omega$ resistor. Find the current.", steps: ["Loop rule: net EMF equals the resistor drop.", "$12 - 4 = I(4)$.", "$8 = 4I$, so $I = 2\\,\\text{A}$."], answer: "$I = 2\\,\\text{A}$." },
        { title: "Finding a missing branch current", problem: "Three branches meet at a node: $5\\,\\text{A}$ in, $2\\,\\text{A}$ out one branch, and $I$ out the other. Find $I$.", steps: ["In equals total out: $5 = 2 + I$.", "$I = 5 - 2 = 3\\,\\text{A}$."], answer: "$I = 3\\,\\text{A}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Junction rule: charge in = charge out. Loop rule: $\\sum V = 0$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Apply the junction rule at nodes and the loop rule around loops." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: counting independent equations", content: { markdown: "A network with $n$ nodes gives $n - 1$ *independent* junction equations (the last node's equation is implied by the others). The remaining equations needed come from independent loops — those that each include at least one branch the others don't. Choose currents, assign each a direction (a negative answer just means you guessed the direction backwards), and you'll always get exactly as many independent equations as unknown currents. This bookkeeping scales up to the matrix methods used by circuit-simulation software." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Current is used up at a junction.\"** No — the junction rule says current in equals current out exactly. Charge is conserved.\n\n**\"You must guess every current's direction correctly.\"** You don't. Pick any direction; a negative result simply means the real current runs the other way.\n\n**\"The loop rule only works for a single battery.\"** It works for any loop with any number of sources — just track each rise and drop with its sign." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Junction rule: current in = current out at every node (conservation of charge).", "Loop rule: the sum of voltage changes around any closed loop is zero (conservation of energy).", "Resistor crossed with the current: a drop of $IR$; source low-to-high: a rise of $\\varepsilon$.", "Write one equation per node and per independent loop, then solve simultaneously.", "A negative current just means you assumed the wrong direction."], formulas: [{ label: "Junction rule", tex: "\\sum I_\\text{in} = \\sum I_\\text{out}" }, { label: "Loop rule", tex: "\\sum V = 0" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Kirchhoff's junction rule is a statement of conservation of:", options: ["energy", "charge", "momentum", "voltage"], answer: 1, difficulty: 2, explanation: "Current in equals current out because charge is conserved." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "The loop rule says the sum of voltage changes around any closed loop is zero.", answer: true, difficulty: 1, explanation: "Yes — that is conservation of energy per round trip." },
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "At a junction, $4\\,\\text{A}$ and $3\\,\\text{A}$ flow in and a single current $I$ flows out. Find $I$ in amperes.", answer: { value: 7, tolerance: 0 }, difficulty: 1, explanation: "$I = 4 + 3 = 7\\,\\text{A}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A node has $6\\,\\text{A}$ in, with $2\\,\\text{A}$ and $I$ flowing out. Find $I$ in amperes.", answer: { value: 4, tolerance: 0 }, hint: "In = sum of outs.", explanation: "$6 = 2 + I$, so $I = 4\\,\\text{A}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A single loop has a $10\\,\\text{V}$ battery and a $5\\,\\Omega$ resistor. By the loop rule, find the current in amperes.", answer: { value: 2, tolerance: 0 }, hint: "Rise = drop: $\\varepsilon = IR$.", explanation: "$10 = I(5)$, so $I = 2\\,\\text{A}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A loop has a $15\\,\\text{V}$ battery and a $9\\,\\text{V}$ battery opposing it, with a $3\\,\\Omega$ resistor. Find the current in amperes.", answer: { value: 2, tolerance: 0 }, difficulty: 4, hint: "Net EMF = $15 - 9$; set equal to $IR$.", explanation: "$15 - 9 = I(3)$, so $6 = 3I$ and $I = 2\\,\\text{A}$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "When solving with Kirchhoff's rules, a current you computed comes out negative. This means:", options: ["you made an arithmetic error", "the current is zero", "the real current flows opposite to your assumed direction", "the loop rule was violated"], answer: 2, difficulty: 3, hint: "Direction is just an assumption.", explanation: "A negative value simply flips your assumed direction." },
      { scope: "PRACTICE", kind: "ORDER", prompt: "Order the steps to solve a multi-loop circuit with Kirchhoff's rules.", options: ["Assign a current and direction to each branch", "Write a junction equation at each node", "Write a loop equation for each independent loop", "Solve the simultaneous equations for the currents", "Interpret any negative current as a reversed direction"], answer: [], difficulty: 4, hint: "Label first, write equations, then solve.", explanation: "Label currents, apply the junction and loop rules, solve, then fix directions from the signs." },
    ],
  },

  // ─────────────── 5. RC Circuits ───────────────
  {
    slug: "rc-circuits",
    title: "RC Circuits",
    tagline: "Charging, discharging, and the time constant",
    estMinutes: 17,
    xpReward: 165,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Circuits with Memory", sub: "Add a capacitor to a resistor and the circuit no longer responds instantly — it charges and discharges on its own clock, the time constant." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Resistor-only circuits react instantly. Add a **capacitor** — a component that stores charge — and the circuit develops *timing*: voltages rise and fall smoothly over a characteristic interval.\n\nThis is the basis of camera-flash charging, the blink rate of a turn signal, the debouncing of a button, and the filters that shape every audio signal. The single number that sets the pace is the **time constant** $\\tau = RC$." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "A **capacitor** stores charge $Q$ in proportion to the voltage across it: $Q = CV$, where $C$ is the **capacitance** (farads).\n\nWhen a capacitor charges through a resistor from a source of voltage $V_0$, the charge (and the capacitor's voltage) rises toward its final value, not instantly but exponentially:\n\n$$V_C(t) = V_0\\left(1 - e^{-t/\\tau}\\right).$$\n\nWhen a charged capacitor **discharges** through a resistor, its voltage decays exponentially toward zero:\n\n$$V_C(t) = V_0\\,e^{-t/\\tau}.$$\n\nThe **time constant** is\n\n$$\\tau = R\\,C,$$\n\nwith units of seconds. It sets the pace of the circuit:\n\n- After **one** time constant ($t = \\tau$), a charging capacitor reaches about $63\\%$ of $V_0$, and a discharging one falls to about $37\\%$.\n- After about **five** time constants the process is essentially complete ($>99\\%$).\n\nA *larger* $R$ or $C$ means a *slower* circuit — more resistance throttles the current, and more capacitance needs more charge to fill." } },
      { kind: "CONCEPT", title: "Derivation: why exponential", content: { markdown: "Discharge a capacitor through a resistor. The capacitor's voltage drives a current $I = V_C/R$, but that current carries away its stored charge, $I = -\\dfrac{dQ}{dt}$. Since $Q = C V_C$,\n\n$$\\frac{dQ}{dt} = -\\frac{Q}{RC}.$$\n\nA quantity whose rate of change is proportional to *itself* decays **exponentially**:\n\n$$Q(t) = Q_0\\,e^{-t/RC}.$$\n\nThe constant $RC$ in the exponent is exactly the time constant $\\tau$. Charging follows the same equation, approaching the final charge instead of zero — hence the $1 - e^{-t/\\tau}$ form." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Find the time constant", problem: "A $2\\,\\Omega$ resistor is in series with a $3\\,\\text{F}$ capacitor. Find the time constant.", steps: ["$\\tau = RC$.", "$\\tau = 2 \\times 3 = 6\\,\\text{s}$."], answer: "$\\tau = 6\\,\\text{s}$." },
        { title: "Charge after one time constant", problem: "A capacitor charges toward $V_0 = 10\\,\\text{V}$. What is $V_C$ after exactly one time constant? (Use $1 - e^{-1} \\approx 0.63$.)", steps: ["$V_C = V_0(1 - e^{-1})$.", "$V_C \\approx 10 \\times 0.63 = 6.3\\,\\text{V}$."], answer: "$V_C \\approx 6.3\\,\\text{V}$." },
        { title: "Discharge voltage", problem: "A capacitor charged to $12\\,\\text{V}$ discharges. What is its voltage after one time constant? (Use $e^{-1} \\approx 0.37$.)", steps: ["$V_C = V_0\\,e^{-1}$.", "$V_C \\approx 12 \\times 0.37 = 4.44\\,\\text{V}$."], answer: "$V_C \\approx 4.4\\,\\text{V}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "$\\tau = RC$; charge to $\\sim 63\\%$ in one $\\tau$, discharge to $\\sim 37\\%$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Compute $\\tau = RC$; use $63\\%$ (charging) and $37\\%$ (discharging) at one $\\tau$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: RC circuits as filters", content: { markdown: "Because an RC circuit reacts slowly, it treats fast and slow signals differently. Tap the voltage across the capacitor and rapid wiggles are smoothed away while slow changes pass — a **low-pass filter**. Tap across the resistor instead and the opposite happens — a **high-pass filter**. The dividing line is the *cutoff frequency* $f_c = \\dfrac{1}{2\\pi RC}$, set by the same time constant. Stack a few of these and you have the tone controls of an equalizer or the anti-aliasing front-end of an oscilloscope." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A capacitor charges instantly.\"** Only through zero resistance. With a real resistor it follows the exponential $V_0(1 - e^{-t/\\tau})$ and takes about five time constants to finish.\n\n**\"After one time constant the capacitor is fully charged.\"** It reaches only about $63\\%$ of the final voltage after one $\\tau$, not $100\\%$.\n\n**\"A bigger resistor makes the capacitor charge faster.\"** The opposite — a larger $R$ (or $C$) increases $\\tau$ and *slows* the charging." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["A capacitor stores charge: $Q = CV$, with $C$ in farads.", "Charging: $V_C = V_0(1 - e^{-t/\\tau})$; discharging: $V_C = V_0 e^{-t/\\tau}$.", "The time constant is $\\tau = RC$, in seconds.", "After one $\\tau$: $\\sim 63\\%$ charged or $\\sim 37\\%$ remaining; after $\\sim 5\\tau$ it's essentially done.", "Larger $R$ or $C$ makes the circuit slower."], formulas: [{ label: "Time constant", tex: "\\tau = RC" }, { label: "Charging", tex: "V_C = V_0\\left(1 - e^{-t/\\tau}\\right)" }, { label: "Discharging", tex: "V_C = V_0\\,e^{-t/\\tau}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The time constant of an RC circuit is:", options: ["$R/C$", "$RC$", "$C/R$", "$R + C$"], answer: 1, difficulty: 1, explanation: "$\\tau = RC$, in seconds." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Increasing the resistance increases the time constant, making the capacitor charge more slowly.", answer: true, difficulty: 2, explanation: "$\\tau = RC$ grows with $R$, so charging slows." },
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "A $5\\,\\Omega$ resistor is in series with a $2\\,\\text{F}$ capacitor. Time constant in seconds?", answer: { value: 10, tolerance: 0 }, difficulty: 1, explanation: "$\\tau = RC = 5 \\times 2 = 10\\,\\text{s}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Find the time constant for $R = 1000\\,\\Omega$ and $C = 0.002\\,\\text{F}$, in seconds.", answer: { value: 2, tolerance: 0 }, hint: "$\\tau = RC$.", explanation: "$\\tau = 1000 \\times 0.002 = 2\\,\\text{s}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A capacitor charges toward $20\\,\\text{V}$. Roughly what is its voltage after one time constant, in volts? (Use $63\\%$.)", answer: { value: 12.6, tolerance: 0.5 }, difficulty: 3, hint: "$V_C = 0.63\\,V_0$ at $t = \\tau$.", explanation: "$0.63 \\times 20 = 12.6\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A capacitor charged to $8\\,\\text{V}$ discharges. Its voltage after one time constant, in volts? (Use $37\\%$.)", answer: { value: 2.96, tolerance: 0.2 }, difficulty: 3, hint: "$V_C = 0.37\\,V_0$ at $t = \\tau$.", explanation: "$0.37 \\times 8 = 2.96\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "After about how many time constants is charging essentially complete (over 99%)?", options: ["1", "2", "5", "100"], answer: 2, difficulty: 2, hint: "Each $\\tau$ closes most of the remaining gap.", explanation: "By $\\sim 5\\tau$ the capacitor is more than 99% charged." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the time constant of an RC circuit in terms of resistance $R$ and capacitance $C$. (Type like `R*C`.)", answer: { expr: "R*C", vars: ["R", "C"] }, difficulty: 2, hint: "Product of resistance and capacitance.", explanation: "$\\tau = RC$." },
    ],
  },
];
