import type { LessonSeed } from "../types.js";

/**
 * Electrostatics & Electric Fields (intro university). The physics of charges at
 * rest: Coulomb's law, the electric field, potential and potential energy,
 * conductors in equilibrium, and capacitance. Algebra-based with the key
 * relations surfaced. Slugs for charge/field topics are reused from
 * electromagnetism.ts so existing user progress is preserved.
 */
export const electrostaticsLessons: LessonSeed[] = [
  // ───────────────────────── 1. Electric Charge & Coulomb's Law ─────────────────────────
  {
    slug: "electric-charge-and-coulombs-law",
    title: "Electric Charge & Coulomb's Law",
    tagline: "Like repels, opposite attracts — an inverse-square grip",
    estMinutes: 16,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "The Electric Grip", sub: "A force like gravity but vastly stronger — and it comes in two signs, so it can push as well as pull." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Almost everything you touch is held together by the electric force. The rigidity of a table, the chemistry of life, the spark of static on a dry day — all are electric charge in action.\n\nWe begin with charges at rest, **electrostatics**. The single most important rule, **Coulomb's law**, looks almost identical to Newton's law of gravity, yet it is enormously stronger and, uniquely, can both attract and repel. Getting it right is the foundation for fields, potential, and circuits to come." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Electric charge** comes in two kinds, positive and negative, measured in **coulombs** (C). The rule everyone knows: **like charges repel, opposite charges attract.**\n\nCharge obeys two deep conservation rules:\n\n- **Conservation of charge** — charge is never created or destroyed, only transferred. Rub a balloon on your hair and electrons move from one to the other; the total charge is unchanged.\n- **Quantization of charge** — charge comes in whole multiples of the **elementary charge** $e = 1.6\\times10^{-19}\\,\\text{C}$. Any charge is $q = N e$ for some integer $N$.\n\n**Coulomb's law** gives the force between two point charges:\n\n$$F = k\\,\\frac{q_1 q_2}{r^2},$$\n\nwhere $r$ is their separation and $k \\approx 9\\times10^{9}\\ \\text{N·m}^2/\\text{C}^2$ (Coulomb's constant).\n\nCompare with gravity, $F = G\\dfrac{m_1 m_2}{r^2}$: both are **inverse-square** laws. The differences:\n\n- Charge has two signs, so the force can be attractive *or* repulsive; gravity only attracts.\n- The electric force is far stronger — about $10^{36}$ times stronger between two protons.\n\nTriple the distance and the force drops to $\\tfrac19$, exactly as with gravity." } },
      { kind: "CONCEPT", title: "Derivation: superposition for many charges", content: { markdown: "Coulomb's law is written for *two* charges, but most situations have more. The **principle of superposition** rescues us: the total force on a charge is the **vector sum** of the separate Coulomb forces from every other charge, each computed as if the others weren't there.\n\nFor a charge $q$ feeling forces from charges $q_1, q_2, q_3, \\dots$:\n\n$$\\vec F_{\\text{total}} = \\vec F_1 + \\vec F_2 + \\vec F_3 + \\cdots = \\sum_i k\\,\\frac{q\\,q_i}{r_i^2}\\,\\hat r_i.$$\n\nNothing more is assumed — each pair simply contributes independently, and the contributions add like any other vectors. This additivity (shared with gravity) is what lets us handle complex arrangements, and it underlies the electric field of any charged object, however intricate." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Inverse-square scaling", problem: "Two charges are pulled apart until their separation triples. What happens to the force between them?", steps: ["Coulomb's law gives $F \\propto 1/r^2$.", "Replacing $r$ with $3r$ multiplies the force by $1/3^2 = 1/9$."], answer: "The force drops to one-ninth of its original value." },
        { title: "Numeric Coulomb force", problem: "Two charges $q_1 = 2\\times10^{-6}\\,\\text{C}$ and $q_2 = 3\\times10^{-6}\\,\\text{C}$ are $0.10\\,\\text{m}$ apart. Find the force ($k = 9\\times10^{9}$).", steps: ["$F = k\\,q_1 q_2 / r^2$.", "$F = 9\\times10^{9}\\times(2\\times10^{-6})(3\\times10^{-6}) / (0.10)^2$.", "Numerator: $9\\times10^{9}\\times 6\\times10^{-12} = 5.4\\times10^{-2}$. Divide by $0.01$: $5.4\\,\\text{N}$."], answer: "$F \\approx 5.4\\,\\text{N}$ (repulsive, since both are positive)." },
        { title: "Counting electrons", problem: "How many excess electrons make up a charge of $-1.6\\times10^{-18}\\,\\text{C}$?", steps: ["Charge is quantized: $q = N e$ with $e = 1.6\\times10^{-19}\\,\\text{C}$.", "$N = |q|/e = (1.6\\times10^{-18}) / (1.6\\times10^{-19}) = 10$."], answer: "$10$ electrons." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Like repels, opposite attracts; inverse-square; charge is conserved and quantized." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use the inverse-square dependence, the sign rule, and $q = Ne$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: why so much stronger than gravity?", content: { markdown: "Both forces share the inverse-square form, so the contrast is entirely in the constants and the 'charges.' Two protons have mass $\\sim 1.7\\times10^{-27}\\,\\text{kg}$ and charge $1.6\\times10^{-19}\\,\\text{C}$. Plug into the two laws and the electric repulsion beats the gravitational attraction by a factor of roughly $10^{36}$.\n\nWhy, then, does gravity rule the cosmos? Because matter is **almost perfectly neutral**: positive and negative charge nearly cancel everywhere, leaving no net electric force at large scales. Gravity has no such cancellation — mass only adds. So the far weaker force wins by sheer accumulation across planets, stars, and galaxies." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Charging an object creates new charge.\"** No — charge is conserved. Charging just moves existing electrons from one object to another; the total is unchanged.\n\n**\"You can have any amount of charge.\"** Charge is quantized in units of $e = 1.6\\times10^{-19}\\,\\text{C}$. Every observable charge is a whole-number multiple of $e$.\n\n**\"Doubling the distance halves the force.\"** It quarters it — the law is inverse-*square*, so $F \\propto 1/r^2$, not $1/r$." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Charge is positive or negative, measured in coulombs; like repels, opposite attracts.", "Charge is conserved (only transferred) and quantized in units of $e = 1.6\\times10^{-19}\\,\\text{C}$.", "Coulomb's law: $F = kq_1q_2/r^2$ with $k \\approx 9\\times10^{9}\\,\\text{N·m}^2/\\text{C}^2$.", "It is an inverse-square law like gravity, but far stronger and able to attract or repel.", "Forces from many charges add by superposition (vector sum)."], formulas: [{ label: "Coulomb's law", tex: "F = k\\dfrac{q_1 q_2}{r^2}" }, { label: "Quantization", tex: "q = N e" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Two charges with the same sign will:", options: ["attract", "repel", "do nothing", "merge"], answer: 1, difficulty: 1, explanation: "Like charges repel." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Coulomb's law depends on distance as:", options: ["$\\propto r$", "$\\propto 1/r$", "$\\propto 1/r^2$", "independent of $r$"], answer: 2, difficulty: 2, explanation: "Inverse-square, like gravity." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Electric charge is quantized — it comes in whole multiples of the elementary charge.", answer: true, difficulty: 2, explanation: "Every charge is $q = Ne$ for some integer $N$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "If the distance between two charges triples, the force becomes:", options: ["3× larger", "9× larger", "1/3", "1/9"], answer: 3, difficulty: 2, hint: "$1/3^2$.", explanation: "Inverse-square: $1/9$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "How many excess electrons make a charge of $-3.2\\times10^{-18}\\,\\text{C}$? (Use $e = 1.6\\times10^{-19}\\,\\text{C}$.)", answer: { value: 20, tolerance: 0 }, difficulty: 3, hint: "$N = |q|/e$.", explanation: "$3.2\\times10^{-18} / 1.6\\times10^{-19} = 20$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write Coulomb's law for the force $F$ between charges $q_1$ and $q_2$ separated by $r$, using Coulomb's constant $k$. (Type like `k*q1*q2/r^2`.)", answer: { expr: "k*q1*q2/r^2", vars: ["k", "q1", "q2", "r"] }, difficulty: 3, hint: "Product of charges over distance squared, times $k$.", explanation: "$F = k\\,q_1 q_2 / r^2$." },
      { scope: "PRACTICE", kind: "GRAPH", prompt: "Taking $kq_1q_2 = 1$, the Coulomb force is $F = 1/r^2$. Graph it (enter $F$ as a function of $r$, use $x$ for $r$).", answer: { expr: "1/x^2", domain: [0.5, 4], variable: "x" }, difficulty: 4, hint: "Inverse-square curve.", explanation: "$F = 1/r^2$ falls off steeply with distance." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Charging a balloon by rubbing creates brand-new electric charge.", answer: false, difficulty: 2, hint: "Conservation of charge.", explanation: "Charge is conserved — rubbing only transfers electrons; no new charge is made." },
    ],
  },

  // ───────────────────────── 2. The Electric Field ─────────────────────────
  {
    slug: "electric-fields",
    title: "The Electric Field",
    tagline: "The force per unit charge that fills space",
    estMinutes: 16,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Force at a Distance", sub: "A charge reshapes the space around it into a field — and any other charge feels that field, not the distant source directly." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "How does one charge 'know' another is there across empty space? Physics answers with the **field**: a charge fills the surrounding space with an electric field, and any charge placed there feels a force from the local field.\n\nThe field is not just bookkeeping — it carries energy and momentum, and it is what light itself is made of. Mastering $E = F/q$ and the field of a point charge is the bridge from Coulomb's law to potential, capacitors, and ultimately electromagnetic waves." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "The **electric field** $E$ at a point is the force per unit positive charge placed there:\n\n$$E = \\frac{F}{q}, \\qquad \\text{so} \\qquad F = qE.$$\n\nIts units are **newtons per coulomb** (N/C). The field is defined using a tiny *positive test charge* so its direction is unambiguous.\n\nA single point charge $Q$ produces a field\n\n$$E = k\\,\\frac{Q}{r^2},$$\n\nagain inverse-square — this is just Coulomb's law divided by the test charge. The field points **away** from positive charges and **toward** negative ones.\n\n**Field lines** picture the field: they start on positive charges, end on negative charges, never cross, and are **denser where the field is stronger**. The tangent to a line at any point gives the field's direction there.\n\nBetween two parallel charged plates the field is **uniform** — constant in strength and direction. This is the configuration inside a capacitor and the setup for accelerating particles in a straight line." } },
      { kind: "CONCEPT", title: "Derivation: the field of a point charge", content: { markdown: "Start from the definition $E = F/q$, where $q$ is a small positive test charge placed a distance $r$ from a source charge $Q$.\n\nThe force on the test charge is Coulomb's law:\n\n$$F = k\\,\\frac{Q\\,q}{r^2}.$$\n\nDivide by $q$ to get the field — the force *per unit charge*:\n\n$$E = \\frac{F}{q} = \\frac{k\\,Q\\,q / r^2}{q} = k\\,\\frac{Q}{r^2}.$$\n\nThe test charge $q$ cancels, which is the whole point: the field belongs to the source $Q$ and the location, not to whatever charge we use to probe it." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Force from a field", problem: "A charge $q = 2\\,\\text{C}$ sits in a field $E = 5\\,\\text{N/C}$. Find the force.", steps: ["$F = qE$.", "$F = 2 \\times 5$."], answer: "$F = 10\\,\\text{N}$." },
        { title: "Field of a point charge", problem: "Find the field $0.30\\,\\text{m}$ from a charge $Q = 5\\times10^{-9}\\,\\text{C}$ ($k = 9\\times10^{9}$).", steps: ["$E = kQ/r^2$.", "$E = 9\\times10^{9}\\times 5\\times10^{-9} / (0.30)^2 = 45 / 0.09$."], answer: "$E = 500\\,\\text{N/C}$, pointing away from $Q$." },
        { title: "Field from force", problem: "A $3\\,\\text{C}$ charge feels $12\\,\\text{N}$. Find the field at its location.", steps: ["$E = F/q$.", "$E = 12/3$."], answer: "$E = 4\\,\\text{N/C}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "$E = F/q$; field of a point charge is $kQ/r^2$; field points away from positive." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Relate field, force, and charge with $F = qE$ and $E = kQ/r^2$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: why introduce a field at all?", content: { markdown: "Coulomb's law already tells us the force between any two charges — so why bother with a field?\n\nTwo reasons. First, **locality**: the field replaces 'action at a distance' with something physical *here*, at each point in space. A charge responds to the field at its own location, not to a faraway source instantaneously.\n\nSecond, and more profound: when charges **move**, changes in their field do not appear everywhere at once. They ripple outward at the speed of light as **electromagnetic waves** — light, radio, X-rays. That is impossible to describe with forces alone but natural with fields. The field, once a convenience, turns out to be the more fundamental object." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"The field needs a charge sitting there to exist.\"** No — the field fills space around the source whether or not a test charge is present. The test charge only *reveals* it.\n\n**\"Field lines can cross.\"** They never do. A crossing would mean two different field directions at one point, which is impossible.\n\n**\"A stronger source charge means a stronger force everywhere automatically.\"** The *field* of a point charge is $kQ/r^2$, but the *force* on something depends on both the field and that object's own charge, $F = qE$." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["The electric field is force per unit charge: $E = F/q$, in N/C.", "A charge in a field feels $F = qE$.", "A point charge makes a field $E = kQ/r^2$ (inverse-square, by dividing Coulomb's law by $q$).", "Field points away from positive charges, toward negative; field lines never cross and are denser where the field is strong.", "Between parallel plates the field is uniform."], formulas: [{ label: "Field", tex: "E = \\dfrac{F}{q}" }, { label: "Force from field", tex: "F = qE" }, { label: "Point-charge field", tex: "E = k\\dfrac{Q}{r^2}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "A charge $q = 2\\,\\text{C}$ sits in a field $E = 5\\,\\text{N/C}$. Find the force in newtons.", answer: { value: 10, tolerance: 0 }, difficulty: 1, explanation: "$F = qE = 10\\,\\text{N}$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The electric field near a positive charge points:", options: ["toward the charge", "away from the charge", "in circles", "there is none"], answer: 1, difficulty: 2, explanation: "Away from positive charges." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Electric field lines can cross one another.", answer: false, difficulty: 2, explanation: "Crossing would give two field directions at one point — impossible. Lines never cross." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $3\\,\\text{C}$ charge feels a force of $12\\,\\text{N}$. Find the field $E$ in N/C.", answer: { value: 4, tolerance: 0 }, difficulty: 2, hint: "$E = F/q$.", explanation: "$E = 12/3 = 4$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Find the field $0.30\\,\\text{m}$ from a charge $Q = 5\\times10^{-9}\\,\\text{C}$ (use $k = 9\\times10^{9}$), in N/C.", answer: { value: 500, tolerance: 5 }, difficulty: 3, hint: "$E = kQ/r^2$.", explanation: "$9\\times10^{9}\\times 5\\times10^{-9} / 0.09 = 45/0.09 = 500\\,\\text{N/C}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the field $E$ of a point charge $Q$ at distance $r$, using Coulomb's constant $k$. (Type like `k*Q/r^2`.)", answer: { expr: "k*Q/r^2", vars: ["k", "Q", "r"] }, difficulty: 3, hint: "Coulomb's law divided by the test charge.", explanation: "$E = kQ/r^2$." },
      { scope: "PRACTICE", kind: "GRAPH", prompt: "Taking $kQ = 1$, a point charge's field is $E = 1/r^2$. Graph it (enter $E$ as a function of $r$, use $x$ for $r$).", answer: { expr: "1/x^2", domain: [0.5, 4], variable: "x" }, difficulty: 4, hint: "Inverse-square again.", explanation: "$E = 1/r^2$ — the same shape as the Coulomb force." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Between two parallel charged plates the field is approximately uniform.", answer: true, difficulty: 2, hint: "Think of a capacitor.", explanation: "Parallel plates produce a uniform field." },
    ],
  },

  // ───────────────────────── 3. Electric Potential & Potential Energy ─────────────────────────
  {
    slug: "electric-potential-and-energy",
    title: "Electric Potential & Potential Energy",
    tagline: "Energy per charge, and the voltage that drives it",
    estMinutes: 17,
    xpReward: 165,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Electric Hills and Valleys", sub: "Just as height stores gravitational energy, position in an electric field stores energy — and the energy per charge is what we call voltage." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Every battery is rated in **volts**, every outlet, every phone charger. Voltage is **electric potential** — the energy each unit of charge carries by virtue of where it sits in a field.\n\nThinking in terms of energy and potential is often far easier than tracking vector forces and fields. It is also the language of circuits: a **potential difference** is precisely what drives current through a wire, just as a height difference drives water downhill." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "Move a charge through an electric field and you do work, storing **electric potential energy** $U$. For a charge $q$ a distance $r$ from a point charge $Q$:\n\n$$U = k\\,\\frac{Q q}{r}.$$\n\nNote the single power of $r$ — potential energy goes as $1/r$, while force goes as $1/r^2$.\n\nThe **electric potential** $V$ is the potential energy *per unit charge* — it belongs to a location, not to any particular charge placed there:\n\n$$V = \\frac{U}{q}, \\qquad \\text{so} \\qquad U = qV.$$\n\nPotential is measured in **volts** (V), where $1\\,\\text{V} = 1\\,\\text{J/C}$. For a point charge,\n\n$$V = k\\,\\frac{Q}{r}.$$\n\nWhat actually matters in practice is the **potential difference** (voltage) between two points, $\\Delta V = V_B - V_A$. The work to move a charge $q$ between them is\n\n$$W = q\\,\\Delta V.$$\n\nAn **equipotential** is a surface on which $V$ is constant. Moving along it takes no work, and the electric field is always **perpendicular** to equipotentials, pointing from high potential to low." } },
      { kind: "CONCEPT", title: "Derivation: potential from potential energy", content: { markdown: "The two point-charge formulas are not independent — one comes straight from the other.\n\nThe energy of a test charge $q$ at distance $r$ from source $Q$ is\n\n$$U = k\\,\\frac{Q q}{r}.$$\n\nPotential is defined as energy per unit charge, $V = U/q$. Substituting:\n\n$$V = \\frac{U}{q} = \\frac{k\\,Q q / r}{q} = k\\,\\frac{Q}{r}.$$\n\nThe test charge $q$ cancels — exactly as it did for the field. Potential, like the field, is a property of the source and the location alone. And running it backwards, $U = qV$ recovers the energy for any charge $q$ you later place there." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Energy from potential", problem: "A charge $q = 4\\,\\text{C}$ sits at a point where $V = 3\\,\\text{V}$. Find its potential energy.", steps: ["$U = qV$.", "$U = 4 \\times 3$."], answer: "$U = 12\\,\\text{J}$." },
        { title: "Potential of a point charge", problem: "Find the potential $0.50\\,\\text{m}$ from $Q = 2\\times10^{-9}\\,\\text{C}$ ($k = 9\\times10^{9}$).", steps: ["$V = kQ/r$.", "$V = 9\\times10^{9}\\times 2\\times10^{-9} / 0.50 = 18 / 0.50$."], answer: "$V = 36\\,\\text{V}$." },
        { title: "Work across a voltage", problem: "How much work moves a $2\\,\\text{C}$ charge through a potential difference of $5\\,\\text{V}$?", steps: ["$W = q\\,\\Delta V$.", "$W = 2 \\times 5$."], answer: "$W = 10\\,\\text{J}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "$U = qV$; $V = kQ/r$; field is perpendicular to equipotentials." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $U = qV$, $V = kQ/r$, and $W = q\\Delta V$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: the field is the slope of the potential", content: { markdown: "Field and potential are two views of the same thing. In a uniform field (like that between capacitor plates), they are linked by\n\n$$E = \\frac{\\Delta V}{d},$$\n\nwhere $d$ is the separation — which is why field can also be quoted in **volts per metre** (V/m), the same as N/C. More generally the field is the (negative) **gradient** of the potential: it points 'downhill,' from high $V$ to low, and is steepest where $V$ changes fastest.\n\nThis is the electric twin of gravity: gravitational field points downhill in height, electric field points downhill in potential. Equipotentials are the contour lines of an electric landscape, and the field always cuts across them at right angles." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Potential and potential energy are the same thing.\"** Potential $V$ is energy *per unit charge* (volts); potential energy $U = qV$ is the actual energy (joules) of a specific charge. One depends on the charge placed there; the other doesn't.\n\n**\"Potential goes as $1/r^2$ like the field.\"** No — potential of a point charge goes as $1/r$. Only the force and field fall off as $1/r^2$.\n\n**\"Moving a charge along an equipotential takes work.\"** It takes zero work, because $V$ doesn't change along the surface — the field is perpendicular to it." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Potential energy of two point charges: $U = kQq/r$ (note the single $1/r$).", "Potential is energy per unit charge: $V = U/q$, so $U = qV$; measured in volts ($1\\,\\text{V} = 1\\,\\text{J/C}$).", "Potential of a point charge: $V = kQ/r$.", "Work to move charge across a voltage: $W = q\\,\\Delta V$.", "Equipotentials are constant-$V$ surfaces; the field is perpendicular to them, pointing high $V$ → low $V$."], formulas: [{ label: "Potential energy", tex: "U = k\\dfrac{Q q}{r}" }, { label: "Potential", tex: "V = \\dfrac{U}{q} = k\\dfrac{Q}{r}" }, { label: "Work across a voltage", tex: "W = q\\,\\Delta V" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "A charge $q = 4\\,\\text{C}$ sits where the potential is $V = 3\\,\\text{V}$. Find its potential energy in joules.", answer: { value: 12, tolerance: 0 }, difficulty: 1, explanation: "$U = qV = 4 \\times 3 = 12\\,\\text{J}$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Electric potential is measured in:", options: ["newtons", "volts", "amps", "ohms"], answer: 1, difficulty: 1, explanation: "Potential is energy per unit charge, measured in volts." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "The electric field is always perpendicular to equipotential surfaces.", answer: true, difficulty: 2, explanation: "Yes — no work is done moving along an equipotential, so the field has no component along it." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Find the potential $0.50\\,\\text{m}$ from a charge $Q = 2\\times10^{-9}\\,\\text{C}$ (use $k = 9\\times10^{9}$), in volts.", answer: { value: 36, tolerance: 0.5 }, difficulty: 3, hint: "$V = kQ/r$.", explanation: "$9\\times10^{9}\\times 2\\times10^{-9} / 0.50 = 18/0.50 = 36\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "How much work (in joules) moves a $2\\,\\text{C}$ charge through a potential difference of $5\\,\\text{V}$?", answer: { value: 10, tolerance: 0 }, difficulty: 2, hint: "$W = q\\,\\Delta V$.", explanation: "$2 \\times 5 = 10\\,\\text{J}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the potential energy $U$ of a charge $q$ at potential $V$. (Type like `q*V`.)", answer: { expr: "q*V", vars: ["q", "V"] }, difficulty: 2, hint: "Energy is charge times potential.", explanation: "$U = qV$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "The potential of a point charge falls off with distance as:", options: ["$\\propto 1/r$", "$\\propto 1/r^2$", "$\\propto r$", "$\\propto r^2$"], answer: 0, difficulty: 3, hint: "Compare with the field's $1/r^2$.", explanation: "Potential goes as $1/r$; only the field and force go as $1/r^2$." },
      { scope: "PRACTICE", kind: "GRAPH", prompt: "Taking $kQ = 1$, a point charge's potential is $V = 1/r$. Graph it (enter $V$ as a function of $r$, use $x$ for $r$).", answer: { expr: "1/x", domain: [0.5, 4], variable: "x" }, difficulty: 4, hint: "Inverse, not inverse-square.", explanation: "$V = 1/r$ falls off more gently than the $1/r^2$ field." },
    ],
  },

  // ───────────────────────── 4. Conductors in Equilibrium ─────────────────────────
  {
    slug: "conductors-in-equilibrium",
    title: "Conductors in Equilibrium",
    tagline: "Charge on the surface, zero field inside",
    estMinutes: 15,
    xpReward: 155,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "The Quiet Interior", sub: "Pile charge onto a metal and it races to the surface, leaving the inside perfectly field-free — the secret behind shielding." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Why are you safe inside a car struck by lightning? Why are sensitive electronics wrapped in metal cans? The answer is how **conductors** behave once their charges settle into **electrostatic equilibrium**.\n\nA conductor is a material — metals especially — whose charges are free to move. When they stop moving, the configuration that results is remarkably simple and powerful, and it underlies shielding, grounding, and the very design of capacitors." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "A **conductor** has charges (electrons) free to move. **Electrostatic equilibrium** is reached when those charges have rearranged so that nothing pushes them any further — there is no net motion. Three consequences follow, and they are the heart of this lesson:\n\n1. **The electric field inside a conductor is zero.** If any field remained, free charges would feel a force and keep moving — contradicting equilibrium. So the interior field must vanish.\n\n2. **Excess charge resides entirely on the surface.** Because like charges repel, they spread out as far apart as possible — which means onto the outer surface. The bulk interior stays neutral.\n\n3. **The field just outside is perpendicular to the surface.** Any sideways component would push surface charges along the surface; in equilibrium none do, so the external field meets the surface at right angles. The whole conductor is a single **equipotential**.\n\nThe practical payoff is **electrostatic shielding**: a hollow conductor (a 'Faraday cage') keeps its interior field-free regardless of charges outside. That is why a car shields you from lightning and a metal box shields delicate circuits." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Field inside a charged sphere", problem: "A solid metal sphere carries excess charge in equilibrium. What is the electric field at its center?", steps: ["In a conductor at equilibrium the interior field is zero.", "The center is interior, so $E = 0$ there."], answer: "$E = 0$ — there is no field anywhere inside the metal." },
        { title: "Where does the charge go?", problem: "You deposit $-6\\,\\mu\\text{C}$ onto an isolated metal block. Where does the charge end up?", steps: ["Like charges repel and conductors let charge move freely.", "They spread to maximize separation — entirely onto the outer surface."], answer: "All of it sits on the outer surface; the interior carries none." },
        { title: "Why the Faraday cage works", problem: "A sensitive circuit is sealed in a closed metal box. A strong charge is brought nearby. What field does the circuit feel?", steps: ["The conductor rearranges its charges to cancel the field inside.", "Inside a hollow conductor the field is zero regardless of external charges."], answer: "Essentially zero — the box shields the circuit (a Faraday cage)." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Inside a conductor: $E = 0$; charge on the surface; surface is an equipotential." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Apply the three equilibrium results and the idea of shielding." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: charge crowds at sharp points", content: { markdown: "Surface charge is *not* spread evenly on an irregular conductor. It piles up where the surface curves most sharply — at **points and edges** — and thins out over flat regions. Because surface charge density there is high, the field just outside a sharp point is intense.\n\nThis is exactly why **lightning rods** are pointed: the strong field at the tip ionizes the surrounding air and bleeds charge off harmlessly, or channels a strike to a safe path. The same effect (corona discharge) is why high-voltage equipment avoids sharp corners. Equilibrium fixes *that* charge is on the surface; geometry decides *how it is distributed* there." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Charge spreads through the whole volume of a conductor.\"** No — in equilibrium all excess charge sits on the outer surface; the interior is neutral and field-free.\n\n**\"There can be a small field inside a conductor.\"** In electrostatic equilibrium the interior field is exactly zero. Any leftover field would keep pushing charges until it cancels.\n\n**\"Shielding requires a solid block of metal.\"** A thin hollow shell — even a mesh, for slow fields — works. It is the conductor's surface, not its thickness, that does the shielding." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["In a conductor at electrostatic equilibrium the interior electric field is zero.", "Excess charge resides entirely on the outer surface.", "The field just outside is perpendicular to the surface; the whole conductor is an equipotential.", "A hollow conductor shields its interior (Faraday cage).", "Surface charge crowds at sharp points, giving strong local fields (lightning rods)."], formulas: [{ label: "Field inside a conductor", tex: "E_{\\text{inside}} = 0" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The electric field inside a conductor at electrostatic equilibrium is:", options: ["zero", "very large", "equal to $kQ/r^2$", "perpendicular to the surface"], answer: 0, difficulty: 2, explanation: "If it weren't zero, free charges would keep moving — contradicting equilibrium." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Excess charge on a conductor in equilibrium resides on its outer surface.", answer: true, difficulty: 2, explanation: "Like charges repel and spread out, ending up on the surface; the interior is neutral." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Just outside a conductor's surface in equilibrium, the field is:", options: ["parallel to the surface", "perpendicular to the surface", "zero", "always pointing inward"], answer: 1, difficulty: 3, explanation: "Any parallel component would move surface charges; in equilibrium the field is perpendicular." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "Why are you relatively safe inside a metal car during a lightning storm?", options: ["rubber tires insulate you", "the metal shell keeps the interior field near zero (Faraday cage)", "the car is grounded by its weight", "lightning cannot reach a car"], answer: 1, difficulty: 3, hint: "Think about the field inside a hollow conductor.", explanation: "The conducting shell shields the interior — a Faraday cage." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "A whole conductor in equilibrium is a single equipotential.", answer: true, difficulty: 2, hint: "Zero interior field means no potential difference within it.", explanation: "With no interior field, no work is needed to move between any two points, so $V$ is constant throughout." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A solid metal sphere holds excess charge in equilibrium. What is the electric field (in N/C) at its exact center?", answer: { value: 0, tolerance: 0 }, difficulty: 2, hint: "The center is inside the conductor.", explanation: "The field inside a conductor at equilibrium is zero everywhere, including the center." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "On an irregularly shaped conductor, charge spreads perfectly evenly over the surface.", answer: false, difficulty: 3, hint: "Think about sharp points versus flat areas.", explanation: "Charge crowds at sharp points and edges, where the local field is strongest." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "A pointed lightning rod works because at a sharp tip the:", options: ["field is weakest", "charge density and field are very high", "conductor stops conducting", "potential is zero"], answer: 1, difficulty: 3, hint: "Charge crowds at points.", explanation: "High charge density at the tip makes a strong field that bleeds off or channels the strike safely." },
    ],
  },

  // ───────────────────────── 5. Capacitance ─────────────────────────
  {
    slug: "capacitance",
    title: "Capacitance",
    tagline: "Storing charge and energy in a field",
    estMinutes: 16,
    xpReward: 160,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Bottling the Field", sub: "Two conductors, a little separation, and you can store charge — and the energy that comes with it — in the electric field between them." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "A **capacitor** is two conductors holding equal and opposite charge, storing energy in the field between them. They are everywhere: smoothing power supplies, flashing a camera, timing circuits, holding memory bits.\n\nCapacitance is the natural endpoint of electrostatics — it ties together charge, field, potential, and energy in one device. The parallel-plate capacitor, with its uniform field, is the cleanest example and the one to master first." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Capacitance** $C$ measures how much charge a capacitor stores per volt applied across it:\n\n$$C = \\frac{Q}{V}.$$\n\nIts unit is the **farad** (F), where $1\\,\\text{F} = 1\\,\\text{C/V}$. A farad is enormous, so real capacitors are usually microfarads ($\\mu\\text{F}$) or smaller.\n\nNotice that $C$ is a property of the *geometry* — it does not change when you add charge. Put more charge on and the voltage rises in proportion, keeping $Q/V$ fixed.\n\nFor a **parallel-plate capacitor** (plate area $A$, separation $d$, vacuum between):\n\n$$C = \\varepsilon_0\\,\\frac{A}{d},$$\n\nwhere $\\varepsilon_0 = 8.85\\times10^{-12}\\,\\text{F/m}$. Bigger plates store more; a smaller gap stores more (the plates pull harder on each other's charge).\n\nCharging a capacitor stores energy in the field. The **energy stored** is\n\n$$E = \\tfrac{1}{2}\\,C V^2 = \\tfrac{1}{2}\\,Q V = \\frac{Q^2}{2C}.$$\n\nAll three forms are equivalent (use $Q = CV$ to convert between them); pick whichever matches your knowns." } },
      { kind: "CONCEPT", title: "Derivation: the ½ in the stored energy", content: { markdown: "Why $\\tfrac12 CV^2$ and not $CV^2$? Because the voltage rises *as you charge it.*\n\nThe work to add a small charge $dq$ when the capacitor already sits at voltage $v = q/C$ is $dW = v\\,dq = (q/C)\\,dq$. Summing (integrating) from $0$ up to the final charge $Q$:\n\n$$E = \\int_0^Q \\frac{q}{C}\\,dq = \\frac{1}{C}\\cdot\\frac{Q^2}{2} = \\frac{Q^2}{2C}.$$\n\nThe early charges go on cheaply (low voltage), the later ones cost more — so the *average* cost is half the final voltage. Substituting $Q = CV$ turns $\\dfrac{Q^2}{2C}$ into the familiar $\\tfrac12 CV^2$. That factor of $\\tfrac12$ is the signature of this build-up, exactly like the $\\tfrac12 k x^2$ of a spring." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Capacitance from charge and voltage", problem: "A capacitor holds $Q = 12\\,\\text{C}$ at $V = 4\\,\\text{V}$. Find its capacitance.", steps: ["$C = Q/V$.", "$C = 12/4$."], answer: "$C = 3\\,\\text{F}$." },
        { title: "Stored energy", problem: "A $2\\,\\text{F}$ capacitor is charged to $3\\,\\text{V}$. How much energy does it store?", steps: ["$E = \\tfrac12 C V^2$.", "$E = \\tfrac12 (2)(3^2) = \\tfrac12 (2)(9)$."], answer: "$E = 9\\,\\text{J}$." },
        { title: "Charge stored", problem: "A $5\\,\\text{F}$ capacitor is connected across $2\\,\\text{V}$. How much charge does it hold?", steps: ["Rearrange $C = Q/V$ to $Q = CV$.", "$Q = 5 \\times 2$."], answer: "$Q = 10\\,\\text{C}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "$C = Q/V$; parallel plates $C = \\varepsilon_0 A/d$; energy $E = \\tfrac12 CV^2$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $C = Q/V$ (so $Q = CV$) and $E = \\tfrac12 CV^2$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: dielectrics boost capacitance", content: { markdown: "Real capacitors rarely have vacuum between the plates — they have an insulating **dielectric** (plastic, ceramic, oxide). Inserting a dielectric multiplies the capacitance by its **dielectric constant** $\\kappa$ (a number greater than 1):\n\n$$C = \\kappa\\,\\varepsilon_0\\,\\frac{A}{d}.$$\n\nThe dielectric's molecules polarize in the field, partly canceling it, which lets the plates hold more charge at the same voltage. Dielectrics also let the plates sit closer without sparking across, raising $C$ further. This is how a capacitor the size of a grain of rice can reach microfarads — packing huge plate area and a thin high-$\\kappa$ layer into a tiny volume." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Adding more charge increases the capacitance.\"** No — $C$ is set by geometry. Adding charge raises the voltage in proportion, so $Q/V$ stays fixed.\n\n**\"Stored energy is just $QV$.\"** It's $\\tfrac12 QV$. The voltage climbs as the capacitor charges, so the average cost is half the final value — hence the factor of $\\tfrac12$.\n\n**\"A wider gap stores more charge.\"** The opposite: $C = \\varepsilon_0 A/d$, so increasing $d$ *decreases* capacitance. A smaller gap (and larger area) stores more." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Capacitance is charge per volt: $C = Q/V$, in farads ($1\\,\\text{F} = 1\\,\\text{C/V}$).", "$C$ depends on geometry, not on how much charge is stored.", "Parallel-plate capacitor: $C = \\varepsilon_0 A/d$ — larger area or smaller gap means more capacitance.", "Stored energy: $E = \\tfrac12 CV^2 = \\tfrac12 QV = Q^2/(2C)$.", "A dielectric multiplies capacitance by $\\kappa > 1$."], formulas: [{ label: "Capacitance", tex: "C = \\dfrac{Q}{V}" }, { label: "Parallel-plate", tex: "C = \\varepsilon_0\\dfrac{A}{d}" }, { label: "Stored energy", tex: "E = \\tfrac{1}{2}C V^2" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "A capacitor holds $Q = 12\\,\\text{C}$ at $V = 4\\,\\text{V}$. Find its capacitance in farads.", answer: { value: 3, tolerance: 0 }, difficulty: 2, explanation: "$C = Q/V = 12/4 = 3\\,\\text{F}$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Capacitance is defined as:", options: ["$Q V$", "$Q/V$", "$V/Q$", "$\\tfrac12 QV$"], answer: 1, difficulty: 1, explanation: "$C = Q/V$, the charge stored per volt." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "For a parallel-plate capacitor, increasing the plate separation $d$ decreases the capacitance.", answer: true, difficulty: 3, explanation: "$C = \\varepsilon_0 A/d$, so larger $d$ gives smaller $C$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $2\\,\\text{F}$ capacitor is charged to $3\\,\\text{V}$. Energy stored in joules?", answer: { value: 9, tolerance: 0 }, difficulty: 2, hint: "$E = \\tfrac12 C V^2$.", explanation: "$\\tfrac12 (2)(9) = 9\\,\\text{J}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $5\\,\\text{F}$ capacitor is connected across $2\\,\\text{V}$. Charge stored in coulombs?", answer: { value: 10, tolerance: 0 }, difficulty: 2, hint: "$Q = CV$.", explanation: "$5 \\times 2 = 10\\,\\text{C}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the energy $E$ stored in a capacitor in terms of its capacitance $C$ and voltage $V$. (Type like `(1/2)*C*V^2`.)", answer: { expr: "(1/2)*C*V^2", vars: ["C", "V"] }, difficulty: 3, hint: "Half of capacitance times voltage squared.", explanation: "$E = \\tfrac12 C V^2$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "Doubling only the plate area $A$ of a parallel-plate capacitor changes its capacitance to:", options: ["half", "double", "unchanged", "one-quarter"], answer: 1, difficulty: 3, hint: "$C = \\varepsilon_0 A/d$.", explanation: "$C \\propto A$, so doubling the area doubles the capacitance." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Inserting a dielectric between the plates increases the capacitance.", answer: true, difficulty: 3, hint: "Dielectric constant $\\kappa > 1$.", explanation: "$C = \\kappa\\varepsilon_0 A/d$ with $\\kappa > 1$, so capacitance rises." },
    ],
  },
];
