import type { LessonSeed } from "../types.js";

/**
 * Classical Mechanics — Fluids (the physics of liquids and gases at rest and in
 * motion, intro-university). Algebra-based, with the key relations derived from
 * pressure, force balance, and conservation ideas.
 */
export const fluidsLessons: LessonSeed[] = [
  // ───────────────────────── 1. Density & Pressure ─────────────────────────
  {
    slug: "density-and-pressure",
    title: "Density & Pressure",
    tagline: "How much stuff, and how hard it pushes",
    estMinutes: 14,
    xpReward: 150,
    difficulty: 2,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "The Fluid State", sub: "Before a fluid can float a ship or lift a plane, we need two ideas: how tightly its matter is packed, and how forcefully it pushes on every surface it touches." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Why does a steel ship float while a steel nail sinks? Why do your ears pop in a plane? Why can a thumbtack pierce a board when your thumb cannot? Every one of these questions turns on two quantities: **density** and **pressure**.\n\nDensity tells you how much mass is crammed into a given volume. Pressure tells you how a force is *spread* over an area. Confusing force with pressure — or mass with density — is the root of most fluid mistakes, so we pin them down precisely first." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Density** ($\\rho$, the Greek letter *rho*) is mass per unit volume:\n\n$$\\rho = \\frac{m}{V}$$\n\nIts SI unit is kilograms per cubic metre, $\\text{kg/m}^3$. Water is about $1000\\,\\text{kg/m}^3$; air at sea level is roughly $1.2\\,\\text{kg/m}^3$. Density is an *intensive* property — it does not depend on how much of the substance you have. A drop of water and a lake have the same density.\n\n**Pressure** ($P$) is the force pressing perpendicular to a surface, divided by the area of that surface:\n\n$$P = \\frac{F}{A}$$\n\nIts SI unit is the **pascal**: $1\\,\\text{Pa} = 1\\,\\text{N/m}^2$. Because area sits in the denominator, the *same* force makes a *larger* pressure when squeezed onto a *smaller* area — which is exactly why a sharp knife or a thin tack works.\n\nA crucial feature of fluids: at a point, pressure pushes **equally in all directions**. It is a scalar, not a vector — it has no single direction of its own." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Density of a block", problem: "A metal block has mass $2.7\\,\\text{kg}$ and volume $1.0\\times 10^{-3}\\,\\text{m}^3$. Find its density.", steps: ["Use $\\rho = m/V$.", "$\\rho = 2.7 / (1.0\\times 10^{-3}) = 2700\\,\\text{kg/m}^3$.", "(That's aluminium.)"], answer: "$\\rho = 2700\\,\\text{kg/m}^3$." },
        { title: "Pressure under a foot", problem: "A person weighing $600\\,\\text{N}$ stands on one foot of area $0.015\\,\\text{m}^2$. What pressure do they exert on the floor?", steps: ["Use $P = F/A$.", "$P = 600 / 0.015 = 40\\,000\\,\\text{Pa} = 40\\,\\text{kPa}$."], answer: "$P = 40\\,000\\,\\text{Pa}$." },
        { title: "Same force, smaller area", problem: "The same $600\\,\\text{N}$ now presses through a tack tip of area $1.0\\times 10^{-6}\\,\\text{m}^2$. What is the pressure?", steps: ["$P = F/A = 600 / (1.0\\times 10^{-6})$.", "$P = 6.0\\times 10^{8}\\,\\text{Pa}$ — millions of times larger.", "Shrinking the area is what lets a tack puncture wood."], answer: "$P = 6.0\\times 10^{8}\\,\\text{Pa}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Keep force and pressure, mass and density, distinct." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use SI units: kilograms, metres, newtons, pascals." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: specific gravity and other units", content: { markdown: "Engineers often quote **specific gravity** — the ratio of a substance's density to that of water, $\\text{SG} = \\rho / \\rho_{\\text{water}}$. It is dimensionless: a specific gravity of $13.6$ (mercury) means it is $13.6$ times denser than water. Anything with $\\text{SG} < 1$ floats on water.\n\nPressure also comes in many practical units. One **atmosphere** is $1\\,\\text{atm} = 101\\,325\\,\\text{Pa} \\approx 101\\,\\text{kPa}$, the average air pressure at sea level. Weather reports use the bar ($1\\,\\text{bar} = 10^5\\,\\text{Pa}$); tyre gauges often read in psi (pounds per square inch). They all measure the same physical quantity, $F/A$." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Heavier things always create more pressure.\"** Pressure depends on force *and* area. A heavy elephant on broad feet can exert less ground pressure than a slim woman in stiletto heels.\n\n**\"Density depends on how big the sample is.\"** Density is intensive — a teaspoon and a tanker of the same oil have identical density. Mass and volume both grow together.\n\n**\"Pressure pushes in one direction.\"** In a fluid, pressure at a point acts equally in every direction; it is a scalar, not a vector." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Density $\\rho = m/V$, in $\\text{kg/m}^3$ — an intensive property.", "Pressure $P = F/A$, measured in pascals ($1\\,\\text{Pa} = 1\\,\\text{N/m}^2$).", "Smaller area means larger pressure for the same force.", "Pressure in a fluid acts equally in all directions (a scalar)."], formulas: [{ label: "Density", tex: "\\rho = \\dfrac{m}{V}" }, { label: "Pressure", tex: "P = \\dfrac{F}{A}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Density is defined as:", options: ["$F/A$", "$m/V$", "$V/m$", "$m\\cdot V$"], answer: 1, difficulty: 1, explanation: "Density is mass per unit volume, $\\rho = m/V$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "The pascal is equal to one newton per square metre.", answer: true, difficulty: 1, explanation: "By definition, $1\\,\\text{Pa} = 1\\,\\text{N/m}^2$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "For the same applied force, pressure is greatest when the contact area is:", options: ["largest", "smallest", "exactly $1\\,\\text{m}^2$", "irrelevant"], answer: 1, difficulty: 2, explanation: "$P = F/A$: a smaller area gives a larger pressure." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A substance has mass $5.0\\,\\text{kg}$ and volume $0.0025\\,\\text{m}^3$. Density in $\\text{kg/m}^3$?", answer: { value: 2000, tolerance: 1 }, hint: "$\\rho = m/V$.", explanation: "$5.0 / 0.0025 = 2000\\,\\text{kg/m}^3$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A force of $250\\,\\text{N}$ presses on an area of $0.50\\,\\text{m}^2$. Pressure in pascals?", answer: { value: 500, tolerance: 1 }, hint: "$P = F/A$.", explanation: "$250 / 0.50 = 500\\,\\text{Pa}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Water has density $1000\\,\\text{kg/m}^3$. What is the mass of $2.0\\,\\text{m}^3$ of water, in kg?", answer: { value: 2000, tolerance: 1 }, hint: "$m = \\rho V$.", explanation: "$m = 1000\\times 2.0 = 2000\\,\\text{kg}$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "The SI unit of density is:", options: ["$\\text{kg/m}^3$", "$\\text{N/m}^2$", "$\\text{kg}\\cdot\\text{m}$", "$\\text{Pa}$"], answer: 0, hint: "Mass over volume.", explanation: "$\\rho = m/V$ has units of $\\text{kg/m}^3$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Solve $P = F/A$ for the force $F$ in terms of $P$ and $A$. (Type like `P*A`.)", answer: { expr: "P*A", vars: ["P", "A"] }, difficulty: 2, hint: "Multiply both sides by the area.", explanation: "$F = P\\cdot A$." },
    ],
  },

  // ─────────────────────────── 2. Pressure with Depth ───────────────────────────
  {
    slug: "pressure-with-depth",
    title: "Pressure with Depth",
    tagline: "Why the deep end pushes harder",
    estMinutes: 15,
    xpReward: 155,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Going Deeper", sub: "Dive to the bottom of a pool and your ears feel it. Pressure in a fluid grows with depth — and we can write down exactly how fast." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Dam walls are built thick at the bottom and thin at the top. Submarines have crush depths. Your blood pressure is measured relative to the air around you. All of these come from one fact: in a fluid at rest, **pressure increases with depth** because of the weight of the fluid stacked above.\n\nUnderstanding this lets you design tanks, read pressure gauges correctly, and explain why a tall dam need not hold back a *heavy* lake — only a *deep* one." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "In a fluid of density $\\rho$ at rest, the pressure at depth $h$ below the surface is:\n\n$$P = P_0 + \\rho g h$$\n\nHere $P_0$ is the pressure pushing down on the surface (often atmospheric pressure), $g \\approx 9.8\\,\\text{m/s}^2$, and $h$ is the depth measured **straight down** from the surface.\n\nTwo terms, two ideas:\n\n- **Absolute pressure** is the full value $P = P_0 + \\rho g h$ — the total push, including the atmosphere overhead.\n- **Gauge pressure** is the extra part, $P_{\\text{gauge}} = \\rho g h = P - P_0$ — what a tyre or blood-pressure gauge reads, since it measures *above* atmospheric.\n\nA striking consequence: the pressure depends **only on the depth $h$**, not on the shape or width of the container. Two points at the **same depth** in a connected fluid have the **same pressure**, whether under a narrow tube or a wide lake. This is why water finds its own level and why a thin straw of water can, in principle, balance a whole tank." } },
      { kind: "CONCEPT", title: "Derivation: weight of the column above", content: { markdown: "Imagine an imaginary column of fluid of cross-sectional area $A$ reaching from the surface down to depth $h$. The fluid is at rest, so the forces on this column balance.\n\nThe column's volume is $V = A h$, so its mass is $m = \\rho V = \\rho A h$ and its weight is $W = mg = \\rho A h g$.\n\nAt the bottom, the surrounding fluid pushes up with force $P\\,A$. At the top, the surface pressure pushes down with $P_0\\,A$, plus the column's own weight pulls down. Balancing up against down:\n\n$$P\\,A = P_0\\,A + \\rho A h g.$$\n\nDivide through by the area $A$:\n\n$$P = P_0 + \\rho g h.$$\n\nThe area cancels — which is exactly why pressure depends on depth alone, not on the container's width." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Gauge pressure in a pool", problem: "Find the gauge pressure at the bottom of a $3.0\\,\\text{m}$ deep pool. ($\\rho = 1000\\,\\text{kg/m}^3$, $g = 9.8\\,\\text{m/s}^2$.)", steps: ["Gauge pressure is $\\rho g h$.", "$P_{\\text{gauge}} = 1000\\times 9.8\\times 3.0 = 29\\,400\\,\\text{Pa}$."], answer: "$P_{\\text{gauge}} \\approx 29\\,400\\,\\text{Pa}$ (about $29\\,\\text{kPa}$)." },
        { title: "Absolute pressure", problem: "For that same pool bottom, find the absolute pressure, taking $P_0 = 101\\,000\\,\\text{Pa}$.", steps: ["$P = P_0 + \\rho g h$.", "$P = 101\\,000 + 29\\,400 = 130\\,400\\,\\text{Pa}$."], answer: "$P \\approx 130\\,400\\,\\text{Pa}$." },
        { title: "Same depth, same pressure", problem: "A U-shaped tube is open at both ends and filled with water. Point X is $0.20\\,\\text{m}$ below the surface in the left arm; point Y is $0.20\\,\\text{m}$ below the surface in the (wider) right arm. Compare the gauge pressures.", steps: ["Gauge pressure depends only on depth: $\\rho g h$.", "Both points are at $h = 0.20\\,\\text{m}$, so $\\rho g h$ is identical.", "Container width is irrelevant."], answer: "Equal — same depth means same pressure." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Distinguish gauge from absolute; remember $h$ is depth, not width." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $\\rho = 1000\\,\\text{kg/m}^3$ for water and $g = 9.8\\,\\text{m/s}^2$ unless told otherwise." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: barometers and the atmosphere", content: { markdown: "The same law explains how a **mercury barometer** measures air pressure. Atmospheric pressure pushing on a dish of mercury holds up a column in a sealed tube; the height $h$ of that column satisfies $P_{\\text{atm}} = \\rho_{\\text{Hg}}\\, g\\, h$. At sea level this gives about $760\\,\\text{mm}$ of mercury — the origin of the unit mmHg still used in medicine.\n\nThe atmosphere itself is a fluid, but because air is compressible (its density falls with altitude), pressure does *not* drop linearly going up; it falls roughly exponentially. The simple $P = P_0 + \\rho g h$ assumes constant density, so it is exact for liquids but only a local approximation for gases." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A wider tank has higher pressure at the bottom.\"** No — pressure depends on depth $h$ alone, not on width or total volume. A deep, thin column and a deep, wide lake have the same bottom pressure.\n\n**\"Gauge and absolute pressure are the same thing.\"** Gauge pressure leaves out the atmosphere: $P_{\\text{abs}} = P_0 + P_{\\text{gauge}}$. A flat tyre reads zero gauge but still holds atmospheric pressure inside.\n\n**\"Pressure depends on the amount of fluid above.\"** It depends on the *depth*, not the total weight of fluid in the container — the cancelled area in the derivation is why." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Pressure with depth: $P = P_0 + \\rho g h$.", "Gauge pressure is $\\rho g h$; absolute pressure adds the surface pressure $P_0$.", "Pressure depends only on depth $h$ — not on container shape or width.", "Points at equal depth in a connected fluid have equal pressure."], formulas: [{ label: "Absolute pressure", tex: "P = P_0 + \\rho g h" }, { label: "Gauge pressure", tex: "P_{\\text{gauge}} = \\rho g h" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "In a fluid at rest, pressure increases with depth because of:", options: ["the temperature", "the weight of fluid above", "the container's colour", "the surface tension"], answer: 1, difficulty: 2, explanation: "The fluid column above each point adds its weight, raising the pressure." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Two points at the same depth in a connected body of water have the same pressure, even if the container is wider at one point.", answer: true, difficulty: 2, explanation: "Pressure depends only on depth, so equal depths give equal pressures." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Gauge pressure is:", options: ["$P_0 + \\rho g h$", "$\\rho g h$", "$P_0$ only", "$\\rho / (g h)$"], answer: 1, difficulty: 2, explanation: "Gauge pressure is the part above atmospheric: $P - P_0 = \\rho g h$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Gauge pressure $5.0\\,\\text{m}$ down in water ($\\rho = 1000$, $g = 9.8$), in pascals?", answer: { value: 49000, tolerance: 100 }, hint: "$\\rho g h$.", explanation: "$1000\\times 9.8\\times 5.0 = 49\\,000\\,\\text{Pa}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "At a depth where the gauge pressure is $19\\,600\\,\\text{Pa}$ in water ($\\rho=1000$, $g=9.8$), what is the depth in metres?", answer: { value: 2, tolerance: 0.1 }, difficulty: 3, hint: "$h = P_{\\text{gauge}} / (\\rho g)$.", explanation: "$h = 19\\,600 / (1000\\times 9.8) = 2.0\\,\\text{m}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Absolute pressure $10\\,\\text{m}$ deep in water, with $P_0 = 101\\,000\\,\\text{Pa}$ ($\\rho=1000$, $g=9.8$), in pascals?", answer: { value: 199000, tolerance: 200 }, difficulty: 3, hint: "$P = P_0 + \\rho g h$.", explanation: "$101\\,000 + 1000\\times 9.8\\times 10 = 101\\,000 + 98\\,000 = 199\\,000\\,\\text{Pa}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the gauge pressure at depth $h$ in a fluid of density $\\rho$ under gravity $g$. (Type like `rho*g*h`.)", answer: { expr: "rho*g*h", vars: ["rho", "g", "h"] }, difficulty: 2, hint: "Gauge pressure is the depth term only.", explanation: "$P_{\\text{gauge}} = \\rho g h$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "A tall, narrow column of water can exert the same bottom pressure as a wide lake of the same depth.", answer: true, difficulty: 3, hint: "Does width appear in $P = P_0 + \\rho g h$?", explanation: "Pressure depends on depth alone; width cancels out, so equal depths give equal pressures." },
    ],
  },

  // ───────────────── 3. Pascal's & Archimedes' Principles ─────────────────
  {
    slug: "pascal-and-archimedes",
    title: "Pascal's & Archimedes' Principles",
    tagline: "Multiplying force, and the secret of floating",
    estMinutes: 17,
    xpReward: 165,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Lift and Float", sub: "A small push on a small piston can hoist a car; a steel ship rides on water. Two ancient principles — Pascal's and Archimedes' — explain both." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Press the brake pedal and a hydraulic system multiplies your foot's force enough to stop two tonnes of car. That is **Pascal's principle**. Drop a coin and it sinks, yet a steel ship floats — that is **Archimedes' principle**. Together they power car lifts, hydraulic presses, submarines, hot-air balloons, and the design of every hull that has ever sailed." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Pascal's principle.** A pressure applied to an enclosed fluid is transmitted *undiminished* to every part of the fluid. In a **hydraulic** system with two connected pistons, the pressure is the same on both sides:\n\n$$\\frac{F_1}{A_1} = \\frac{F_2}{A_2}$$\n\nSo a small force $F_1$ on a small piston $A_1$ produces a large force $F_2 = F_1\\,(A_2/A_1)$ on a large piston. The area ratio is the **force multiplication**. (You pay for it in distance: the big piston moves less, conserving energy.)\n\n**Archimedes' principle.** Any object immersed in a fluid feels an upward **buoyant force** equal to the *weight of the fluid it displaces*:\n\n$$F_b = \\rho_{\\text{fluid}}\\, V\\, g$$\n\nwhere $V$ is the volume of fluid pushed aside (for a fully submerged object, its whole volume).\n\n**Float or sink?** Compare the object's average density to the fluid's:\n\n- $\\rho_{\\text{object}} < \\rho_{\\text{fluid}}$ → it **floats** (buoyancy can exceed its weight).\n- $\\rho_{\\text{object}} > \\rho_{\\text{fluid}}$ → it **sinks**.\n- A floating object sinks just far enough that the displaced fluid's weight equals its own weight. A steel ship floats because its overall shape — steel plus the air inside — has an average density below water's." } },
      { kind: "CONCEPT", title: "Derivation: buoyancy from pressure difference", content: { markdown: "Buoyancy is just the depth-pressure law in disguise. Take a block of height $\\Delta h$ and cross-section $A$ submerged in a fluid of density $\\rho$, with its top at depth $h_1$ and bottom at $h_2 = h_1 + \\Delta h$.\n\nPressure pushes harder on the *bottom* (deeper) face than on the top. The net upward force is:\n\n$$F_b = P_{\\text{bottom}}A - P_{\\text{top}}A = (\\rho g h_2 - \\rho g h_1)A = \\rho g\\,(\\Delta h)\\,A.$$\n\nBut $(\\Delta h)A = V$, the block's volume — which equals the volume of fluid displaced. So:\n\n$$F_b = \\rho_{\\text{fluid}}\\, V\\, g,$$\n\nexactly Archimedes' principle. The sideways pressures cancel; only the top-bottom difference survives, and it always points *up*." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Hydraulic lift", problem: "A hydraulic lift has pistons of area $A_1 = 0.0050\\,\\text{m}^2$ and $A_2 = 0.50\\,\\text{m}^2$. A force of $200\\,\\text{N}$ is applied to the small piston. What force appears at the large one?", steps: ["Equal pressure: $F_2 = F_1\\,(A_2/A_1)$.", "$A_2/A_1 = 0.50/0.0050 = 100$.", "$F_2 = 200\\times 100 = 20\\,000\\,\\text{N}$."], answer: "$F_2 = 20\\,000\\,\\text{N}$ — a hundredfold multiplication." },
        { title: "Buoyant force on a submerged block", problem: "A block of volume $2.0\\times 10^{-3}\\,\\text{m}^3$ is fully submerged in water ($\\rho = 1000\\,\\text{kg/m}^3$, $g = 9.8$). Find the buoyant force.", steps: ["$F_b = \\rho_{\\text{fluid}} V g$.", "$F_b = 1000\\times (2.0\\times 10^{-3})\\times 9.8 = 19.6\\,\\text{N}$."], answer: "$F_b = 19.6\\,\\text{N}$ upward." },
        { title: "Float or sink?", problem: "An object has density $700\\,\\text{kg/m}^3$. Will it float or sink in water ($1000\\,\\text{kg/m}^3$)? In oil ($850\\,\\text{kg/m}^3$)?", steps: ["Compare densities: object $700$ vs water $1000$ → object is less dense → floats.", "Object $700$ vs oil $850$ → still less dense → floats.", "It would float on both."], answer: "Floats in water and in oil (it is less dense than both)." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Track which area and which density each formula uses." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $\\rho_{\\text{water}} = 1000\\,\\text{kg/m}^3$ and $g = 9.8\\,\\text{m/s}^2$ unless told otherwise." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: apparent weight and fraction submerged", content: { markdown: "When you weigh a submerged object on a scale, you measure its **apparent weight**: $W_{\\text{apparent}} = W - F_b$. A rock that weighs $50\\,\\text{N}$ in air feels lighter underwater by exactly the buoyant force — the principle Archimedes (legend says) used to test a crown's gold content.\n\nFor a *floating* object, equilibrium ($F_b = W$) gives a neat result: the fraction of the volume submerged equals the ratio of densities,\n\n$$\\frac{V_{\\text{submerged}}}{V_{\\text{total}}} = \\frac{\\rho_{\\text{object}}}{\\rho_{\\text{fluid}}}.$$\n\nIce ($\\rho \\approx 920\\,\\text{kg/m}^3$) floating on water sits with about $92\\%$ of its volume below the surface — the origin of \"tip of the iceberg.\"" } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Heavier objects always sink.\"** Floating depends on *density*, not weight. A giant ship far outweighs a pebble yet floats, because its average density (hull plus enclosed air) is below water's.\n\n**\"The hydraulic lift gives free energy.\"** No — the large piston moves a *shorter* distance, so force × distance (work) is conserved. You trade distance for force.\n\n**\"Buoyant force depends on the object's weight.\"** It depends on the *displaced fluid's* weight: $F_b = \\rho_{\\text{fluid}} V g$. Two objects of equal volume feel equal buoyancy, however heavy each one is." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Pascal's principle: pressure is transmitted equally; hydraulics give $F_1/A_1 = F_2/A_2$.", "Force is multiplied by the area ratio (distance is traded away — energy is conserved).", "Archimedes: buoyant force $F_b = \\rho_{\\text{fluid}} V g$ = weight of displaced fluid.", "Float if $\\rho_{\\text{object}} < \\rho_{\\text{fluid}}$; sink if greater."], formulas: [{ label: "Hydraulic press", tex: "\\dfrac{F_1}{A_1} = \\dfrac{F_2}{A_2}" }, { label: "Buoyant force", tex: "F_b = \\rho_{\\text{fluid}}\\, V\\, g" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The buoyant force on a submerged object equals the weight of:", options: ["the object", "the fluid it displaces", "the container", "the air above it"], answer: 1, difficulty: 2, explanation: "Archimedes' principle: $F_b$ equals the weight of the displaced fluid." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "In a hydraulic system the pressure is the same on both pistons.", answer: true, difficulty: 2, explanation: "Pascal's principle: the applied pressure is transmitted undiminished, so $F_1/A_1 = F_2/A_2$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "An object floats in water when its density is:", options: ["greater than water's", "less than water's", "exactly zero", "equal to its weight"], answer: 1, difficulty: 2, explanation: "If $\\rho_{\\text{object}} < \\rho_{\\text{fluid}}$, it floats." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A hydraulic press has $A_1 = 0.010\\,\\text{m}^2$ and $A_2 = 0.20\\,\\text{m}^2$. A force of $50\\,\\text{N}$ on the small piston produces what force on the large one, in newtons?", answer: { value: 1000, tolerance: 1 }, hint: "$F_2 = F_1 (A_2/A_1)$.", explanation: "$A_2/A_1 = 20$, so $F_2 = 50\\times 20 = 1000\\,\\text{N}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A fully submerged object displaces $0.0030\\,\\text{m}^3$ of water ($\\rho=1000$, $g=9.8$). Buoyant force in newtons?", answer: { value: 29.4, tolerance: 0.3 }, hint: "$F_b = \\rho V g$.", explanation: "$1000\\times 0.0030\\times 9.8 = 29.4\\,\\text{N}$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "A steel ship floats because:", options: ["steel is less dense than water", "its average density (steel plus air) is below water's", "buoyancy ignores weight", "it is painted"], answer: 1, difficulty: 3, hint: "Think about the hollow shape full of air.", explanation: "The hull encloses air, lowering the ship's average density below water's." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the buoyant force on a submerged object of volume $V$ in a fluid of density $\\rho$ under gravity $g$. (Type like `rho*V*g`.)", answer: { expr: "rho*V*g", vars: ["rho", "V", "g"] }, difficulty: 2, hint: "Weight of the displaced fluid.", explanation: "$F_b = \\rho V g$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "A hydraulic lift multiplies force without violating energy conservation, because the larger piston moves a shorter distance.", answer: true, difficulty: 3, hint: "Work = force × distance.", explanation: "Force is gained but distance is lost in proportion, so the work done is unchanged." },
    ],
  },

  // ───────────────────── 4. Fluid Flow & Continuity ─────────────────────
  {
    slug: "fluid-flow-and-continuity",
    title: "Fluid Flow & Continuity",
    tagline: "Narrow the pipe, speed the flow",
    estMinutes: 14,
    xpReward: 150,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Fluids in Motion", sub: "Pinch a garden hose and the water shoots faster. That everyday trick hides a conservation law as solid as any in physics." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Why does a river run faster through a narrow gorge? Why does pinching a hose make the jet reach farther? Why do engineers size pipes the way they do? The answer is **continuity** — the idea that, for an incompressible fluid, what flows in must flow out. It is conservation of mass, written for fluids, and it is the first half of understanding moving fluids (Bernoulli's equation is the second)." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "Consider a fluid flowing steadily through a pipe whose cross-sectional area changes. The **volume flow rate** — the volume passing any cross-section per second — is the area times the flow speed:\n\n$$Q = A\\,v$$\n\nmeasured in $\\text{m}^3/\\text{s}$.\n\nFor an **incompressible** fluid (constant density, a good model for liquids), no fluid is created or destroyed, so the flow rate must be the same at every cross-section. That is the **continuity equation**:\n\n$$A_1 v_1 = A_2 v_2$$\n\nThe immediate consequence: where the pipe is **narrow** (small $A$), the fluid must move **fast** (large $v$); where it is **wide**, it moves slowly. Speed and area are *inversely* related.\n\nRearranged, $v_2 = v_1\\,(A_1/A_2)$ — halving the area doubles the speed, quartering it quadruples the speed. This is exactly why pinching a hose to a quarter of its area makes the water leave four times faster." } },
      { kind: "CONCEPT", title: "Derivation: conservation of volume", content: { markdown: "In a short time $\\Delta t$, fluid entering the wide section sweeps through a length $v_1 \\Delta t$, filling a volume $A_1 v_1 \\Delta t$. In the same time, fluid leaving the narrow section sweeps out $A_2 v_2 \\Delta t$.\n\nIf the fluid is incompressible and none piles up, the volume in must equal the volume out:\n\n$$A_1 v_1 \\Delta t = A_2 v_2 \\Delta t.$$\n\nThe $\\Delta t$ cancels, leaving the continuity equation:\n\n$$A_1 v_1 = A_2 v_2.$$\n\nIt is simply conservation of mass (here, of volume, since density is constant) applied to a flow tube." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Narrowing pipe", problem: "Water flows at $2.0\\,\\text{m/s}$ through a pipe of area $0.10\\,\\text{m}^2$. It then enters a section of area $0.040\\,\\text{m}^2$. Find the new speed.", steps: ["Use $A_1 v_1 = A_2 v_2$, so $v_2 = v_1 (A_1/A_2)$.", "$v_2 = 2.0\\times (0.10/0.040) = 2.0\\times 2.5 = 5.0\\,\\text{m/s}$."], answer: "$v_2 = 5.0\\,\\text{m/s}$." },
        { title: "Volume flow rate", problem: "A pipe of area $0.020\\,\\text{m}^2$ carries water at $3.0\\,\\text{m/s}$. What is the volume flow rate?", steps: ["$Q = A v = 0.020\\times 3.0$.", "$Q = 0.060\\,\\text{m}^3/\\text{s}$."], answer: "$Q = 0.060\\,\\text{m}^3/\\text{s}$." },
        { title: "Pinching a hose", problem: "Water leaves a hose of area $A$ at $1.5\\,\\text{m/s}$. You cover the end so the opening is one-third the area. How fast does the water now exit?", steps: ["New area $A_2 = A/3$, so $v_2 = v_1 (A_1/A_2) = v_1\\times 3$.", "$v_2 = 1.5\\times 3 = 4.5\\,\\text{m/s}$."], answer: "$v_2 = 4.5\\,\\text{m/s}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Remember: smaller area means faster flow." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Treat the fluid as incompressible: $A_1 v_1 = A_2 v_2$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: round pipes and compressible flow", content: { markdown: "For a circular pipe of radius $r$, the area is $A = \\pi r^2$, so continuity becomes $r_1^2 v_1 = r_2^2 v_2$. Because area scales with the *square* of the radius, halving the radius quarters the area and so makes the fluid flow **four times** faster — a small change in radius has a big effect on speed.\n\nThe simple $A_1 v_1 = A_2 v_2$ assumes constant density. For gases moving fast enough that they compress noticeably (think jet engines or sound waves), density changes too, and the correct statement conserves **mass** flow: $\\rho_1 A_1 v_1 = \\rho_2 A_2 v_2$. For liquids and slow gas flows, density is constant and our simpler form holds." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A wider pipe makes the fluid flow faster.\"** The opposite: in a wider section the fluid slows down, because the same volume per second spreads over more area.\n\n**\"Speed and area are proportional.\"** They are *inversely* related — $v \\propto 1/A$. Doubling the area halves the speed.\n\n**\"Continuity needs a pump or pressure.\"** It is pure conservation of volume; it holds for any steady incompressible flow, with or without a driving pump." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Volume flow rate $Q = A v$, in $\\text{m}^3/\\text{s}$.", "Continuity (incompressible): $A_1 v_1 = A_2 v_2$.", "Speed and area are inversely related: narrow ⇒ fast, wide ⇒ slow.", "It is conservation of mass/volume applied to a flow tube."], formulas: [{ label: "Flow rate", tex: "Q = A v" }, { label: "Continuity", tex: "A_1 v_1 = A_2 v_2" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The continuity equation for an incompressible fluid is:", options: ["$A_1 v_1 = A_2 v_2$", "$A_1 / v_1 = A_2 / v_2$", "$A_1 v_2 = A_2 v_1$", "$v_1 + v_2 = A_1 + A_2$"], answer: 0, difficulty: 2, explanation: "Conservation of volume gives $A_1 v_1 = A_2 v_2$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "When an incompressible fluid enters a narrower section of pipe, it speeds up.", answer: true, difficulty: 2, explanation: "Smaller area requires larger speed to keep $A v$ constant." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "In a flowing incompressible fluid, speed and cross-sectional area are:", options: ["directly proportional", "inversely related", "unrelated", "always equal"], answer: 1, difficulty: 2, explanation: "$v \\propto 1/A$ from $A_1 v_1 = A_2 v_2$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Water moves at $2.0\\,\\text{m/s}$ in a pipe of area $0.060\\,\\text{m}^2$, then enters area $0.020\\,\\text{m}^2$. New speed in m/s?", answer: { value: 6, tolerance: 0.1 }, hint: "$v_2 = v_1 (A_1/A_2)$.", explanation: "$v_2 = 2.0\\times (0.060/0.020) = 2.0\\times 3 = 6.0\\,\\text{m/s}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A pipe of area $0.050\\,\\text{m}^2$ carries water at $4.0\\,\\text{m/s}$. Volume flow rate in $\\text{m}^3/\\text{s}$?", answer: { value: 0.2, tolerance: 0.005 }, hint: "$Q = A v$.", explanation: "$0.050\\times 4.0 = 0.20\\,\\text{m}^3/\\text{s}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Fluid flows at $5.0\\,\\text{m/s}$ through area $0.030\\,\\text{m}^2$. To keep the flow rate, what speed is needed in a section of area $0.015\\,\\text{m}^2$, in m/s?", answer: { value: 10, tolerance: 0.1 }, difficulty: 3, hint: "Halving the area doubles the speed.", explanation: "$v_2 = 5.0\\times (0.030/0.015) = 10\\,\\text{m/s}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Solve the continuity equation for $v_2$ in terms of $A_1$, $v_1$, and $A_2$. (Type like `A_1*v_1/A_2`.)", answer: { expr: "A_1*v_1/A_2", vars: ["A_1", "v_1", "A_2"] }, difficulty: 3, hint: "Divide both sides of $A_1 v_1 = A_2 v_2$ by $A_2$.", explanation: "$v_2 = A_1 v_1 / A_2$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Doubling a pipe's cross-sectional area, with the same flow rate, doubles the fluid's speed.", answer: false, difficulty: 3, hint: "Is the relationship direct or inverse?", explanation: "Speed is inversely related to area, so doubling the area halves the speed." },
    ],
  },

  // ─────────────────────── 5. Bernoulli's Equation ───────────────────────
  {
    slug: "bernoulli-equation",
    title: "Bernoulli's Equation",
    tagline: "Fast flow, low pressure — energy on the move",
    estMinutes: 18,
    xpReward: 168,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Energy in a Flow", sub: "Wings lift planes, atomisers spray perfume, and tanks drain at a predictable rate — all explained by one elegant statement of energy conservation for fluids." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "How does a wing generate lift? Why does a shower curtain billow inward? How fast does water shoot from a hole in a tank? Daniel Bernoulli's equation answers all of these by treating a flowing fluid through the lens of **energy conservation**. It ties together pressure, speed, and height — and reveals the counterintuitive rule that *faster-moving fluid has lower pressure*." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "For a steady, incompressible flow with negligible friction, the following combination is **constant** along a streamline:\n\n$$P + \\tfrac{1}{2}\\rho v^2 + \\rho g h = \\text{constant}$$\n\nThree terms, each an energy per unit volume:\n\n- $P$ — the pressure (flow/work energy density),\n- $\\tfrac{1}{2}\\rho v^2$ — the kinetic energy per unit volume,\n- $\\rho g h$ — the gravitational potential energy per unit volume.\n\nBecause the sum is fixed, the terms trade off. The headline consequence, at constant height: **where the fluid moves faster, its pressure drops.** Speed up the flow ($v$ rises, so $\\tfrac12\\rho v^2$ rises) and $P$ must fall to keep the sum constant.\n\nWritten between two points on a streamline:\n\n$$P_1 + \\tfrac{1}{2}\\rho v_1^2 + \\rho g h_1 = P_2 + \\tfrac{1}{2}\\rho v_2^2 + \\rho g h_2.$$\n\n**Applications.**\n- **Lift:** air travels faster over the curved top of a wing than beneath it, so the pressure above is lower — the net upward force is lift.\n- **Venturi meter:** a constriction speeds the flow (continuity) and so lowers its pressure; measuring that pressure drop gives the flow speed.\n- **Leaks (Torricelli):** water draining from a hole a depth $h$ below the surface exits at $v = \\sqrt{2 g h}$ — the same speed it would reach falling freely through $h$." } },
      { kind: "CONCEPT", title: "Derivation: Torricelli's speed from Bernoulli", content: { markdown: "Take a large open tank with a small hole a depth $h$ below the water surface. Apply Bernoulli between the surface (point 1) and the hole (point 2).\n\nBoth the surface and the open hole are exposed to the atmosphere, so $P_1 = P_2 = P_0$ — the pressure terms cancel. Because the tank is wide, the surface drops very slowly, so $v_1 \\approx 0$. Put the hole at $h_2 = 0$ and the surface at $h_1 = h$.\n\nBernoulli becomes:\n\n$$P_0 + 0 + \\rho g h = P_0 + \\tfrac{1}{2}\\rho v_2^2 + 0.$$\n\nCancel $P_0$ and the density $\\rho$:\n\n$$g h = \\tfrac{1}{2} v_2^2 \\;\\Rightarrow\\; v_2 = \\sqrt{2 g h}.$$\n\nThe escaping water moves exactly as fast as if it had fallen freely from the surface — **Torricelli's theorem**, a direct consequence of energy conservation." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Speed from a leak", problem: "Water leaks from a hole $5.0\\,\\text{m}$ below the surface of a large open tank. How fast does it exit? ($g = 9.8\\,\\text{m/s}^2$.)", steps: ["Use Torricelli: $v = \\sqrt{2 g h}$.", "$v = \\sqrt{2\\times 9.8\\times 5.0} = \\sqrt{98} \\approx 9.9\\,\\text{m/s}$."], answer: "$v \\approx 9.9\\,\\text{m/s}$." },
        { title: "Pressure drop in a faster section", problem: "In a horizontal pipe, water ($\\rho = 1000$) speeds up from $2.0\\,\\text{m/s}$ to $6.0\\,\\text{m/s}$. By how much does its pressure drop?", steps: ["Horizontal, so the $\\rho g h$ terms cancel: $P_1 + \\tfrac12\\rho v_1^2 = P_2 + \\tfrac12\\rho v_2^2$.", "$\\Delta P = P_1 - P_2 = \\tfrac12\\rho (v_2^2 - v_1^2)$.", "$= \\tfrac12 (1000)(6.0^2 - 2.0^2) = 500\\times (36 - 4) = 500\\times 32 = 16\\,000\\,\\text{Pa}$."], answer: "The pressure drops by $16\\,000\\,\\text{Pa}$." },
        { title: "Which term is which", problem: "In $P + \\tfrac12\\rho v^2 + \\rho g h$, identify the kinetic-energy term and what happens to $P$ as $v$ increases at fixed height.", steps: ["The kinetic-energy-per-volume term is $\\tfrac12\\rho v^2$.", "At fixed $h$, the sum is constant, so as $\\tfrac12\\rho v^2$ grows, $P$ must shrink."], answer: "Kinetic term: $\\tfrac12\\rho v^2$; $P$ falls as $v$ rises." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Faster flow ↔ lower pressure (at the same height)." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $\\rho_{\\text{water}} = 1000\\,\\text{kg/m}^3$ and $g = 9.8\\,\\text{m/s}^2$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: assumptions and where Bernoulli breaks", content: { markdown: "Bernoulli's equation is energy conservation per unit volume, but only under four assumptions: the flow is **steady** (not changing in time), **incompressible** (constant $\\rho$), **non-viscous** (no internal friction), and we follow a **single streamline**. \n\nReal fluids have viscosity, which converts flow energy into heat — so pressure drops along a long pipe even at constant speed and height, something Bernoulli alone cannot capture (that needs the viscous flow laws, like Poiseuille's). Likewise, fast gas flows compress and need the full energy equation. Bernoulli is the ideal-fluid limit — wonderfully predictive for wings, nozzles, and venturis where friction is small over the region of interest." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Faster fluid has higher pressure.\"** Exactly backwards. At a given height, faster flow means *lower* pressure — that is the heart of Bernoulli and the reason wings lift.\n\n**\"Bernoulli works for any fluid in any situation.\"** It assumes steady, incompressible, frictionless flow along a streamline. Viscosity and turbulence break it.\n\n**\"Pressure and kinetic energy are unrelated.\"** They are two terms of the same conserved sum; when one rises the other (or the height term) must fall." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Bernoulli: $P + \\tfrac12\\rho v^2 + \\rho g h$ is constant along a streamline (energy per volume).", "At constant height, faster flow ⇒ lower pressure.", "Explains wing lift, venturi meters, and tank leaks.", "Torricelli: leak speed $v = \\sqrt{2 g h}$.", "Valid for steady, incompressible, frictionless flow."], formulas: [{ label: "Bernoulli's equation", tex: "P + \\tfrac{1}{2}\\rho v^2 + \\rho g h = \\text{const}" }, { label: "Torricelli leak speed", tex: "v = \\sqrt{2 g h}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "In Bernoulli's equation, the term $\\tfrac12\\rho v^2$ represents the:", options: ["pressure", "kinetic energy per unit volume", "potential energy per unit volume", "density"], answer: 1, difficulty: 2, explanation: "$\\tfrac12\\rho v^2$ is the kinetic energy per unit volume of the flowing fluid." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "At the same height, a faster-moving fluid has lower pressure.", answer: true, difficulty: 2, explanation: "Bernoulli's sum is constant, so a larger $\\tfrac12\\rho v^2$ forces a smaller $P$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "An aeroplane wing generates lift mainly because air over the top moves:", options: ["slower, raising pressure above", "faster, lowering pressure above", "at the same speed everywhere", "only downward"], answer: 1, difficulty: 3, explanation: "Faster flow over the top means lower pressure there, so the net force is upward." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Water leaks from a hole $2.0\\,\\text{m}$ below the surface of a large tank ($g=9.8$). Exit speed in m/s?", answer: { value: 6.26, tolerance: 0.1 }, hint: "$v = \\sqrt{2 g h}$.", explanation: "$v = \\sqrt{2\\times 9.8\\times 2.0} = \\sqrt{39.2} \\approx 6.26\\,\\text{m/s}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Torricelli: a hole $4.9\\,\\text{m}$ below the surface ($g=9.8$). Exit speed in m/s?", answer: { value: 9.8, tolerance: 0.1 }, difficulty: 3, hint: "$v = \\sqrt{2 g h}$.", explanation: "$v = \\sqrt{2\\times 9.8\\times 4.9} = \\sqrt{96.04} \\approx 9.8\\,\\text{m/s}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "In a horizontal pipe, water ($\\rho=1000$) goes from $1.0\\,\\text{m/s}$ to $3.0\\,\\text{m/s}$. Pressure drop in pascals? ($\\Delta P = \\tfrac12\\rho(v_2^2 - v_1^2)$.)", answer: { value: 4000, tolerance: 10 }, difficulty: 3, hint: "$\\tfrac12(1000)(9 - 1)$.", explanation: "$\\tfrac12(1000)(3.0^2 - 1.0^2) = 500\\times 8 = 4000\\,\\text{Pa}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write Torricelli's leak speed for a hole at depth $h$ (use $g$ for gravity). (Type like `sqrt(2*g*h)`.)", answer: { expr: "sqrt(2*g*h)", vars: ["g", "h"] }, difficulty: 3, hint: "It matches free-fall through height $h$.", explanation: "$v = \\sqrt{2 g h}$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Bernoulli's equation assumes the flow is frictionless (non-viscous).", answer: true, difficulty: 3, hint: "What does viscosity do to flow energy?", explanation: "Bernoulli neglects viscosity; real viscous flows lose energy to friction, so the simple form no longer holds." },
    ],
  },
];
