import type { LessonSeed } from "../types.js";

/**
 * The Sun (grades 11–12 / intro university): Circular Motion & Gravitation —
 * the force that holds the solar system together. Uniform circular motion and
 * centripetal acceleration, centripetal force and banked curves, Newton's law
 * of universal gravitation, orbital motion, and Kepler's three laws. Uses the
 * locally graded NUMERIC / SYMBOLIC / GRAPH / PROOF types. All original content.
 */
export const gravitationLessons: LessonSeed[] = [
  // ───────────────────────── 1. Uniform Circular Motion ─────────────────────────
  {
    slug: "uniform-circular-motion",
    title: "Uniform Circular Motion",
    tagline: "Turning is accelerating",
    estMinutes: 15,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Always Falling Inward", sub: "An object moving in a circle at steady speed is still accelerating — because its direction never stops changing." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Earth races around the Sun at about $30\\,\\text{km/s}$, yet it neither speeds up nor flies away. Its **speed** is constant but its **velocity** is not — velocity is a vector, and its direction turns continuously.\n\nThe same idea governs a car on a roundabout, a stone on a string, a spinning hard-drive platter, and a satellite overhead. A changing velocity means acceleration, and acceleration needs a force. Understanding the acceleration of circular motion is the first step toward understanding every orbit." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "In **uniform circular motion** an object travels a circle of radius $r$ at constant speed $v$. \"Uniform\" means the *speed* is fixed; the *direction* of the velocity is not.\n\n**Period and frequency.** The time for one full loop is the **period** $T$ (seconds). Its reciprocal is the **frequency** $f$ (loops per second, hertz):\n\n$$f = \\frac{1}{T}.$$\n\n**Speed.** In one period the object covers the circumference $2\\pi r$, so\n\n$$v = \\frac{2\\pi r}{T} = 2\\pi r f.$$\n\nUnits: $r$ in metres, $T$ in seconds, $v$ in $\\text{m/s}$.\n\n**Centripetal acceleration.** The velocity is always **tangent** to the circle, so its direction changes constantly — that is an acceleration even though the speed is fixed. This *center-seeking* (centripetal) acceleration points toward the center of the circle and has magnitude\n\n$$a_c = \\frac{v^2}{r}.$$\n\nUnits: $\\text{m/s}^2$. Doubling the speed quadruples $a_c$; doubling the radius (at the same speed) halves it." } },
      { kind: "CONCEPT", title: "Derivation: why $a_c = v^2/r$", content: { markdown: "Over a tiny time $\\Delta t$ the object moves a small arc and its velocity vector turns by a small angle $\\Delta\\theta$, keeping the same length $v$. The velocity triangle (the two velocity vectors and their difference $\\Delta\\vec v$) is **similar** to the position triangle (the two radii and the chord), because both are isosceles with the same apex angle $\\Delta\\theta$.\n\nMatching the ratios of corresponding sides:\n\n$$\\frac{|\\Delta\\vec v|}{v} = \\frac{|\\Delta\\vec r|}{r}.$$\n\nFor a small angle the chord length is $|\\Delta\\vec r| \\approx v\\,\\Delta t$. Substitute and solve for the ratio that is the acceleration:\n\n$$|\\Delta\\vec v| = \\frac{v}{r}\\,(v\\,\\Delta t) \\;\\Rightarrow\\; a_c = \\frac{|\\Delta\\vec v|}{\\Delta t} = \\frac{v^2}{r}.$$\n\nAnd because $\\Delta\\vec v$ points toward the center, so does the acceleration. Taking $\\Delta t \\to 0$ makes this exact — the same limiting argument that defines a derivative." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Centripetal acceleration", problem: "A car rounds a circle of radius $20\\,\\text{m}$ at $10\\,\\text{m/s}$. Find $a_c$.", steps: ["Use $a_c = v^2/r$.", "$a_c = 10^2 / 20 = 100/20$."], answer: "$a_c = 5\\,\\text{m/s}^2$ toward the center." },
        { title: "Speed from the period", problem: "A point at radius $r = 2\\,\\text{m}$ completes a loop in $T = \\pi\\,\\text{s}$. Find $v$.", steps: ["$v = 2\\pi r / T$.", "$v = 2\\pi(2)/\\pi = 4$."], answer: "$v = 4\\,\\text{m/s}$." },
        { title: "Frequency to acceleration", problem: "A stone on a $0.5\\,\\text{m}$ string is whirled at $f = 2\\,\\text{Hz}$. Find $v$ and $a_c$.", steps: ["$v = 2\\pi r f = 2\\pi(0.5)(2) = 2\\pi \\approx 6.28\\,\\text{m/s}$.", "$a_c = v^2/r = (2\\pi)^2 / 0.5 \\approx 39.5/0.5$."], answer: "$v \\approx 6.28\\,\\text{m/s}$, $a_c \\approx 79\\,\\text{m/s}^2$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Direction changes, so there is acceleration." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $v = 2\\pi r/T$ and $a_c = v^2/r$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: angular velocity", content: { markdown: "It is often tidier to describe circular motion by the **angular velocity** $\\omega$ — the rate the radius sweeps angle, in radians per second:\n\n$$\\omega = \\frac{2\\pi}{T} = 2\\pi f.$$\n\nThen the tangential speed is simply $v = \\omega r$, and the centripetal acceleration can be written three equivalent ways:\n\n$$a_c = \\frac{v^2}{r} = \\omega^2 r = \\omega v.$$\n\nThe $\\omega^2 r$ form makes a point clear: on a rigid spinning disk every point shares the same $\\omega$, so the outer points (larger $r$) feel a *larger* acceleration — which is why the rim of a grinding wheel is where things fly off first." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Constant speed means no acceleration.\"** Acceleration is the rate of change of *velocity*, a vector. Changing direction at constant speed is still accelerating.\n\n**\"The acceleration points forward along the motion.\"** In *uniform* circular motion it points straight inward, perpendicular to the velocity — there is no forward (tangential) component because the speed is unchanging.\n\n**\"A bigger circle always means a bigger acceleration.\"** At fixed speed, $a_c = v^2/r$ *decreases* as $r$ grows. A tight turn (small $r$) is the demanding one." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Constant speed in a circle still means changing velocity → acceleration.", "Period $T$ and frequency $f = 1/T$ time one loop.", "Speed around the circle: $v = 2\\pi r/T = 2\\pi r f$.", "Centripetal acceleration $a_c = v^2/r$ points to the center.", "At fixed speed, a tighter (smaller-$r$) turn needs more acceleration."], formulas: [{ label: "Speed in a circle", tex: "v = \\dfrac{2\\pi r}{T}" }, { label: "Centripetal acceleration", tex: "a_c = \\dfrac{v^2}{r}" }, { label: "Frequency", tex: "f = \\dfrac{1}{T}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "An object moving in a circle at constant speed is accelerating.", answer: true, difficulty: 1, explanation: "Its direction (hence velocity) changes, so it accelerates even at constant speed." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The centripetal acceleration points:", options: ["tangent to the circle", "toward the center", "away from the center", "straight down"], answer: 1, difficulty: 2, explanation: "Centripetal means center-seeking — it points inward." },
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "Find $a_c$ for $v = 10\\,\\text{m/s}$ and $r = 20\\,\\text{m}$ (in $\\text{m/s}^2$).", answer: { value: 5, tolerance: 0 }, difficulty: 2, explanation: "$a_c = 10^2/20 = 5\\,\\text{m/s}^2$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write centripetal acceleration $a_c$ in terms of speed $v$ and radius $r$. (Type like `v^2/r`.)", answer: { expr: "v^2/r", vars: ["v", "r"] }, difficulty: 3, hint: "Speed squared over radius.", explanation: "$a_c = \\dfrac{v^2}{r}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A point at radius $2\\,\\text{m}$ completes a loop every $\\pi\\,\\text{s}$. Find its speed in m/s ($v = 2\\pi r/T$).", answer: { value: 4, tolerance: 0 }, difficulty: 3, hint: "$v = 2\\pi(2)/\\pi$.", explanation: "$v = 4\\pi/\\pi = 4\\,\\text{m/s}$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "If the speed doubles at the same radius, the centripetal acceleration becomes:", options: ["doubled", "halved", "four times larger", "unchanged"], answer: 2, difficulty: 3, hint: "$a_c \\propto v^2$.", explanation: "Acceleration scales with $v^2$, so it quadruples." },
      { scope: "PRACTICE", kind: "GRAPH", prompt: "At fixed radius $r = 1\\,\\text{m}$, centripetal acceleration as a function of speed is $a = v^2$. Graph it (enter $a$ as a function of $v$, use $x$ for $v$).", answer: { expr: "x^2", domain: [0, 5], variable: "x" }, difficulty: 4, hint: "At $r=1$, $a_c = v^2$.", explanation: "$a = v^2$ — a parabola: doubling the speed quadruples the acceleration." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A turntable spins with period $T = 0.5\\,\\text{s}$. What is its frequency in Hz?", answer: { value: 2, tolerance: 0 }, difficulty: 2, hint: "$f = 1/T$.", explanation: "$f = 1/0.5 = 2\\,\\text{Hz}$." },
    ],
  },

  // ───────────────────── 2. Centripetal Force & Banked Curves ─────────────────────
  {
    slug: "centripetal-force-banked-curves",
    title: "Centripetal Force & Banked Curves",
    tagline: "What actually pushes you around the bend",
    estMinutes: 16,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "The Force That Turns You", sub: "Centripetal force is never new — it is whatever real force happens to point toward the center: tension, friction, gravity, or the lean of a banked road." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Why does a car skid out of a sharp turn taken too fast? Why are highway off-ramps and racetracks tilted inward? Why do you feel pressed against the door as the car corners?\n\nAll of these are about the **centripetal force** — the inward force that any circular motion demands. Once you can name *which* real force is doing the job, you can predict the maximum safe speed of a turn, design a banked curve, and explain that \"pressed against the door\" feeling correctly." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "By Newton's second law, the centripetal acceleration $a_c = v^2/r$ requires a net inward force, the **centripetal force**:\n\n$$F_c = m a_c = \\frac{m v^2}{r}.$$\n\nUnits: $m$ in kg, $v$ in $\\text{m/s}$, $r$ in m, $F_c$ in newtons.\n\n**Centripetal force is not a new force.** It is the *net* of the ordinary forces, resolved toward the center. Depending on the situation, the job is done by:\n\n- **Tension** — a ball whirled on a string; the string pulls inward.\n- **Friction** — a car turning on a flat road; static friction between tires and road points toward the center.\n- **Gravity** — the Moon orbiting Earth; gravity is the inward pull.\n- **The normal force** — a banked curve or a loop-the-loop, where a tilted surface pushes partly inward.\n\n**Flat curve (friction only).** On a level road the maximum static friction $f_\\text{max} = \\mu_s m g$ must supply the centripetal force. Setting $\\mu_s m g = m v^2/r$ gives the fastest safe speed:\n\n$$v_\\text{max} = \\sqrt{\\mu_s g r}.$$\n\nNotice the mass cancels — a heavy truck and a light car skid at the same speed on the same curve.\n\n**Banked curve (no friction needed).** If the road is tilted at angle $\\theta$, the normal force gains an inward horizontal component. At exactly the right speed, that component alone supplies $F_c$ with no friction at all:\n\n$$\\tan\\theta = \\frac{v^2}{g r}.$$\n\nThis is the *design speed* of the curve — the bank is built for one ideal speed." } },
      { kind: "CONCEPT", title: "Derivation: the ideal banking angle", content: { markdown: "On a frictionless banked road, only two forces act on the car: gravity $mg$ straight down and the normal force $N$ perpendicular to the road surface. With the road tilted at angle $\\theta$, resolve $N$ into components.\n\n**Vertical** (no vertical acceleration — the car stays on the road):\n\n$$N\\cos\\theta = mg.$$\n\n**Horizontal** (the inward component supplies the centripetal force):\n\n$$N\\sin\\theta = \\frac{m v^2}{r}.$$\n\nDivide the second equation by the first. Both $N$ and $m$ cancel:\n\n$$\\frac{N\\sin\\theta}{N\\cos\\theta} = \\frac{m v^2 / r}{m g} \\;\\Rightarrow\\; \\tan\\theta = \\frac{v^2}{g r}.$$\n\nThe angle depends only on the design speed $v$, the radius $r$, and $g$ — never the car's mass." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Tension as centripetal force", problem: "A $0.5\\,\\text{kg}$ ball on a string is whirled in a horizontal circle of radius $1.0\\,\\text{m}$ at $4\\,\\text{m/s}$. Find the string tension (the centripetal force).", steps: ["The only inward force is tension, so $T = F_c = mv^2/r$.", "$T = 0.5 \\times 4^2 / 1.0 = 0.5 \\times 16$."], answer: "$T = 8\\,\\text{N}$." },
        { title: "Fastest safe speed on a flat curve", problem: "A car corners on a flat road of radius $50\\,\\text{m}$ with $\\mu_s = 0.8$. Take $g = 10\\,\\text{m/s}^2$. Find the maximum speed.", steps: ["Friction supplies $F_c$: $v_\\text{max} = \\sqrt{\\mu_s g r}$.", "$v_\\text{max} = \\sqrt{0.8 \\times 10 \\times 50} = \\sqrt{400}$."], answer: "$v_\\text{max} = 20\\,\\text{m/s}$." },
        { title: "Banking angle", problem: "A curve of radius $80\\,\\text{m}$ is to be banked for a design speed of $20\\,\\text{m/s}$. Take $g = 10\\,\\text{m/s}^2$. Find $\\tan\\theta$.", steps: ["Use $\\tan\\theta = v^2/(g r)$.", "$\\tan\\theta = 20^2 / (10 \\times 80) = 400/800$."], answer: "$\\tan\\theta = 0.5$ (about $27^\\circ$)." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Name the force that points toward the center." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $F_c = mv^2/r$, $v_\\text{max} = \\sqrt{\\mu_s g r}$, and $\\tan\\theta = v^2/(g r)$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: the centrifugal \"force\"", content: { markdown: "When a car corners, you feel flung *outward* against the door — so why do we insist the net force is *inward*? Because there is no real outward force. Your body, obeying inertia, wants to continue in a straight line; the door has to push you inward to make you turn with the car. The outward feeling is your inertia resisting that inward push.\n\nIn a rotating reference frame (one that turns with the car) it can be *convenient* to invent an outward **centrifugal force** to balance the books — but it is a *fictitious* force, an artifact of the accelerating frame, not a push from any object. In the inertial (ground) frame it simply does not exist, and the only forces are the real inward ones." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"There is an outward centrifugal force throwing you out of the turn.\"** In the ground frame the net force is inward; the outward feeling is inertia, not a real force.\n\n**\"Centripetal force is an extra force you add to the diagram.\"** It is not separate — it *is* the net inward component of the real forces (tension, friction, gravity, normal force). Drawing it as a fifth arrow double-counts.\n\n**\"A banked curve works at any speed.\"** A frictionless bank is designed for exactly one speed; too slow and you slide down the bank, too fast and you slide up it. Real friction gives a range around the design speed." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Centripetal force $F_c = mv^2/r$ is the net inward force, not a new force.", "On a flat curve, friction provides it: $v_\\text{max} = \\sqrt{\\mu_s g r}$ (mass cancels).", "On a banked curve, the normal force's inward component can supply it: $\\tan\\theta = v^2/(gr)$.", "Sources of centripetal force: tension, friction, gravity, normal force.", "There is no real outward centrifugal force in the inertial frame."], formulas: [{ label: "Centripetal force", tex: "F_c = \\dfrac{m v^2}{r}" }, { label: "Flat-curve max speed", tex: "v_\\text{max} = \\sqrt{\\mu_s g r}" }, { label: "Ideal banking angle", tex: "\\tan\\theta = \\dfrac{v^2}{g r}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "For a ball whirled on a string in a horizontal circle, the centripetal force is provided by:", options: ["friction", "the string's tension", "gravity", "the normal force"], answer: 1, difficulty: 2, explanation: "The string pulls the ball inward — its tension is the centripetal force." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Centripetal force is a brand-new kind of force, separate from gravity, friction, and tension.", answer: false, difficulty: 2, explanation: "It is just the net inward component of the ordinary forces, not a new force." },
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "A $2\\,\\text{kg}$ mass moves at $4\\,\\text{m/s}$ on a radius of $2\\,\\text{m}$. Find the centripetal force in newtons.", answer: { value: 16, tolerance: 0 }, difficulty: 2, explanation: "$F_c = mv^2/r = 2 \\times 16 / 2 = 16\\,\\text{N}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the centripetal force $F_c$ in terms of mass $m$, speed $v$, and radius $r$. (Type like `m*v^2/r`.)", answer: { expr: "m*v^2/r", vars: ["m", "v", "r"] }, difficulty: 3, hint: "Mass times centripetal acceleration.", explanation: "$F_c = m a_c = \\dfrac{m v^2}{r}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A car corners on a flat road of radius $50\\,\\text{m}$ with $\\mu_s = 0.8$. Using $g = 10\\,\\text{m/s}^2$, find the maximum speed in m/s.", answer: { value: 20, tolerance: 0 }, difficulty: 3, hint: "$v_\\text{max} = \\sqrt{\\mu_s g r}$.", explanation: "$v_\\text{max} = \\sqrt{0.8 \\times 10 \\times 50} = \\sqrt{400} = 20\\,\\text{m/s}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A curve of radius $80\\,\\text{m}$ is banked for a design speed of $20\\,\\text{m/s}$. Using $g = 10\\,\\text{m/s}^2$, find $\\tan\\theta$.", answer: { value: 0.5, tolerance: 0.01 }, difficulty: 4, hint: "$\\tan\\theta = v^2/(g r)$.", explanation: "$\\tan\\theta = 400/(10\\times 80) = 0.5$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "On a flat curve, the maximum safe speed $v_\\text{max} = \\sqrt{\\mu_s g r}$ for a heavy truck compared with a light car (same tires, same curve) is:", options: ["larger for the truck", "smaller for the truck", "the same — mass cancels", "zero for the truck"], answer: 2, difficulty: 3, hint: "Does $m$ appear in the formula?", explanation: "Mass cancels: both can take the curve at the same maximum speed." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "When a car corners, the feeling of being pushed outward against the door is caused by a real outward force acting on you.", answer: false, difficulty: 3, hint: "What is the only real horizontal force the door exerts?", explanation: "It is your inertia resisting the inward push of the door; the net real force is inward, not outward." },
    ],
  },

  // ───────────────────────── 3. Universal Gravitation ─────────────────────────
  {
    slug: "universal-gravitation",
    title: "Newton's Law of Universal Gravitation",
    tagline: "Every mass pulls every other",
    estMinutes: 15,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "The Same Force, Everywhere", sub: "The pull that drops an apple is the very same pull that bends the Moon's path. Newton's great unification." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Newton's insight was audacious: the force pulling an apple to the ground is the *same* force holding the Moon in orbit, just weaker with distance. Every pair of masses in the universe attracts, by one law, with no exceptions yet found.\n\nThat single equation explains the tides, the orbits of planets and satellites, the value of $g$ on every world, and the slow assembly of stars and galaxies. It is one of the most far-reaching laws in all of science." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Newton's law of universal gravitation:** every two point masses attract along the line joining them with a force\n\n$$F = G\\,\\frac{m_1 m_2}{r^2},$$\n\nwhere $m_1, m_2$ are the masses (kg), $r$ is the distance between their centers (m), and\n\n$$G = 6.67\\times10^{-11}\\ \\text{N·m}^2/\\text{kg}^2$$\n\nis the **universal gravitational constant**. The force $F$ comes out in newtons.\n\nKey features:\n\n- **Mutual and equal.** The two bodies pull on each other with equal and opposite forces (Newton's third law): the Earth pulls you down exactly as hard as you pull it up.\n- **Inverse-square law.** $F \\propto 1/r^2$: triple the distance and the force drops to $\\tfrac{1}{9}$. The distance is measured *between centers*, not between surfaces.\n- **Always attractive.** Gravity only pulls; there is no gravitational repulsion.\n\n**Surface gravity.** For an object of mass $m$ near a planet of mass $M$ and radius $R$, the force is $F = GMm/R^2$. We also write this as $F = mg$, so the **surface gravitational acceleration** is\n\n$$g = \\frac{GM}{R^2}.$$\n\nFor Earth ($M_\\oplus \\approx 5.97\\times10^{24}\\,\\text{kg}$, $R_\\oplus \\approx 6.37\\times10^6\\,\\text{m}$) this gives $g \\approx 9.8\\,\\text{m/s}^2$ — and notice the falling object's own mass has cancelled out." } },
      { kind: "CONCEPT", title: "Derivation: surface gravity is independent of mass", content: { markdown: "Apply the universal law to a small object of mass $m$ sitting on a planet of mass $M$ and radius $R$. The gravitational force on it is\n\n$$F = G\\frac{M m}{R^2}.$$\n\nBy Newton's second law, its free-fall acceleration is the force divided by its own mass:\n\n$$a = \\frac{F}{m} = \\frac{G M m}{R^2 m}.$$\n\nThe object's mass $m$ cancels top and bottom:\n\n$$a = \\frac{G M}{R^2} = g.$$\n\nBecause $m$ has disappeared, *every* object — feather or boulder — falls with the same acceleration $g$ at a given planet's surface. This is exactly Galileo's observation, now explained by Newton's law." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Inverse-square scaling", problem: "If the distance between two masses triples, what happens to the gravitational force?", steps: ["$F \\propto 1/r^2$.", "Replace $r$ with $3r$: factor $1/3^2 = 1/9$."], answer: "The force becomes one-ninth as strong." },
        { title: "Surface gravity of a planet", problem: "A planet has the same radius as Earth but twice Earth's mass. How does its surface gravity compare?", steps: ["$g = GM/R^2$.", "Same $R$, mass $\\to 2M$: $g \\to 2 \\times 9.8$."], answer: "Surface gravity is doubled, about $19.6\\,\\text{m/s}^2$." },
        { title: "Force between two masses", problem: "Estimate the gravitational force between two $1000\\,\\text{kg}$ cars whose centers are $10\\,\\text{m}$ apart. ($G = 6.67\\times10^{-11}$.)", steps: ["$F = G m_1 m_2 / r^2$.", "$F = 6.67\\times10^{-11} \\times (1000)(1000) / 10^2 = 6.67\\times10^{-11}\\times 10^6/100$."], answer: "$F \\approx 6.7\\times10^{-7}\\,\\text{N}$ — tiny, which is why everyday gravity between objects is unnoticeable." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Mutual, attractive, inverse-square." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Mind the inverse-square dependence on distance." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: the gravitational field", content: { markdown: "We often split gravity into two ideas: a mass $M$ creates a **field** $g = GM/r^2$ in the space around it, and a second mass $m$ placed there feels $F = mg$. The field exists whether or not a test mass is present — it is a property of space sculpted by mass.\n\nThis field picture is the bridge to Einstein's general relativity, where mass curves spacetime itself and 'gravity' is objects following the straightest possible paths through that curvature. Newton's inverse-square law re-emerges as the weak-field, low-speed limit of that deeper theory — which is why it still flies our spacecraft with exquisite accuracy." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Heavier objects fall faster.\"** Surface gravity $g = GM/R^2$ does not contain the falling object's mass, so all objects fall at the same rate (ignoring air).\n\n**\"There's no gravity in space, because astronauts float.\"** Gravity is everywhere and falls off only gradually; at the ISS it is still about $90\\%$ of its surface value. Astronauts float because they are in continuous free fall, not because gravity is absent.\n\n**\"Doubling the distance halves the force.\"** It is an *inverse-square* law: doubling $r$ quarters the force, not halves it." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Gravity acts between every pair of masses: $F = Gm_1m_2/r^2$.", "It is attractive, mutual, and equal on both bodies (Newton's third law).", "It follows an inverse-square law in the center-to-center distance.", "$G = 6.67\\times10^{-11}\\ \\text{N·m}^2/\\text{kg}^2$ is the same everywhere.", "Surface gravity $g = GM/R^2$ is the same for all falling masses."], formulas: [{ label: "Universal gravitation", tex: "F = G\\dfrac{m_1 m_2}{r^2}" }, { label: "Surface gravity", tex: "g = \\dfrac{GM}{R^2}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Gravitational force between two masses depends on distance as:", options: ["$\\propto r$", "$\\propto 1/r$", "$\\propto 1/r^2$", "independent of $r$"], answer: 2, difficulty: 2, explanation: "It is an inverse-square law: $F \\propto 1/r^2$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Earth pulls on you with the same magnitude of force that you pull on Earth.", answer: true, difficulty: 2, explanation: "Newton's third law — the gravitational forces are an equal, opposite pair." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "If the distance between two masses triples, the force becomes:", options: ["3× larger", "9× larger", "1/3 as strong", "1/9 as strong"], answer: 3, difficulty: 2, explanation: "$1/3^2 = 1/9$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "With $k = Gm_1m_2$ held constant, write the gravitational force $F$ as a function of distance $r$. (Type like `k/r^2`.)", answer: { expr: "k/r^2", vars: ["k", "r"] }, difficulty: 3, hint: "Inverse square of $r$.", explanation: "$F = \\dfrac{k}{r^2}$ where $k = Gm_1m_2$." },
      { scope: "PRACTICE", kind: "GRAPH", prompt: "Taking $Gm_1m_2 = 1$, gravitational force versus distance is $F = 1/r^2$. Graph it (enter $F$ as a function of $r$, use $x$ for $r$).", answer: { expr: "1/x^2", domain: [0.5, 4], variable: "x" }, difficulty: 4, hint: "Inverse-square curve.", explanation: "$F = 1/r^2$ — a steep curve that falls off quickly with distance." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write a planet's surface gravity $g$ in terms of $G$, its mass $M$, and its radius $R$. (Type like `G*M/R^2`.)", answer: { expr: "G*M/R^2", vars: ["G", "M", "R"] }, difficulty: 3, hint: "Force per unit mass at the surface.", explanation: "$g = \\dfrac{GM}{R^2}$ — the falling mass cancels." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "A planet has Earth's radius but twice Earth's mass. Its surface gravity is about:", options: ["$4.9\\,\\text{m/s}^2$", "$9.8\\,\\text{m/s}^2$", "$19.6\\,\\text{m/s}^2$", "$39.2\\,\\text{m/s}^2$"], answer: 2, difficulty: 3, hint: "$g = GM/R^2$, with $M$ doubled.", explanation: "Doubling $M$ at the same $R$ doubles $g$ to about $19.6\\,\\text{m/s}^2$." },
      { scope: "PRACTICE", kind: "PROOF", prompt: "Arrange the argument that free-fall acceleration is independent of the falling mass.", options: ["Gravity on a mass $m$ near a planet is $F = GMm/R^2$.", "By Newton's second law, $a = F/m$.", "Substitute: $a = GMm/(R^2 m)$.", "The $m$ cancels: $a = GM/R^2 = g$."], answer: [], difficulty: 4, hint: "Start from the force, divide by $m$.", explanation: "Dividing the gravitational force by the mass cancels $m$, leaving $g = GM/R^2$." },
    ],
  },

  // ───────────────────────────── 4. Orbital Motion ─────────────────────────────
  {
    slug: "orbits-and-kepler",
    title: "Orbital Motion",
    tagline: "Falling forever, missing the ground",
    estMinutes: 16,
    xpReward: 170,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Falling Forever", sub: "An orbit is just continuous falling — moving sideways fast enough that you keep missing the ground." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Newton imagined a cannon firing horizontally ever faster. Slow shots fall to Earth; fast enough, and the ground curves away as quickly as the ball falls — it never lands. That is an **orbit**.\n\nEvery GPS satellite, every weather satellite, the Moon, and the entire planetary family obey this one idea: the same gravity that drops an apple, supplying exactly the centripetal force a curved path needs. Get this and you can compute how fast a satellite must go and why astronauts appear weightless." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "For a circular orbit, **gravity is the centripetal force**. Nothing else pulls the satellite inward, so the gravitational force must equal exactly the centripetal requirement. For a small mass $m$ orbiting a large mass $M$ at radius $r$:\n\n$$\\frac{GMm}{r^2} = \\frac{m v^2}{r}.$$\n\nSolving for the **orbital speed**:\n\n$$v = \\sqrt{\\frac{GM}{r}}.$$\n\nUnits: $G$ in $\\text{N·m}^2/\\text{kg}^2$, $M$ in kg, $r$ in m, $v$ in $\\text{m/s}$. Two consequences:\n\n- The orbiting mass $m$ **cancels** — orbital speed depends only on *what* you orbit ($M$) and *how far out* ($r$), not on the satellite's own mass.\n- **Farther orbits are slower**: $v \\propto 1/\\sqrt{r}$. A low satellite must race; the distant Moon ambles.\n\n**Weightlessness.** Astronauts on the ISS are *not* beyond gravity — gravity there is nearly as strong as on the ground. They float because the station and everyone in it are in continuous **free fall**, all accelerating inward at the same rate. With nothing pushing up against them, there is no normal force — and the absence of that normal force is exactly the sensation we call weightlessness. The same thing happens, briefly, at the top of a roller-coaster drop or in a falling elevator." } },
      { kind: "CONCEPT", title: "Derivation: circular orbital speed", content: { markdown: "Begin with the physical statement that gravity provides the centripetal force:\n\n$$\\frac{GMm}{r^2} = \\frac{m v^2}{r}.$$\n\nThe satellite's mass $m$ appears on both sides, so cancel it:\n\n$$\\frac{GM}{r^2} = \\frac{v^2}{r}.$$\n\nMultiply both sides by $r$ to clear one power of $r$ on the right:\n\n$$\\frac{GM}{r} = v^2.$$\n\nTake the square root:\n\n$$v = \\sqrt{\\frac{GM}{r}}.$$\n\nThe whole result rests on a single idea — that for a circle, gravity *is* the centripetal force — and a little algebra." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Why mass drops out", problem: "Why doesn't a satellite's orbital speed depend on its own mass?", steps: ["Set $GMm/r^2 = mv^2/r$.", "The satellite mass $m$ appears on both sides and cancels.", "$v = \\sqrt{GM/r}$ — only $M$ and $r$ remain."], answer: "Orbital speed depends only on the central mass $M$ and the radius $r$." },
        { title: "Comparing two orbits", problem: "Satellite B orbits 4× farther from Earth than satellite A. How do their orbital speeds compare? (Use $v \\propto 1/\\sqrt r$.)", steps: ["$v \\propto r^{-1/2}$.", "Radius $\\times 4 \\Rightarrow$ speed $\\times 1/\\sqrt 4 = 1/2$."], answer: "B moves at half the speed of A — farther is slower." },
        { title: "Weightlessness", problem: "Is an astronaut on the ISS weightless because there is no gravity there?", steps: ["At the ISS gravity is about $90\\%$ of its surface value — far from zero.", "The station and astronaut are both in free fall, accelerating inward together.", "With no surface pushing up, there is no normal force."], answer: "No — they are in free fall; the missing normal force, not missing gravity, makes them feel weightless." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Gravity supplies the centripetal force." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $v = \\sqrt{GM/r}$; remember $v \\propto 1/\\sqrt r$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: escape speed", content: { markdown: "Orbital speed keeps you going around; **escape speed** is the launch speed needed to leave a planet entirely and never fall back. Setting the kinetic energy equal to the depth of the gravitational potential well gives\n\n$$v_\\text{esc} = \\sqrt{\\frac{2GM}{R}} = \\sqrt{2}\\,v_\\text{orbit}.$$\n\nEscape speed is just $\\sqrt 2 \\approx 1.41$ times the low-orbit speed — for Earth, about $11.2\\,\\text{km/s}$. Notice the launching object's mass cancels here too, and that a more massive or more compact body (larger $M$, smaller $R$) is harder to escape. Push $R$ small enough that $v_\\text{esc}$ would exceed the speed of light and you have crossed into the territory of a **black hole**." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Astronauts float because there's no gravity in space.\"** Gravity at the ISS is roughly $90\\%$ of its surface value. They float because they are in free fall, not because gravity is gone.\n\n**\"A heavier satellite must orbit faster at the same height.\"** Orbital speed $v = \\sqrt{GM/r}$ has no $m$ in it — all satellites at a given radius move at the same speed.\n\n**\"Faster always means a higher orbit.\"** It is the reverse: higher orbits are *slower*, since $v \\propto 1/\\sqrt r$." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["An orbit is free fall with enough sideways speed to keep missing the ground.", "Gravity provides the centripetal force: equate $GMm/r^2 = mv^2/r$.", "Orbital speed $v = \\sqrt{GM/r}$ is independent of the orbiting mass.", "Farther orbits are slower: $v \\propto 1/\\sqrt r$.", "Weightlessness is free fall (no normal force), not the absence of gravity."], formulas: [{ label: "Orbital speed", tex: "v = \\sqrt{\\dfrac{GM}{r}}" }, { label: "Escape speed", tex: "v_\\text{esc} = \\sqrt{\\dfrac{2GM}{R}}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "In a circular orbit, the centripetal force is provided by:", options: ["air resistance", "gravity", "the engine", "magnetism"], answer: 1, difficulty: 2, explanation: "Gravity supplies exactly the inward force the circular path needs." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "A more massive satellite must orbit faster at the same radius.", answer: false, difficulty: 2, explanation: "Orbital speed $v = \\sqrt{GM/r}$ is independent of the satellite's mass." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Astronauts on the space station feel weightless because there is essentially no gravity at that altitude.", answer: false, difficulty: 3, explanation: "Gravity there is about 90% of its surface value; they feel weightless because they are in free fall (no normal force)." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the circular orbital speed $v$ in terms of $G$, the central mass $M$, and the orbit radius $r$. (Type like `sqrt(G*M/r)`.)", answer: { expr: "sqrt(G*M/r)", vars: ["G", "M", "r"] }, difficulty: 4, hint: "Square root of $GM$ over $r$.", explanation: "$v = \\sqrt{\\dfrac{GM}{r}}$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "Satellite B orbits 4 times farther out than satellite A. Using $v \\propto 1/\\sqrt r$, B's orbital speed is:", options: ["4× A's", "2× A's", "half of A's", "one-quarter of A's"], answer: 2, difficulty: 3, hint: "$1/\\sqrt 4 = 1/2$.", explanation: "Four times the radius gives $1/\\sqrt 4 = 1/2$ the speed." },
      { scope: "PRACTICE", kind: "GRAPH", prompt: "With $GM = 1$, orbital speed versus radius is $v = 1/\\sqrt{r}$. Graph it (enter $v$ as a function of $r$, use $x$ for $r$).", answer: { expr: "1/sqrt(x)", domain: [0.5, 4], variable: "x" }, difficulty: 4, hint: "$v = r^{-1/2}$.", explanation: "$v = 1/\\sqrt r$ — speed falls off as the orbit grows: farther is slower." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "A low-Earth-orbit satellite moves faster than the more distant Moon.", answer: true, difficulty: 2, hint: "Closer in means a smaller $r$.", explanation: "Since $v \\propto 1/\\sqrt r$, the closer satellite has the larger orbital speed." },
      { scope: "PRACTICE", kind: "PROOF", prompt: "Arrange the derivation of orbital speed for a circular orbit.", options: ["Gravity equals the centripetal force: $\\dfrac{GMm}{r^2} = \\dfrac{mv^2}{r}$.", "Cancel $m$ from both sides.", "Multiply both sides by $r$: $\\dfrac{GM}{r} = v^2$.", "Take the square root: $v = \\sqrt{GM/r}$."], answer: [], difficulty: 5, hint: "Set the two forces equal, then solve for $v$.", explanation: "Equating gravity to the centripetal requirement and solving gives $v = \\sqrt{GM/r}$." },
    ],
  },

  // ───────────────────────────── 5. Kepler's Laws ─────────────────────────────
  {
    slug: "keplers-laws",
    title: "Kepler's Laws",
    tagline: "The geometry and rhythm of orbits",
    estMinutes: 16,
    xpReward: 170,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Three Laws for Every Orbit", sub: "Decades before Newton, Kepler distilled mountains of data into three crisp rules that every planet, moon, and comet obeys." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Johannes Kepler spent years poring over Tycho Brahe's painstaking observations of Mars and emerged with three empirical laws — long before anyone knew *why* they held. Newton later showed they all follow from his single law of gravitation.\n\nKepler's laws still describe everything from the planets to binary stars to the satellites you depend on. They let astronomers weigh distant stars and let engineers place a satellite in exactly the orbit they need." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**First law — the law of ellipses.** Every planet moves in an **ellipse** with the Sun at one **focus** (not the center). An ellipse is a stretched circle; how stretched it is, is its *eccentricity*. The closest point to the Sun is the **perihelion**, the farthest the **aphelion**.\n\n**Second law — the law of equal areas.** The line from the Sun to a planet **sweeps out equal areas in equal times**. Since the area near the Sun is swept with a short radius, the planet must move *faster* when closer and *slower* when farther. This is a direct consequence of the **conservation of angular momentum** — with gravity pulling straight toward the Sun, there is no twisting torque about it, so angular momentum stays constant.\n\n**Third law — the harmonic law.** The square of a planet's orbital **period** is proportional to the cube of its orbital radius (more precisely, its semi-major axis):\n\n$$T^2 \\propto r^3.$$\n\nFor circular orbits the full form, derivable from Newton's gravity, is\n\n$$T^2 = \\frac{4\\pi^2}{GM}\\,r^3.$$\n\nThe proportionality constant $4\\pi^2/(GM)$ is the same for *every* body orbiting that central mass $M$ — which is exactly why one curve fits all the planets at once, and why measuring a moon's $T$ and $r$ lets you weigh its planet." } },
      { kind: "CONCEPT", title: "Derivation: the harmonic law $T^2 \\propto r^3$", content: { markdown: "Start from the circular orbital speed from the previous lesson, $v = \\sqrt{GM/r}$, and the definition of speed as circumference over period, $v = 2\\pi r/T$. Set them equal:\n\n$$\\frac{2\\pi r}{T} = \\sqrt{\\frac{GM}{r}}.$$\n\nSquare both sides to remove the root:\n\n$$\\frac{4\\pi^2 r^2}{T^2} = \\frac{GM}{r}.$$\n\nCross-multiply to isolate $T^2$:\n\n$$T^2 = \\frac{4\\pi^2 r^2 \\cdot r}{GM} = \\frac{4\\pi^2}{GM}\\,r^3.$$\n\nSo $T^2 \\propto r^3$, with a constant $4\\pi^2/(GM)$ that depends only on the central mass — Kepler's third law, recovered from Newton's gravity." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Kepler scaling", problem: "Planet B orbits 4× farther than planet A. How many times longer is B's year? (Use $T^2 \\propto r^3$.)", steps: ["$T \\propto r^{3/2}$.", "$4^{3/2} = (\\sqrt 4)^3 = 2^3 = 8$."], answer: "B's year is 8 times longer." },
        { title: "Equal areas", problem: "Where in its elliptical orbit does a comet move fastest, and why?", steps: ["The Sun–comet line sweeps equal areas in equal times.", "Near the Sun the radius is short, so the comet must move faster to sweep the same area.", "This is conservation of angular momentum."], answer: "At perihelion (closest approach), where it moves fastest." },
        { title: "Weighing a star", problem: "Why does measuring a planet's $T$ and $r$ reveal the central mass $M$?", steps: ["$T^2 = 4\\pi^2 r^3/(GM)$.", "Rearrange: $M = 4\\pi^2 r^3/(G T^2)$.", "Everything on the right is measurable."], answer: "Kepler's third law lets you solve for $M$ from the orbit's size and period." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Ellipses, equal areas, and $T^2 \\propto r^3$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $T^2 \\propto r^3$ and the equal-areas idea." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: angular momentum and the second law", content: { markdown: "Kepler's second law is conservation of angular momentum in disguise. The area swept in a small time $\\Delta t$ is approximately the thin triangle $\\Delta A \\approx \\tfrac12 r (v\\,\\Delta t)$, so the *areal velocity* is $\\dfrac{\\Delta A}{\\Delta t} = \\tfrac12 r v_\\perp$, where $v_\\perp$ is the component of velocity perpendicular to the radius. The angular momentum of the planet is $L = m r v_\\perp$, so\n\n$$\\frac{\\Delta A}{\\Delta t} = \\frac{L}{2m}.$$\n\nGravity always points straight at the Sun, exerting **no torque** about it, so $L$ is constant — and therefore the areal velocity is constant. Equal areas in equal times is exactly this statement. The same conservation principle reaches far beyond orbits, from spinning skaters to galaxies." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"The Sun sits at the center of a planet's orbit.\"** It sits at a *focus* of the ellipse, which is offset from the center.\n\n**\"Planets move at constant speed.\"** Only the *areal* velocity is constant; the planet speeds up near the Sun and slows down far away (equal areas, not equal arcs).\n\n**\"Kepler's third law says $T \\propto r^3$.\"** It is the *square* of the period that scales with the *cube* of the radius: $T^2 \\propto r^3$, so $T \\propto r^{3/2}$." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["First law: orbits are ellipses with the Sun at one focus.", "Second law: the Sun–planet line sweeps equal areas in equal times (faster when closer).", "The second law is conservation of angular momentum — gravity exerts no torque.", "Third law: $T^2 \\propto r^3$; for circular orbits $T^2 = 4\\pi^2 r^3/(GM)$.", "The third-law constant depends only on $M$, so it weighs the central body."], formulas: [{ label: "Harmonic law", tex: "T^2 \\propto r^3" }, { label: "Circular form", tex: "T^2 = \\dfrac{4\\pi^2}{GM}\\,r^3" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Kepler's first law states that a planet's orbit is:", options: ["a circle with the Sun at the center", "an ellipse with the Sun at one focus", "a parabola", "a straight line"], answer: 1, difficulty: 2, explanation: "Orbits are ellipses with the Sun at one focus." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Kepler's second law (equal areas in equal times) is a consequence of the conservation of angular momentum.", answer: true, difficulty: 3, explanation: "Gravity exerts no torque about the Sun, so angular momentum — and thus areal velocity — is conserved." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Kepler's third law states that:", options: ["$T \\propto r$", "$T^2 \\propto r^3$", "$T^3 \\propto r^2$", "$T \\propto 1/r$"], answer: 1, difficulty: 2, explanation: "The square of the period is proportional to the cube of the radius." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Planet B orbits 4 times farther than planet A. Using $T^2 \\propto r^3$, how many times longer is B's orbital period?", answer: { value: 8, tolerance: 0 }, difficulty: 3, hint: "$4^{3/2} = (\\sqrt 4)^3$.", explanation: "$4^{3/2} = 2^3 = 8$ times longer." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "A comet in an elliptical orbit moves fastest:", options: ["farthest from the Sun (aphelion)", "closest to the Sun (perihelion)", "at constant speed throughout", "halfway along the orbit"], answer: 1, difficulty: 3, hint: "Equal areas in equal times.", explanation: "Near the Sun it sweeps the same area with a shorter radius, so it must move faster — fastest at perihelion." },
      { scope: "PRACTICE", kind: "GRAPH", prompt: "With the third-law constant set to 1, the period follows $T = r^{1.5}$. Graph it (enter $T$ as a function of $r$, use $x$ for $r$).", answer: { expr: "x^1.5", domain: [0, 4], variable: "x" }, difficulty: 4, hint: "$T = r^{3/2}$.", explanation: "$T = r^{1.5}$ — period rises faster than linearly, but slower than $r^2$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "The Sun sits exactly at the center of each planet's elliptical orbit.", answer: false, difficulty: 2, hint: "Where on an ellipse does Kepler's first law place it?", explanation: "The Sun is at a focus of the ellipse, which is offset from the center." },
      { scope: "PRACTICE", kind: "PROOF", prompt: "Arrange the derivation of Kepler's third law for a circular orbit.", options: ["Set orbital speed equal to circumference over period: $\\dfrac{2\\pi r}{T} = \\sqrt{\\dfrac{GM}{r}}$.", "Square both sides: $\\dfrac{4\\pi^2 r^2}{T^2} = \\dfrac{GM}{r}$.", "Cross-multiply to isolate $T^2$: $T^2 = \\dfrac{4\\pi^2 r^2 \\cdot r}{GM}$.", "Simplify: $T^2 = \\dfrac{4\\pi^2}{GM} r^3$, so $T^2 \\propto r^3$."], answer: [], difficulty: 5, hint: "Start from $v = 2\\pi r/T = \\sqrt{GM/r}$.", explanation: "Equating the two expressions for $v$, squaring, and isolating $T^2$ gives $T^2 = 4\\pi^2 r^3/(GM)$." },
    ],
  },
];
