import type { LessonSeed } from "../types.js";

/**
 * Magnetism & Electromagnetism (intro university). Algebra-based, with the
 * calculus definitions surfaced where they clarify the physics. Builds on the
 * existing Electricity & Magnetism unit (charges, fields, circuits) and carries
 * the story through to induction, Lenz's law, and inductance.
 */
export const magnetismLessons: LessonSeed[] = [
  // ───────── 1. Magnetic Fields & Force on Moving Charges ─────────
  {
    slug: "magnetic-fields-and-force-on-charges",
    title: "Magnetic Fields & Force on Moving Charges",
    tagline: "Why a moving charge feels a sideways shove",
    estMinutes: 16,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "The Magnetic Force", sub: "A magnet on its own does nothing to a charge sitting still. Set that charge moving and a brand-new force appears — always at right angles to the motion." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Magnetic forces steer the electron beams that once painted television screens, bend protons around the Large Hadron Collider, and deflect the solar wind so it spills harmlessly around our planet as auroras.\n\nThe defining feature of the magnetic force is strange and important: it acts only on **moving** charges, and it always pushes **perpendicular** to the velocity. That single fact explains why magnetic forces make things turn in circles rather than speed them up." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "A **magnetic field** $\\vec B$ fills the space around magnets and currents, measured in **teslas** ($\\text{T}$). Field lines run from a magnet's north pole to its south pole, and a small compass needle lines up along them.\n\nA charge $q$ moving with speed $v$ through a field $B$ feels a force whose magnitude is\n\n$$F = q\\,v\\,B\\,\\sin\\theta$$\n\nwhere $\\theta$ is the angle between the velocity $\\vec v$ and the field $\\vec B$. Read off the consequences:\n\n- A charge **at rest** ($v = 0$) feels no magnetic force.\n- A charge moving **parallel** to the field ($\\theta = 0$ or $180^\\circ$) feels no force, because $\\sin\\theta = 0$.\n- The force is **largest** when the motion is **perpendicular** to the field ($\\theta = 90^\\circ$, $\\sin\\theta = 1$), giving $F = qvB$.\n\n**Direction — the right-hand rule.** Point the fingers of your right hand along $\\vec v$, curl them toward $\\vec B$; your thumb points along $\\vec v \\times \\vec B$, which is the force on a **positive** charge. For a negative charge, the force points the opposite way." } },
      { kind: "CONCEPT", title: "Derivation: why the motion is circular", content: { markdown: "Because the magnetic force is always perpendicular to the velocity, it can never speed a charge up or slow it down — it only changes the *direction*. A force of constant size that is always perpendicular to the velocity is exactly the recipe for **uniform circular motion**.\n\nSet the magnetic force equal to the centripetal force needed to hold the charge on a circle of radius $r$:\n\n$$qvB = \\frac{m v^2}{r}.$$\n\nCancel one factor of $v$ and solve for the radius:\n\n$$r = \\frac{m v}{q B}.$$\n\nFaster or heavier particles trace wider circles; stronger fields tighten the loop. This is the working principle of the **mass spectrometer** and the **cyclotron**." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Force at right angles", problem: "A proton ($q = 1.6\\times10^{-19}\\,\\text{C}$) moves at $v = 2.0\\times10^{6}\\,\\text{m/s}$ perpendicular to a field $B = 0.50\\,\\text{T}$. Find the magnetic force.", steps: ["Perpendicular motion means $\\theta = 90^\\circ$, so $\\sin\\theta = 1$ and $F = qvB$.", "$F = (1.6\\times10^{-19})(2.0\\times10^{6})(0.50) = 1.6\\times10^{-13}\\,\\text{N}$."], answer: "$F = 1.6\\times10^{-13}\\,\\text{N}$." },
        { title: "Moving along the field", problem: "An electron travels exactly parallel to a magnetic field. What magnetic force does it feel?", steps: ["Parallel motion gives $\\theta = 0$, so $\\sin\\theta = 0$.", "$F = qvB\\sin 0 = 0$."], answer: "Zero — no force when motion is along the field." },
        { title: "Radius of the circle", problem: "A particle of mass $m = 1.0\\times10^{-26}\\,\\text{kg}$ and charge $q = 1.6\\times10^{-19}\\,\\text{C}$ moves at $v = 3.0\\times10^{5}\\,\\text{m/s}$ across a field $B = 0.20\\,\\text{T}$. Find the radius of its path.", steps: ["Use $r = \\dfrac{mv}{qB}$.", "$r = \\dfrac{(1.0\\times10^{-26})(3.0\\times10^{5})}{(1.6\\times10^{-19})(0.20)} = \\dfrac{3.0\\times10^{-21}}{3.2\\times10^{-20}} \\approx 0.094\\,\\text{m}$."], answer: "$r \\approx 0.094\\,\\text{m}$ (about 9.4 cm)." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Mind the angle and the right-hand rule." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $F = qvB\\sin\\theta$ and $r = mv/(qB)$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: the full Lorentz force", content: { markdown: "Electric and magnetic forces are two faces of one law. The complete **Lorentz force** on a charge is\n\n$$\\vec F = q\\vec E + q\\,\\vec v \\times \\vec B.$$\n\nThe first term acts on any charge, moving or not, and points along $\\vec E$. The second is the magnetic piece — present only when the charge moves, and always perpendicular to both $\\vec v$ and $\\vec B$ through the cross product. A **velocity selector** balances the two terms ($qE = qvB$) so that only charges with speed $v = E/B$ pass straight through, a trick used inside mass spectrometers." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A magnet pulls on any nearby charge.\"** Only on *moving* charges. A charge at rest in a magnetic field feels no magnetic force at all.\n\n**\"The magnetic force speeds the charge up.\"** It can't — being perpendicular to the velocity, it does zero work, so it changes direction but never speed.\n\n**\"The force points along the field.\"** It points perpendicular to *both* the velocity and the field, given by the right-hand rule, not along $\\vec B$." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["A magnetic field $\\vec B$ is measured in teslas; it acts only on moving charges.", "$F = qvB\\sin\\theta$ — maximal when $\\vec v \\perp \\vec B$, zero when $\\vec v \\parallel \\vec B$.", "The right-hand rule gives the direction (reverse it for negative charges).", "Because the force is perpendicular to $v$, charges move in circles of radius $r = mv/(qB)$."], formulas: [{ label: "Magnetic force", tex: "F = qvB\\sin\\theta" }, { label: "Circular radius", tex: "r = \\dfrac{mv}{qB}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The magnetic force on a charge is largest when its velocity is:", options: ["parallel to $\\vec B$", "perpendicular to $\\vec B$", "zero", "anti-parallel to $\\vec B$"], answer: 1, difficulty: 2, explanation: "$F = qvB\\sin\\theta$ peaks at $\\theta = 90^\\circ$ where $\\sin\\theta = 1$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "A charge sitting at rest in a magnetic field feels a magnetic force.", answer: false, difficulty: 1, explanation: "No — the magnetic force needs motion ($F = qvB\\sin\\theta = 0$ when $v = 0$)." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The magnetic force does no work on a moving charge because it is always:", options: ["very small", "perpendicular to the velocity", "parallel to the velocity", "negative"], answer: 1, difficulty: 3, explanation: "Being perpendicular to $\\vec v$, the force changes direction but not speed, so it does zero work." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A charge $q = 2.0\\times10^{-6}\\,\\text{C}$ moves at $v = 500\\,\\text{m/s}$ perpendicular to $B = 0.40\\,\\text{T}$. Force in newtons?", answer: { value: 0.0004, tolerance: 0.00002 }, hint: "$F = qvB$ since $\\theta = 90^\\circ$.", explanation: "$F = (2.0\\times10^{-6})(500)(0.40) = 4.0\\times10^{-4}\\,\\text{N}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A charge moves parallel to a magnetic field. The magnetic force on it, in newtons, is:", answer: { value: 0, tolerance: 0 }, hint: "What is $\\sin 0^\\circ$?", explanation: "$\\theta = 0$, so $\\sin\\theta = 0$ and $F = 0$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the magnitude of the magnetic force on a charge moving perpendicular to the field, in terms of $q$, $v$, and $B$. (Type like `q*v*B`.)", answer: { expr: "q*v*B", vars: ["q", "v", "B"] }, difficulty: 2, hint: "Perpendicular means $\\sin\\theta = 1$.", explanation: "With $\\theta = 90^\\circ$, $F = qvB\\sin 90^\\circ = qvB$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A particle of mass $2.0\\times10^{-25}\\,\\text{kg}$, charge $1.6\\times10^{-19}\\,\\text{C}$, moves at $4.0\\times10^{4}\\,\\text{m/s}$ across $B = 0.50\\,\\text{T}$. Radius of its circular path, in metres?", answer: { value: 0.1, tolerance: 0.01 }, difficulty: 4, hint: "$r = mv/(qB)$.", explanation: "$r = \\dfrac{(2.0\\times10^{-25})(4.0\\times10^{4})}{(1.6\\times10^{-19})(0.50)} = \\dfrac{8.0\\times10^{-21}}{8.0\\times10^{-20}} = 0.10\\,\\text{m}$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Doubling a charged particle's speed (everything else fixed) doubles the radius of its circular path in a magnetic field.", answer: true, difficulty: 3, hint: "Look at $r = mv/(qB)$.", explanation: "Radius is proportional to $v$, so doubling $v$ doubles $r$." },
    ],
  },

  // ───────── 2. Force on Current-Carrying Wires ─────────
  {
    slug: "force-on-current-carrying-wires",
    title: "Force on Current-Carrying Wires",
    tagline: "Many moving charges add up to a push you can feel",
    estMinutes: 15,
    xpReward: 155,
    difficulty: 3,
    requiresMath: "rates-and-unit-rates",
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Wires That Push", sub: "A current is just a parade of moving charges. Put that wire in a magnetic field and every charge gets shoved — adding up to a force strong enough to spin a motor." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Every electric motor — in a fan, a drill, a high-speed train — turns because a current-carrying wire feels a force in a magnetic field. The same effect drives loudspeakers, which jiggle a coil in a field to push air. Understanding the force on a wire is the bridge from \"magnetism is interesting\" to \"magnetism does work.\"" } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "A wire carrying current $I$ holds a stream of moving charges, so the magnetic force on each charge adds up to a force on the whole wire. For a straight length $L$ of wire in a uniform field $B$,\n\n$$F = B\\,I\\,L\\,\\sin\\theta$$\n\nwhere $\\theta$ is the angle between the wire (the direction of the current) and the field $\\vec B$. The pattern mirrors the single-charge law:\n\n- The force is **greatest** when the wire is **perpendicular** to the field ($\\theta = 90^\\circ$): $F = BIL$.\n- A wire running **parallel** to the field ($\\theta = 0$) feels **no** force.\n\n**Direction.** Use the right-hand rule with the current playing the role of velocity: fingers point along the conventional current $I$, curl toward $\\vec B$, and the thumb gives the force direction.\n\n**Two parallel wires** carrying currents exert forces on each other through their magnetic fields: currents in the **same** direction **attract**, opposite directions **repel** — the basis of the formal definition of the ampere." } },
      { kind: "CONCEPT", title: "Derivation: how a motor turns", content: { markdown: "Picture a rectangular loop of wire carrying current, sitting in a magnetic field. The two opposite sides carry current in **opposite** directions, so the forces on them point in opposite directions — one side is pushed up, the other down. That pair of forces forms a **couple** that twists the loop: a **torque**.\n\nFor a loop of $N$ turns, area $A$, carrying current $I$ in field $B$, the torque is\n\n$$\\tau = N\\,B\\,I\\,A\\,\\sin\\phi,$$\n\nwhere $\\phi$ is the angle between the field and the loop's normal. The torque is largest when the loop lies along the field and vanishes when the loop is perpendicular to it. A **commutator** flips the current direction every half-turn so the torque keeps pushing the same way — and the loop spins continuously. That is an electric motor." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Wire perpendicular to the field", problem: "A straight wire of length $L = 0.30\\,\\text{m}$ carries $I = 4.0\\,\\text{A}$ perpendicular to a field $B = 0.50\\,\\text{T}$. Find the force.", steps: ["Perpendicular means $\\theta = 90^\\circ$, so $F = BIL$.", "$F = (0.50)(4.0)(0.30) = 0.60\\,\\text{N}$."], answer: "$F = 0.60\\,\\text{N}$." },
        { title: "Wire at an angle", problem: "The same wire ($L = 0.30\\,\\text{m}$, $I = 4.0\\,\\text{A}$, $B = 0.50\\,\\text{T}$) is now tilted so $\\theta = 30^\\circ$. Find the force.", steps: ["$F = BIL\\sin\\theta = (0.50)(4.0)(0.30)\\sin 30^\\circ$.", "$\\sin 30^\\circ = 0.5$, so $F = 0.60 \\times 0.5 = 0.30\\,\\text{N}$."], answer: "$F = 0.30\\,\\text{N}$." },
        { title: "Wire along the field", problem: "A current-carrying wire runs exactly parallel to $\\vec B$. What force does it feel?", steps: ["$\\theta = 0$, so $\\sin\\theta = 0$.", "$F = BIL\\sin 0 = 0$."], answer: "Zero force." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Use $F = BIL\\sin\\theta$ and the motor idea." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Identify the angle between current and field first." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: from wire force to the ampere", content: { markdown: "Two long parallel wires a distance $d$ apart, carrying currents $I_1$ and $I_2$, attract or repel with a force per unit length\n\n$$\\frac{F}{L} = \\frac{\\mu_0 I_1 I_2}{2\\pi d},$$\n\nwhere $\\mu_0 = 4\\pi\\times10^{-7}\\,\\text{T·m/A}$ is the permeability of free space. For decades this very relation *defined* the ampere: the current that, in two such wires one metre apart, produces a force of $2\\times10^{-7}\\,\\text{N}$ per metre. The modern SI fixes the ampere via the elementary charge instead, but the physics of attracting and repelling wires is unchanged." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A wire always feels a force in a magnetic field.\"** Not if the current runs parallel to the field — then $\\sin\\theta = 0$ and $F = 0$.\n\n**\"Parallel currents repel.\"** It's the opposite: currents in the *same* direction attract; only *opposite* currents repel.\n\n**\"A motor's torque is constant through a full turn.\"** Without a commutator the torque would reverse every half-turn; the commutator flips the current to keep the turning steady." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["A current-carrying wire in a field feels $F = BIL\\sin\\theta$.", "Force is maximal when the wire is perpendicular to $\\vec B$, zero when parallel.", "The right-hand rule (current as velocity) gives the direction.", "Forces on the sides of a current loop produce torque — the principle of the electric motor."], formulas: [{ label: "Force on a wire", tex: "F = BIL\\sin\\theta" }, { label: "Torque on a loop", tex: "\\tau = NBIA\\sin\\phi" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The force on a current-carrying wire is given by:", options: ["$F = BIL\\sin\\theta$", "$F = qE$", "$F = IR$", "$F = mv/(qB)$"], answer: 0, difficulty: 1, explanation: "The magnetic force on a length $L$ of wire is $F = BIL\\sin\\theta$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "A wire carrying current parallel to a magnetic field feels no magnetic force.", answer: true, difficulty: 2, explanation: "With $\\theta = 0$, $\\sin\\theta = 0$, so $F = 0$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Two parallel wires carrying current in the same direction will:", options: ["attract each other", "repel each other", "feel no force", "spin"], answer: 0, difficulty: 3, explanation: "Currents in the same direction attract; opposite currents repel." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A wire of length $0.50\\,\\text{m}$ carries $3.0\\,\\text{A}$ perpendicular to a $0.20\\,\\text{T}$ field. Force in newtons?", answer: { value: 0.3, tolerance: 0.01 }, hint: "$F = BIL$ at $90^\\circ$.", explanation: "$F = (0.20)(3.0)(0.50) = 0.30\\,\\text{N}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $0.40\\,\\text{m}$ wire carries $5.0\\,\\text{A}$ at $\\theta = 30^\\circ$ to a $0.10\\,\\text{T}$ field. Force in newtons?", answer: { value: 0.1, tolerance: 0.005 }, difficulty: 3, hint: "Include $\\sin 30^\\circ = 0.5$.", explanation: "$F = (0.10)(5.0)(0.40)(0.5) = 0.10\\,\\text{N}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the force on a wire of length $L$ carrying current $I$ perpendicular to a field $B$, in terms of $B$, $I$, and $L$. (Type like `B*I*L`.)", answer: { expr: "B*I*L", vars: ["B", "I", "L"] }, difficulty: 2, hint: "Perpendicular means $\\sin\\theta = 1$.", explanation: "$F = BIL\\sin 90^\\circ = BIL$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A single-turn loop of area $0.02\\,\\text{m}^2$ carries $10\\,\\text{A}$ in a $0.30\\,\\text{T}$ field, with the field in the plane of the loop ($\\phi = 90^\\circ$). Torque in N·m?", answer: { value: 0.06, tolerance: 0.005 }, difficulty: 4, hint: "$\\tau = NBIA\\sin\\phi$ with $N = 1$, $\\sin 90^\\circ = 1$.", explanation: "$\\tau = (1)(0.30)(10)(0.02)(1) = 0.060\\,\\text{N·m}$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "A commutator reverses the current direction each half-turn so a motor keeps turning the same way.", answer: true, difficulty: 3, hint: "What would happen to the torque without it?", explanation: "Yes — flipping the current each half-turn keeps the torque pushing in one rotational sense." },
    ],
  },

  // ───────── 3. Magnetic Fields from Currents ─────────
  {
    slug: "magnetic-fields-from-currents",
    title: "Magnetic Fields from Currents",
    tagline: "Electric currents are the true source of magnetism",
    estMinutes: 15,
    xpReward: 155,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Currents Make Fields", sub: "Oersted noticed a compass twitch beside a wire and changed physics forever: every electric current wraps itself in a magnetic field." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "In 1820 Hans Christian Oersted saw a compass needle deflect when he switched on a nearby current — the first hint that electricity and magnetism are linked. That observation makes **electromagnets** possible: coils whose magnetism switches on and off with a current, lifting cars in scrapyards, reading and writing hard drives, and forming the heart of every MRI scanner. Magnetism, it turns out, comes from moving charge." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Every current produces a magnetic field.** Three standard geometries cover most problems:\n\n**Straight wire.** The field circles the wire in loops; its strength a distance $r$ away is\n\n$$B = \\frac{\\mu_0 I}{2\\pi r}.$$\n\nThe field weakens as $1/r$ with distance and grows with the current $I$. Wrap your right hand around the wire with the thumb along the current; your fingers curl the way $\\vec B$ points.\n\n**Circular loop.** Bending the wire into a loop concentrates the field through its centre, where\n\n$$B = \\frac{\\mu_0 I}{2R}$$\n\nfor a single loop of radius $R$. The loop behaves like a tiny bar magnet, with a north and south face.\n\n**Solenoid.** A long coil of $N$ turns over a length $\\ell$ makes a nearly **uniform** field inside, like a bar magnet's interior:\n\n$$B = \\mu_0 n I, \\qquad n = \\frac{N}{\\ell},$$\n\nwhere $n$ is the number of turns per metre. Here $\\mu_0 = 4\\pi\\times10^{-7}\\,\\text{T·m/A}$ is the permeability of free space." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Field beside a wire", problem: "Find the magnetic field $2.0\\,\\text{cm}$ from a long straight wire carrying $I = 5.0\\,\\text{A}$. ($\\mu_0 = 4\\pi\\times10^{-7}$)", steps: ["Use $B = \\dfrac{\\mu_0 I}{2\\pi r}$ with $r = 0.020\\,\\text{m}$.", "$B = \\dfrac{(4\\pi\\times10^{-7})(5.0)}{2\\pi(0.020)} = \\dfrac{(2\\times10^{-7})(5.0)}{0.020} = 5.0\\times10^{-5}\\,\\text{T}$."], answer: "$B = 5.0\\times10^{-5}\\,\\text{T}$." },
        { title: "Solenoid field", problem: "A solenoid has $n = 1000$ turns per metre and carries $I = 2.0\\,\\text{A}$. Find the interior field.", steps: ["Use $B = \\mu_0 n I$.", "$B = (4\\pi\\times10^{-7})(1000)(2.0) \\approx 2.5\\times10^{-3}\\,\\text{T}$."], answer: "$B \\approx 2.5\\times10^{-3}\\,\\text{T}$ (about 2.5 mT)." },
        { title: "Doubling the current", problem: "If you double the current in a straight wire, what happens to the field at a fixed distance?", steps: ["$B = \\dfrac{\\mu_0 I}{2\\pi r}$ is proportional to $I$.", "Doubling $I$ doubles $B$."], answer: "The field doubles." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Match each geometry to its field formula." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $\\mu_0 = 4\\pi\\times10^{-7}\\,\\text{T·m/A}$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: Ampère's law and the origin of all magnetism", content: { markdown: "These three formulas are special cases of **Ampère's law**, which relates the magnetic field looping around any closed path to the current threading through it: $\\oint \\vec B \\cdot d\\vec\\ell = \\mu_0 I_{\\text{enc}}$. For the symmetric cases above it reproduces the $1/r$ wire field and the uniform solenoid field directly.\n\nIt also reveals something deep: even a **bar magnet** is, at heart, currents — the circulating motion and intrinsic spin of its electrons act like countless tiny current loops. There are no isolated magnetic \"charges\" (no magnetic monopoles); all magnetism traces back to moving charge." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Magnetism comes from special magnetic particles.\"** No magnetic monopole has ever been found. All magnetic fields come from moving charges (currents) or electron spin.\n\n**\"The field of a straight wire points straight out from it.\"** It *circles* the wire in loops, perpendicular to the wire — found with the right-hand grip rule.\n\n**\"A longer solenoid has a stronger inside field.\"** What matters is turns *per metre* ($n$) and current, not total length: $B = \\mu_0 n I$." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Every current creates a magnetic field — magnetism comes from moving charge.", "Straight wire: $B = \\mu_0 I/(2\\pi r)$, circling the wire and falling off as $1/r$.", "Loop centre: $B = \\mu_0 I/(2R)$; the loop acts like a small bar magnet.", "Solenoid: $B = \\mu_0 n I$, a nearly uniform interior field set by turns per metre."], formulas: [{ label: "Straight wire", tex: "B = \\dfrac{\\mu_0 I}{2\\pi r}" }, { label: "Loop centre", tex: "B = \\dfrac{\\mu_0 I}{2R}" }, { label: "Solenoid", tex: "B = \\mu_0 n I" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The magnetic field around a long straight wire:", options: ["points straight away from the wire", "circles the wire in loops", "points along the wire", "is uniform everywhere"], answer: 1, difficulty: 2, explanation: "The field forms closed loops circling the wire, given by the right-hand grip rule." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Magnetic fields can be produced by electric currents.", answer: true, difficulty: 1, explanation: "Oersted's discovery: every current creates a magnetic field." },
      { scope: "CONCEPT_CHECK", kind: "MATCHING", prompt: "Match each current geometry to its field formula.", options: { left: ["Straight wire", "Loop centre", "Solenoid"], right: ["$\\mu_0 I/(2\\pi r)$", "$\\mu_0 I/(2R)$", "$\\mu_0 n I$"] }, answer: ["$\\mu_0 I/(2\\pi r)$", "$\\mu_0 I/(2R)$", "$\\mu_0 n I$"], difficulty: 3, explanation: "Wire $\\to \\mu_0 I/(2\\pi r)$, loop centre $\\to \\mu_0 I/(2R)$, solenoid $\\to \\mu_0 n I$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A straight wire carries $10\\,\\text{A}$. Field at $r = 0.050\\,\\text{m}$, in teslas? ($\\mu_0 = 4\\pi\\times10^{-7}$)", answer: { value: 0.00004, tolerance: 0.000002 }, hint: "$B = \\mu_0 I/(2\\pi r)$; note $\\mu_0/(2\\pi) = 2\\times10^{-7}$.", explanation: "$B = (2\\times10^{-7})(10)/0.050 = 4.0\\times10^{-5}\\,\\text{T}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A solenoid with $n = 500$ turns/m carries $4.0\\,\\text{A}$. Interior field in teslas? ($\\mu_0 = 4\\pi\\times10^{-7}$; use $\\pi \\approx 3.14$)", answer: { value: 0.00251, tolerance: 0.0002 }, difficulty: 3, hint: "$B = \\mu_0 n I$.", explanation: "$B = (4\\pi\\times10^{-7})(500)(4.0) \\approx 2.51\\times10^{-3}\\,\\text{T}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the interior field of a solenoid in terms of $\\mu_0$ (type `mu_0`), turns per metre $n$, and current $I$. (Type like `mu_0*n*I`.)", answer: { expr: "mu_0*n*I", vars: ["mu_0", "n", "I"] }, difficulty: 2, hint: "It's a simple product of the three.", explanation: "$B = \\mu_0 n I$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Doubling the current in a straight wire doubles the magnetic field at a fixed distance.", answer: true, difficulty: 2, hint: "$B \\propto I$.", explanation: "Since $B = \\mu_0 I/(2\\pi r)$ is proportional to $I$, doubling $I$ doubles $B$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "At $0.10\\,\\text{m}$ from a wire the field is $1.0\\times10^{-5}\\,\\text{T}$. At $0.20\\,\\text{m}$ (same current), the field in teslas is?", answer: { value: 0.000005, tolerance: 0.0000005 }, difficulty: 3, hint: "$B \\propto 1/r$ — double the distance, half the field.", explanation: "Doubling $r$ halves $B$: $5.0\\times10^{-6}\\,\\text{T}$." },
    ],
  },

  // ───────── 4. Electromagnetic Induction & Faraday's Law ─────────
  {
    slug: "electromagnetic-induction-faradays-law",
    title: "Electromagnetic Induction & Faraday's Law",
    tagline: "A changing magnetic field makes electricity",
    estMinutes: 17,
    xpReward: 165,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Making Electricity from Motion", sub: "Currents make fields — and, astonishingly, a changing field makes currents right back. This two-way street powers nearly every generator on Earth." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Move a magnet near a coil and a voltage appears — out of nothing but motion. This is **electromagnetic induction**, discovered by Michael Faraday in 1831, and it is how essentially all of the world's electricity is generated: spinning turbines (driven by steam, wind, or falling water) move coils through magnetic fields. It also runs transformers, induction cooktops, and the wireless charger on your nightstand." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "First we need **magnetic flux** $\\Phi$ — a measure of how much magnetic field passes through a loop of area $A$:\n\n$$\\Phi = B\\,A\\,\\cos\\theta,$$\n\nwhere $\\theta$ is the angle between the field and the loop's **normal** (the line perpendicular to its surface). Flux is largest when the field pierces the loop straight on ($\\theta = 0$) and zero when the field skims along the loop's plane ($\\theta = 90^\\circ$). The unit is the **weber** ($1\\,\\text{Wb} = 1\\,\\text{T·m}^2$).\n\n**Faraday's law** says an EMF (voltage) is induced whenever the flux *changes*:\n\n$$\\varepsilon = -N\\,\\frac{d\\Phi}{dt}.$$\n\nHere $N$ is the number of turns. The faster the flux changes, the bigger the voltage. You can change the flux three ways:\n\n- change the field strength $B$,\n- change the loop's area $A$ (stretch or shrink it),\n- change the angle $\\theta$ (rotate the loop — this is how a generator works).\n\nThe minus sign is **Lenz's law**, the subject of the next lesson; for now, focus on the *size* of the induced EMF, $|\\varepsilon| = N\\,|\\Delta\\Phi / \\Delta t|$." } },
      { kind: "CONCEPT", title: "Derivation: EMF from a sliding bar", content: { markdown: "A conducting bar of length $L$ slides at speed $v$ along rails in a field $B$ perpendicular to the loop. As it moves a distance $\\Delta x$, the enclosed area grows by $\\Delta A = L\\,\\Delta x$, so the flux changes by $\\Delta\\Phi = B\\,\\Delta A = B L\\,\\Delta x$.\n\nDivide by the time $\\Delta t$ and use $v = \\Delta x/\\Delta t$:\n\n$$|\\varepsilon| = \\frac{\\Delta\\Phi}{\\Delta t} = B L \\frac{\\Delta x}{\\Delta t} = B L v.$$\n\nThis **motional EMF**, $\\varepsilon = BLv$, is Faraday's law in miniature: a wire of length $L$ swept through a field at speed $v$ generates a voltage proportional to all three." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Flux through a loop", problem: "A field $B = 0.40\\,\\text{T}$ passes straight through a loop of area $A = 0.05\\,\\text{m}^2$ ($\\theta = 0$). Find the flux.", steps: ["$\\Phi = BA\\cos\\theta$ with $\\cos 0 = 1$.", "$\\Phi = (0.40)(0.05) = 0.020\\,\\text{Wb}$."], answer: "$\\Phi = 0.020\\,\\text{Wb}$." },
        { title: "Induced EMF", problem: "The flux through a single loop drops from $0.020\\,\\text{Wb}$ to $0$ in $0.10\\,\\text{s}$. Find the magnitude of the induced EMF.", steps: ["$|\\varepsilon| = N\\,|\\Delta\\Phi/\\Delta t|$ with $N = 1$.", "$|\\Delta\\Phi| = 0.020\\,\\text{Wb}$, so $|\\varepsilon| = 0.020/0.10 = 0.20\\,\\text{V}$."], answer: "$|\\varepsilon| = 0.20\\,\\text{V}$." },
        { title: "Sliding bar", problem: "A bar of length $L = 0.25\\,\\text{m}$ slides at $v = 4.0\\,\\text{m/s}$ through a field $B = 0.30\\,\\text{T}$ (perpendicular). Find the motional EMF.", steps: ["Use $\\varepsilon = BLv$.", "$\\varepsilon = (0.30)(0.25)(4.0) = 0.30\\,\\text{V}$."], answer: "$\\varepsilon = 0.30\\,\\text{V}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "What changes the flux, and how fast?" } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $\\Phi = BA\\cos\\theta$, $|\\varepsilon| = N|\\Delta\\Phi/\\Delta t|$, and $\\varepsilon = BLv$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: Faraday's law as a field equation", content: { markdown: "Faraday's law is one of **Maxwell's four equations**, the complete description of electromagnetism. In its field form it states that a changing magnetic field creates a circulating electric field: $\\oint \\vec E \\cdot d\\vec\\ell = -\\dfrac{d\\Phi}{dt}$. The induced electric field is *not* conservative — it loops around, which is exactly what drives current around a closed circuit.\n\nPaired with the reverse effect (a changing electric field producing a magnetic field), this is what allows **electromagnetic waves** — light, radio, X-rays — to propagate through empty space, each field continually regenerating the other." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A strong magnetic field induces a voltage.\"** A *steady* field induces nothing. Only a *changing* flux induces an EMF.\n\n**\"Flux is just the field strength.\"** Flux is field times area times $\\cos\\theta$ — geometry matters. The same field through a bigger or better-aligned loop gives more flux.\n\n**\"You must move the magnet to induce a current.\"** Any way of changing the flux works: switching the field on or off, rotating the loop, or stretching its area all induce an EMF." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Magnetic flux $\\Phi = BA\\cos\\theta$ measures field passing through a loop (unit: weber).", "Faraday's law: a changing flux induces $\\varepsilon = -N\\,d\\Phi/dt$.", "Change flux by varying $B$, area $A$, or angle $\\theta$ (rotating a loop).", "A bar swept through a field gives motional EMF $\\varepsilon = BLv$."], formulas: [{ label: "Magnetic flux", tex: "\\Phi = BA\\cos\\theta" }, { label: "Faraday's law", tex: "\\varepsilon = -N\\dfrac{d\\Phi}{dt}" }, { label: "Motional EMF", tex: "\\varepsilon = BLv" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "An EMF is induced in a loop whenever:", options: ["the magnetic field is strong", "the magnetic flux changes", "current flows nearby", "the loop is large"], answer: 1, difficulty: 2, explanation: "Faraday's law: only a *changing* flux induces an EMF." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "A steady, unchanging magnetic field through a stationary loop induces no EMF.", answer: true, difficulty: 2, explanation: "With $d\\Phi/dt = 0$, there is no induced EMF." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Magnetic flux is defined as:", options: ["$BA\\cos\\theta$", "$BIL$", "$qvB$", "$\\mu_0 n I$"], answer: 0, difficulty: 1, explanation: "$\\Phi = BA\\cos\\theta$, with $\\theta$ measured from the loop's normal." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A field $B = 0.50\\,\\text{T}$ passes straight through a loop of area $0.04\\,\\text{m}^2$ ($\\theta = 0$). Flux in webers?", answer: { value: 0.02, tolerance: 0.001 }, hint: "$\\Phi = BA\\cos 0$.", explanation: "$\\Phi = (0.50)(0.04)(1) = 0.020\\,\\text{Wb}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "The flux through a single loop changes by $0.030\\,\\text{Wb}$ in $0.060\\,\\text{s}$. Magnitude of the induced EMF, in volts?", answer: { value: 0.5, tolerance: 0.02 }, hint: "$|\\varepsilon| = |\\Delta\\Phi/\\Delta t|$.", explanation: "$0.030/0.060 = 0.50\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A coil of $200$ turns has its flux change by $0.010\\,\\text{Wb}$ in $0.50\\,\\text{s}$. Induced EMF in volts?", answer: { value: 4, tolerance: 0.1 }, difficulty: 3, hint: "$|\\varepsilon| = N|\\Delta\\Phi/\\Delta t|$.", explanation: "$200 \\times 0.010/0.50 = 4.0\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A bar of length $0.20\\,\\text{m}$ slides at $5.0\\,\\text{m/s}$ through a perpendicular field $B = 0.40\\,\\text{T}$. Motional EMF in volts?", answer: { value: 0.4, tolerance: 0.02 }, difficulty: 3, hint: "$\\varepsilon = BLv$.", explanation: "$(0.40)(0.20)(5.0) = 0.40\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the motional EMF of a bar of length $L$ moving at speed $v$ through a perpendicular field $B$, in terms of $B$, $L$, $v$. (Type like `B*L*v`.)", answer: { expr: "B*L*v", vars: ["B", "L", "v"] }, difficulty: 2, hint: "It's a product of the three.", explanation: "$\\varepsilon = BLv$." },
    ],
  },

  // ───────── 5. Lenz's Law & Inductance ─────────
  {
    slug: "lenzs-law-and-inductance",
    title: "Lenz's Law & Inductance",
    tagline: "Nature pushes back against any change in flux",
    estMinutes: 17,
    xpReward: 165,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Opposing the Change", sub: "Drop a magnet down a copper pipe and it floats down in slow motion. The induced currents fight the very change that creates them — that's Lenz's law made visible." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "The minus sign in Faraday's law is not a footnote — it is a statement about how nature conserves energy. **Lenz's law** tells us the *direction* of every induced current: it always opposes the change that produced it. This single principle explains regenerative braking in electric cars, the slow fall of a magnet through copper, the behaviour of transformers that step voltages up and down across the power grid, and why generators take effort to turn." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Lenz's law.** An induced current always flows in the direction that **opposes the change in flux** that caused it. That is the meaning of the minus sign in $\\varepsilon = -N\\,d\\Phi/dt$.\n\n- Push a north pole *toward* a coil and the coil's induced current makes its near face a *north* pole — repelling the magnet, fighting the approach.\n- Pull the magnet *away* and the induced current reverses to *attract* it, fighting the retreat.\n\nLenz's law is really **conservation of energy** in disguise: if induced currents *helped* the change instead of opposing it, you'd get free energy. The opposition is why a generator resists being turned — you must do work to make electricity.\n\n**Inductance.** A coil opposes changes in *its own* current too, because a changing current changes its own flux. This **self-inductance** $L$ (units: **henry**, $\\text{H}$) sets the back-EMF:\n\n$$\\varepsilon = -L\\,\\frac{dI}{dt}.$$\n\nA coil with large $L$ strongly resists sudden current changes — an inductor smooths current the way a flywheel smooths rotation. The energy stored in an inductor's magnetic field is\n\n$$U = \\tfrac{1}{2}L I^2.$$" } },
      { kind: "CONCEPT", title: "Derivation: generators and transformers", content: { markdown: "**Generator.** Rotate a coil of $N$ turns and area $A$ at angular speed $\\omega$ in a field $B$. The angle is $\\theta = \\omega t$, so the flux is $\\Phi = BA\\cos(\\omega t)$. By Faraday's law,\n\n$$\\varepsilon = -N\\frac{d\\Phi}{dt} = N B A\\,\\omega \\sin(\\omega t).$$\n\nThe output is a **sine wave** — alternating current — with peak EMF $\\varepsilon_0 = NBA\\omega$. Spinning faster raises both the voltage and the frequency.\n\n**Transformer.** Two coils share an iron core so they link the same changing flux. Applying Faraday's law to each gives the turns-ratio relation\n\n$$\\frac{V_s}{V_p} = \\frac{N_s}{N_p}.$$\n\nMore turns on the secondary steps the voltage *up*; fewer steps it *down*. Transformers only work on **alternating** current, because they need a continually changing flux." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Which way does it flow?", problem: "You push the north pole of a magnet toward a coil. Which pole does the coil's near face become, and why?", steps: ["Lenz's law: the induced current opposes the change (the approaching north pole).", "To repel the incoming north pole, the near face must also be a north pole."], answer: "A north pole — it repels the magnet to oppose the approach." },
        { title: "Back-EMF of an inductor", problem: "An inductor of $L = 0.50\\,\\text{H}$ has its current change at $dI/dt = 4.0\\,\\text{A/s}$. Find the magnitude of the induced EMF.", steps: ["$|\\varepsilon| = L\\,|dI/dt|$.", "$|\\varepsilon| = (0.50)(4.0) = 2.0\\,\\text{V}$."], answer: "$|\\varepsilon| = 2.0\\,\\text{V}$." },
        { title: "Step-down transformer", problem: "A transformer has $N_p = 1000$ turns on the primary and $N_s = 100$ on the secondary. If $V_p = 120\\,\\text{V}$, find $V_s$.", steps: ["$V_s = V_p (N_s/N_p) = 120 \\times (100/1000)$.", "$V_s = 120 \\times 0.10 = 12\\,\\text{V}$."], answer: "$V_s = 12\\,\\text{V}$ — a step-down transformer." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Opposition, energy, and turns ratios." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $\\varepsilon = -L\\,dI/dt$, $U = \\tfrac12 L I^2$, and $V_s/V_p = N_s/N_p$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: eddy currents and magnetic braking", content: { markdown: "When a *solid* conductor (not just a wire loop) moves through a changing field, the induced currents swirl through the bulk metal as **eddy currents**. By Lenz's law they oppose the motion, converting kinetic energy into heat. This is **magnetic braking**: the smooth, frictionless slowing used in trains, roller coasters, and gym exercise bikes, and the reason a magnet dropped down a thick copper pipe drifts down rather than falling freely. The same eddy currents waste energy in transformer cores, which is why those cores are built from thin insulated **laminations** to break the current loops up." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"The induced current helps the magnet along.\"** It always *opposes* the change — Lenz's law is energy conservation; a helping current would mean free energy.\n\n**\"A transformer can step up DC voltage.\"** Transformers need a *changing* flux, so they only work on alternating current; steady DC induces nothing.\n\n**\"An inductor blocks all current.\"** It only opposes *changes* in current. Once the current is steady, $dI/dt = 0$ and the back-EMF vanishes." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Lenz's law: induced currents oppose the change in flux that causes them (the minus sign).", "It is conservation of energy — opposition is why generators take work to turn.", "Self-inductance gives a back-EMF $\\varepsilon = -L\\,dI/dt$; energy stored is $U = \\tfrac12 L I^2$.", "Generators output AC ($\\varepsilon = NBA\\omega\\sin\\omega t$); transformers scale voltage by $N_s/N_p$ and need AC."], formulas: [{ label: "Self-inductance EMF", tex: "\\varepsilon = -L\\dfrac{dI}{dt}" }, { label: "Inductor energy", tex: "U = \\tfrac{1}{2}L I^2" }, { label: "Transformer ratio", tex: "\\dfrac{V_s}{V_p} = \\dfrac{N_s}{N_p}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "An induced current always flows in the direction that:", options: ["aids the change in flux", "opposes the change in flux", "is independent of the flux", "maximizes the field"], answer: 1, difficulty: 2, explanation: "Lenz's law: induced currents oppose the change that produces them." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Lenz's law is a consequence of conservation of energy.", answer: true, difficulty: 2, explanation: "If induced currents aided the change, you'd get energy for free — so they must oppose it." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "A transformer requires which kind of input current to work?", options: ["alternating (AC)", "steady direct (DC)", "zero current", "either works equally"], answer: 0, difficulty: 3, explanation: "Transformers rely on a changing flux, so they need AC; steady DC induces nothing." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "An inductor of $L = 0.20\\,\\text{H}$ has its current change at $dI/dt = 3.0\\,\\text{A/s}$. Magnitude of the induced EMF, in volts?", answer: { value: 0.6, tolerance: 0.02 }, hint: "$|\\varepsilon| = L|dI/dt|$.", explanation: "$(0.20)(3.0) = 0.60\\,\\text{V}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Energy stored in a $0.50\\,\\text{H}$ inductor carrying $4.0\\,\\text{A}$, in joules?", answer: { value: 4, tolerance: 0.1 }, difficulty: 3, hint: "$U = \\tfrac12 L I^2$.", explanation: "$\\tfrac12(0.50)(4.0^2) = \\tfrac12(0.50)(16) = 4.0\\,\\text{J}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A transformer has $N_p = 500$ and $N_s = 2500$ turns. With $V_p = 100\\,\\text{V}$, find $V_s$ in volts.", answer: { value: 500, tolerance: 1 }, difficulty: 3, hint: "$V_s = V_p (N_s/N_p)$.", explanation: "$V_s = 100 \\times (2500/500) = 100 \\times 5 = 500\\,\\text{V}$ — a step-up transformer." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the energy stored in an inductor in terms of $L$ and current $I$. (Type like `(1/2)*L*I^2`.)", answer: { expr: "(1/2)*L*I^2", vars: ["L", "I"] }, difficulty: 3, hint: "It's one-half times $L$ times the square of the current.", explanation: "$U = \\tfrac12 L I^2$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Dropping a magnet down a copper pipe makes it fall slower than free fall because of induced (eddy) currents that oppose its motion.", answer: true, difficulty: 3, hint: "Lenz's law applied to a solid conductor.", explanation: "Eddy currents oppose the changing flux, braking the magnet's fall." },
    ],
  },
];
