import type { LessonSeed } from "../types.js";

/**
 * Waves & Optics (intro university). Light as an electromagnetic wave, then the
 * classic optics toolkit: reflection and refraction, image formation by mirrors
 * and lenses, the wave phenomena of interference and diffraction, and finally
 * polarization. Algebra-based with the wave picture surfaced throughout.
 *
 * NOTE on grading: the expression engine evaluates trig in RADIANS, so any
 * Snell's-law / Malus's-law numbers that involve degrees are shipped as NUMERIC
 * questions with pre-computed values rather than degree-based SYMBOLIC/GRAPH.
 */
export const opticsLessons: LessonSeed[] = [
  // ───────────────────────── 1. Electromagnetic Waves ─────────────────────────
  {
    slug: "em-waves",
    title: "Electromagnetic Waves",
    tagline: "Light as a self-sustaining ripple of electric and magnetic fields",
    estMinutes: 15,
    xpReward: 150,
    difficulty: 2,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "What Light Is", sub: "Light is not a substance and not a particle of dust — it is an electromagnetic wave, an oscillation of electric and magnetic fields that carries energy across empty space at the fastest speed there is." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Every photo you take, every Wi-Fi packet, every X-ray and microwave dinner, and the sunlight warming your face are all the *same thing*: electromagnetic waves, differing only in **frequency**. Understanding light as a wave is the foundation of optics, communications, and astronomy — when we look at a distant galaxy, we are reading EM waves that left it billions of years ago." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "An **electromagnetic (EM) wave** is a travelling disturbance in which an oscillating **electric field** $\\vec E$ and an oscillating **magnetic field** $\\vec B$ regenerate each other and propagate together. The two fields are perpendicular to each other and to the direction of travel — so light is a **transverse** wave.\n\nUnlike sound or water waves, an EM wave needs **no medium**: it travels through a vacuum. In a vacuum every EM wave moves at the **speed of light**:\n\n$$c \\approx 3.00\\times 10^{8}\\,\\text{m/s}.$$\n\nLike any wave, light obeys the universal **wave relation** linking speed, frequency $f$, and wavelength $\\lambda$:\n\n$$c = f\\,\\lambda.$$\n\nBecause $c$ is fixed, frequency and wavelength trade off inversely: short wavelength means high frequency, and vice versa.\n\nThe **electromagnetic spectrum** is the full range of frequencies, traditionally ordered from low frequency / long wavelength to high frequency / short wavelength:\n\n**radio → microwave → infrared → visible → ultraviolet → X-ray → gamma.**\n\nVisible light is a tiny slice in the middle, roughly $400\\,\\text{nm}$ (violet) to $700\\,\\text{nm}$ (red). The **photon energy** grows with frequency ($E = hf$), which is why gamma rays are dangerous and radio waves are not." } },
      { kind: "CONCEPT", title: "Derivation: why c = f·λ", content: { markdown: "The relation $c = f\\lambda$ isn't special to light — it holds for *any* periodic wave. In one **period** $T$ (the time for one full oscillation), the wave advances exactly one **wavelength** $\\lambda$. Speed is distance over time, so\n\n$$c = \\frac{\\lambda}{T}.$$\n\nFrequency is the number of oscillations per second, the reciprocal of the period, $f = 1/T$. Substituting $1/T = f$:\n\n$$c = \\lambda f = f\\,\\lambda.$$\n\nSince $c$ is constant in vacuum, this single equation lets you convert between any wave's frequency and its wavelength." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Wavelength of an FM station", problem: "An FM radio station broadcasts at $f = 1.0\\times 10^{8}\\,\\text{Hz}$ (100 MHz). What is the wavelength of the wave? Use $c = 3.0\\times 10^8\\,\\text{m/s}$.", steps: ["Rearrange $c = f\\lambda$ for wavelength: $\\lambda = c/f$.", "$\\lambda = \\dfrac{3.0\\times 10^8}{1.0\\times 10^8} = 3.0\\,\\text{m}$."], answer: "$\\lambda = 3.0\\,\\text{m}$." },
        { title: "Frequency of green light", problem: "Green light has a wavelength of about $\\lambda = 5.0\\times 10^{-7}\\,\\text{m}$ (500 nm). Find its frequency.", steps: ["Rearrange for frequency: $f = c/\\lambda$.", "$f = \\dfrac{3.0\\times 10^8}{5.0\\times 10^{-7}} = 6.0\\times 10^{14}\\,\\text{Hz}$."], answer: "$f = 6.0\\times 10^{14}\\,\\text{Hz}$." },
        { title: "Ordering the spectrum", problem: "Rank these by increasing frequency: visible light, radio waves, X-rays.", steps: ["Frequency rises as we go up the spectrum from radio toward gamma.", "Radio has the lowest frequency, then visible, then X-rays."], answer: "radio < visible < X-rays." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Light is a wave — use $c = f\\lambda$ and the spectrum order." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $c = 3.0\\times 10^8\\,\\text{m/s}$ unless told otherwise." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: wave and particle together", content: { markdown: "Light behaves as a wave (it diffracts and interferes) **and** as a stream of particles called **photons**, each carrying energy $E = hf$ where $h = 6.63\\times 10^{-34}\\,\\text{J·s}$ is Planck's constant. This **wave–particle duality** is one of the central surprises of modern physics. The wave picture explains optics — refraction, interference, polarization — beautifully, which is why this whole unit leans on it. The photon picture takes over when light is emitted or absorbed one quantum at a time, the subject of the Quantum unit later on the journey." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Light needs a medium to travel, like sound does.\"** No — EM waves are self-sustaining and cross the vacuum of space. That is how sunlight reaches Earth.\n\n**\"Different colours of light travel at different speeds in vacuum.\"** In a vacuum, every EM wave travels at exactly $c$, regardless of frequency. (Inside glass or water they *do* differ — that's dispersion.)\n\n**\"Higher frequency means a longer wavelength.\"** It's the opposite: since $c = f\\lambda$ is fixed, higher frequency means a *shorter* wavelength." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Light is a transverse electromagnetic wave: perpendicular oscillating $\\vec E$ and $\\vec B$ fields.", "EM waves need no medium and travel at $c \\approx 3.0\\times 10^8\\,\\text{m/s}$ in vacuum.", "The wave relation $c = f\\lambda$ ties speed, frequency, and wavelength.", "The spectrum runs radio → microwave → infrared → visible → ultraviolet → X-ray → gamma, by increasing frequency."], formulas: [{ label: "Wave relation", tex: "c = f\\lambda" }, { label: "Photon energy", tex: "E = hf" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The speed of light in a vacuum is approximately:", options: ["$3\\times 10^8\\,\\text{m/s}$", "$3\\times 10^6\\,\\text{m/s}$", "$340\\,\\text{m/s}$", "$3\\times 10^{10}\\,\\text{m/s}$"], answer: 0, difficulty: 1, explanation: "$c \\approx 3.0\\times 10^8\\,\\text{m/s}$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Electromagnetic waves require a medium to travel through.", answer: false, difficulty: 1, explanation: "EM waves are self-sustaining and travel through a vacuum — that's how sunlight reaches Earth." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "For light in vacuum, if the frequency increases, the wavelength:", options: ["decreases", "increases", "stays the same", "becomes zero"], answer: 0, difficulty: 2, explanation: "$c = f\\lambda$ is fixed, so $f$ up means $\\lambda$ down." },
      { scope: "CONCEPT_CHECK", kind: "MATCHING", prompt: "Match each band of the spectrum to its relative frequency.", options: { left: ["Radio waves", "Visible light", "Gamma rays"], right: ["Lowest frequency", "Middle frequency", "Highest frequency"] }, answer: ["Lowest frequency", "Middle frequency", "Highest frequency"], difficulty: 2, explanation: "Frequency rises from radio up to gamma; visible light sits in the middle." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A radio wave has frequency $f = 1.0\\times 10^8\\,\\text{Hz}$. Its wavelength in metres ($c = 3.0\\times 10^8$)?", answer: { value: 3, tolerance: 0.05 }, hint: "$\\lambda = c/f$.", explanation: "$\\lambda = (3.0\\times 10^8)/(1.0\\times 10^8) = 3.0\\,\\text{m}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Green light has $\\lambda = 5.0\\times 10^{-7}\\,\\text{m}$. Its frequency in Hz ($c = 3.0\\times 10^8$)? Give the answer as a multiple of $10^{14}$ (i.e. enter $6.0$ for $6.0\\times 10^{14}$).", answer: { value: 6, tolerance: 0.1 }, difficulty: 3, hint: "$f = c/\\lambda$, then divide by $10^{14}$.", explanation: "$f = (3.0\\times 10^8)/(5.0\\times 10^{-7}) = 6.0\\times 10^{14}\\,\\text{Hz}$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Visible light occupies only a small portion of the electromagnetic spectrum.", answer: true, hint: "Think radio through gamma.", explanation: "Visible light (≈400–700 nm) is a thin slice between infrared and ultraviolet." },
      { scope: "PRACTICE", kind: "ORDER", prompt: "Order these EM bands from longest wavelength to shortest.", options: ["Radio", "Infrared", "Visible", "X-ray", "Gamma"], answer: [], difficulty: 3, hint: "Longest wavelength is the same as lowest frequency.", explanation: "Wavelength shortens (frequency rises) from radio through gamma." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "In an electromagnetic wave, the electric and magnetic fields are:", options: ["perpendicular to each other and to the direction of travel", "parallel to each other", "parallel to the direction of travel", "at random angles"], answer: 0, hint: "Light is a transverse wave.", explanation: "$\\vec E \\perp \\vec B$, and both are perpendicular to the propagation direction." },
    ],
  },

  // ─────────────────────── 2. Reflection & Refraction ───────────────────────
  {
    slug: "reflection-refraction",
    title: "Reflection & Refraction",
    tagline: "How light bounces off surfaces and bends between materials",
    estMinutes: 16,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Bouncing and Bending", sub: "A mirror sends light back; a glass of water bends the spoon inside it. Two simple laws — reflection and Snell's law — govern almost everything light does at a surface." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Lenses focus your phone's camera, fibre-optic cables carry the internet, and rainbows split sunlight — all because light **bends and bounces** at the boundary between materials. The two rules here, the law of reflection and Snell's law, are the entire grammar of geometric optics. Master them and the next lesson on mirrors and lenses falls into place." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "Angles in optics are measured from the **normal** — the line perpendicular to the surface at the point where the ray hits.\n\n**Law of reflection.** When light bounces off a surface, the angle of reflection equals the angle of incidence:\n\n$$\\theta_r = \\theta_i.$$\n\n**Refractive index.** Light slows down inside a material. The **index of refraction** $n$ measures how much:\n\n$$n = \\frac{c}{v},$$\n\nwhere $v$ is the speed of light in that material. Vacuum has $n = 1$ (air is very close); water is about $1.33$; common glass about $1.5$. Since $v \\le c$, we always have $n \\ge 1$.\n\n**Snell's law (refraction).** When light crosses from medium 1 into medium 2 it bends, and the angles relate to the indices by\n\n$$n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2.$$\n\nGoing into a *denser* medium (larger $n$) bends the ray *toward* the normal; going into a *less dense* medium bends it *away*.\n\n**Total internal reflection.** When light tries to pass from a denser into a less dense medium ($n_1 > n_2$) at a steep enough angle, Snell's law has no solution and the light reflects entirely back. This happens beyond the **critical angle** $\\theta_c$, given by setting $\\theta_2 = 90^\\circ$:\n\n$$\\sin\\theta_c = \\frac{n_2}{n_1}.$$\n\nThis is exactly what traps light inside an optical fibre." } },
      { kind: "CONCEPT", title: "Derivation: the critical angle", content: { markdown: "Start from Snell's law for light leaving a dense medium ($n_1$) for a lighter one ($n_2 < n_1$):\n\n$$n_1\\sin\\theta_1 = n_2\\sin\\theta_2.$$\n\nAs the incidence angle $\\theta_1$ grows, the refracted ray bends further from the normal, so $\\theta_2$ grows faster and reaches $90^\\circ$ first. At that exact moment the refracted ray skims along the surface — this defines the **critical angle** $\\theta_c$. Substituting $\\theta_2 = 90^\\circ$ (so $\\sin\\theta_2 = 1$):\n\n$$n_1\\sin\\theta_c = n_2(1) \\;\\Longrightarrow\\; \\sin\\theta_c = \\frac{n_2}{n_1}.$$\n\nFor any $\\theta_1 > \\theta_c$ there is no real refraction angle — all the light reflects internally." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Speed of light in glass", problem: "Glass has a refractive index $n = 1.5$. How fast does light travel inside it? Use $c = 3.0\\times 10^8\\,\\text{m/s}$.", steps: ["From $n = c/v$, solve for $v$: $v = c/n$.", "$v = \\dfrac{3.0\\times 10^8}{1.5} = 2.0\\times 10^8\\,\\text{m/s}$."], answer: "$v = 2.0\\times 10^8\\,\\text{m/s}$." },
        { title: "A reflected ray", problem: "A beam strikes a mirror at $30^\\circ$ from the normal. What is the angle of reflection?", steps: ["The law of reflection says $\\theta_r = \\theta_i$.", "So $\\theta_r = 30^\\circ$."], answer: "$30^\\circ$ from the normal." },
        { title: "Bending into water", problem: "Light in air ($n_1 = 1.00$) hits water ($n_2 = 1.33$) at $\\theta_1 = 30^\\circ$. Does it bend toward or away from the normal? Find $\\sin\\theta_2$.", steps: ["Snell: $n_1\\sin\\theta_1 = n_2\\sin\\theta_2$, so $\\sin\\theta_2 = \\dfrac{n_1\\sin\\theta_1}{n_2}$.", "$\\sin\\theta_2 = \\dfrac{(1.00)(0.500)}{1.33} = 0.376$, giving $\\theta_2 \\approx 22^\\circ$.", "Since $\\theta_2 < \\theta_1$, the ray bends toward the normal — as expected entering a denser medium."], answer: "Toward the normal; $\\sin\\theta_2 \\approx 0.376$, $\\theta_2 \\approx 22^\\circ$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Measure angles from the normal; remember $n \\ge 1$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $c = 3.0\\times 10^8\\,\\text{m/s}$ and the indices given in each problem." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: dispersion and rainbows", content: { markdown: "A material's refractive index depends slightly on the **wavelength** of the light — this is **dispersion**. Violet light slows a touch more than red in glass, so it bends a touch more. A prism therefore spreads white light into a spectrum, and raindrops do the same to sunlight to make a rainbow: each colour leaves at a slightly different angle. Dispersion is also why lens designers must correct for **chromatic aberration**, the coloured fringing you'd otherwise see at the edges of a cheap lens." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Angles are measured from the surface.\"** They are measured from the **normal** (perpendicular to the surface). A ray grazing the surface has an angle near $90^\\circ$, not near $0^\\circ$.\n\n**\"Light always bends toward the normal when entering glass.\"** Only when entering a *denser* medium. Going from glass into air (less dense) it bends *away* from the normal.\n\n**\"Total internal reflection can happen going from air into glass.\"** No — it only occurs going from the *denser* medium toward the *less dense* one ($n_1 > n_2$), beyond the critical angle." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Angles are measured from the normal; the law of reflection is $\\theta_r = \\theta_i$.", "Refractive index $n = c/v \\ge 1$ measures how much a medium slows light.", "Snell's law: $n_1\\sin\\theta_1 = n_2\\sin\\theta_2$ — denser medium bends light toward the normal.", "Beyond the critical angle ($\\sin\\theta_c = n_2/n_1$, with $n_1 > n_2$), light is totally internally reflected."], formulas: [{ label: "Law of reflection", tex: "\\theta_r = \\theta_i" }, { label: "Refractive index", tex: "n = \\dfrac{c}{v}" }, { label: "Snell's law", tex: "n_1\\sin\\theta_1 = n_2\\sin\\theta_2" }, { label: "Critical angle", tex: "\\sin\\theta_c = \\dfrac{n_2}{n_1}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Angles in reflection and refraction are measured from the:", options: ["normal (perpendicular to the surface)", "surface itself", "horizontal", "incoming ray"], answer: 0, difficulty: 1, explanation: "All optics angles are measured from the normal." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "For the law of reflection, the angle of reflection equals the angle of incidence.", answer: true, difficulty: 1, explanation: "$\\theta_r = \\theta_i$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "A material with a larger refractive index $n$:", options: ["slows light down more", "speeds light up", "has no effect on light's speed", "always reflects all light"], answer: 0, difficulty: 2, explanation: "$n = c/v$, so a larger $n$ means a smaller speed $v$ inside the material." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Light travels through a medium at $v = 2.0\\times 10^8\\,\\text{m/s}$. Its refractive index ($c = 3.0\\times 10^8$)?", answer: { value: 1.5, tolerance: 0.02 }, hint: "$n = c/v$.", explanation: "$n = (3.0\\times 10^8)/(2.0\\times 10^8) = 1.5$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Glass has $n = 1.5$. Speed of light inside it, as a multiple of $10^8\\,\\text{m/s}$ (enter $2.0$ for $2.0\\times 10^8$)?", answer: { value: 2, tolerance: 0.05 }, hint: "$v = c/n$.", explanation: "$v = (3.0\\times 10^8)/1.5 = 2.0\\times 10^8\\,\\text{m/s}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Light goes from air ($n_1=1.00$) into water ($n_2=1.33$) with $\\theta_1$ such that $\\sin\\theta_1 = 0.500$. Find $\\sin\\theta_2$ (Snell's law).", answer: { value: 0.376, tolerance: 0.01 }, difficulty: 3, hint: "$\\sin\\theta_2 = n_1\\sin\\theta_1/n_2$.", explanation: "$\\sin\\theta_2 = (1.00)(0.500)/1.33 = 0.376$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Total internal reflection can occur when light goes from glass into air at a steep enough angle.", answer: true, difficulty: 3, hint: "Which direction (denser→lighter) allows it?", explanation: "Glass ($n_1=1.5$) into air ($n_2=1.0$) is denser → lighter, so beyond the critical angle the light reflects entirely." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "Light passes from glass ($n=1.5$) into air ($n=1.0$). The ray bends:", options: ["away from the normal", "toward the normal", "not at all", "back the way it came"], answer: 0, hint: "Entering a less dense medium.", explanation: "Going to a smaller index, the ray bends away from the normal." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "For light in glass ($n_1 = 1.50$) meeting air ($n_2 = 1.00$), what is $\\sin\\theta_c$ for the critical angle?", answer: { value: 0.667, tolerance: 0.01 }, difficulty: 4, hint: "$\\sin\\theta_c = n_2/n_1$.", explanation: "$\\sin\\theta_c = 1.00/1.50 = 0.667$ (so $\\theta_c \\approx 41.8^\\circ$)." },
    ],
  },

  // ───────────────────────── 3. Mirrors & Lenses ─────────────────────────
  {
    slug: "mirrors-and-lenses",
    title: "Mirrors & Lenses",
    tagline: "Forming images with the thin-lens and mirror equation",
    estMinutes: 17,
    xpReward: 160,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Forming Images", sub: "A curved mirror or a lens collects bending rays and brings them to a focus. One compact equation — 1/f = 1/dₒ + 1/dᵢ — predicts where the image lands and how big it is." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Eyeglasses, telescopes, microscopes, camera lenses, and the lens in your own eye all do one job: take rays from an object and reassemble them into an **image**. The same thin-lens / mirror equation describes them all. Once you can predict image position, size, and whether it's real or virtual, you can reason about any optical instrument." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "A converging lens or concave mirror has a **focal length** $f$: the distance at which parallel rays converge to a point, the **focal point**.\n\nThe **thin-lens / mirror equation** relates the focal length to the object distance $d_o$ and the image distance $d_i$:\n\n$$\\frac{1}{f} = \\frac{1}{d_o} + \\frac{1}{d_i}.$$\n\nThe **magnification** tells you the image's size and orientation:\n\n$$m = \\frac{h_i}{h_o} = -\\frac{d_i}{d_o}.$$\n\nReading the signs (standard convention):\n\n- $d_i > 0$: a **real image** — formed by rays that actually converge; it can be projected on a screen and is **inverted** ($m < 0$).\n- $d_i < 0$: a **virtual image** — rays only *appear* to come from it; it cannot be projected and is **upright** ($m > 0$). A plane mirror or a magnifying glass held close produces one.\n- $|m| > 1$ means the image is enlarged; $|m| < 1$ means it's reduced.\n\nFor a **converging** lens or **concave** mirror, $f > 0$. For a **diverging** lens or **convex** mirror, $f < 0$, and the image is always virtual, upright, and reduced." } },
      { kind: "CONCEPT", title: "Derivation: rearranging the lens equation", content: { markdown: "The thin-lens equation $\\dfrac{1}{f} = \\dfrac{1}{d_o} + \\dfrac{1}{d_i}$ is most useful once solved for whichever quantity you need. To find the image distance, isolate $1/d_i$:\n\n$$\\frac{1}{d_i} = \\frac{1}{f} - \\frac{1}{d_o} = \\frac{d_o - f}{f\\,d_o}.$$\n\nInvert both sides:\n\n$$d_i = \\frac{f\\,d_o}{d_o - f}.$$\n\nThis closed form makes the sign behaviour obvious: when the object sits *outside* the focal point ($d_o > f$), the denominator is positive and $d_i > 0$ — a real image. When the object sits *inside* the focal point ($d_o < f$), the denominator goes negative and $d_i < 0$ — a virtual, upright, magnified image (the magnifying-glass case)." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Where is the image?", problem: "An object sits $30\\,\\text{cm}$ in front of a converging lens of focal length $f = 10\\,\\text{cm}$. Find the image distance.", steps: ["Use $\\dfrac{1}{f} = \\dfrac{1}{d_o} + \\dfrac{1}{d_i}$, so $\\dfrac{1}{d_i} = \\dfrac{1}{f} - \\dfrac{1}{d_o}$.", "$\\dfrac{1}{d_i} = \\dfrac{1}{10} - \\dfrac{1}{30} = \\dfrac{3 - 1}{30} = \\dfrac{2}{30} = \\dfrac{1}{15}$.", "$d_i = 15\\,\\text{cm}$ (positive ⇒ real image)."], answer: "$d_i = 15\\,\\text{cm}$, a real image." },
        { title: "How big and which way up?", problem: "For that lens, find the magnification.", steps: ["$m = -d_i/d_o = -15/30 = -0.5$."], answer: "$m = -0.5$: the image is half size and inverted (real)." },
        { title: "A magnifying glass", problem: "An object is placed $5\\,\\text{cm}$ from a converging lens with $f = 10\\,\\text{cm}$ (object inside the focal point). Find the image distance and describe it.", steps: ["$\\dfrac{1}{d_i} = \\dfrac{1}{10} - \\dfrac{1}{5} = \\dfrac{1 - 2}{10} = -\\dfrac{1}{10}$.", "$d_i = -10\\,\\text{cm}$ (negative ⇒ virtual).", "$m = -d_i/d_o = -(-10)/5 = +2$ ⇒ upright and twice as large."], answer: "$d_i = -10\\,\\text{cm}$: a virtual, upright, $2\\times$ image — the magnifier in action." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Mind the sign of $d_i$ — it tells you real vs virtual." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $\\dfrac{1}{f} = \\dfrac{1}{d_o} + \\dfrac{1}{d_i}$ and $m = -d_i/d_o$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: lens power and the human eye", content: { markdown: "Opticians describe lenses by their **power** $P = 1/f$, measured in **dioptres** (D) when $f$ is in metres. A lens with $f = 0.5\\,\\text{m}$ has $P = +2\\,\\text{D}$. Powers add: stacking thin lenses gives $P_\\text{total} = P_1 + P_2 + \\dots$, which is why your eye's fixed lens plus a corrective lens combine simply. The eye focuses by *changing* the power of its flexible lens (accommodation); glasses for near- or far-sightedness just add or subtract a few dioptres to land the image back on the retina." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A virtual image can be projected onto a screen.\"** No — only **real** images ($d_i > 0$, formed by rays that actually meet) can be caught on a screen. Virtual images only *appear* to be there.\n\n**\"Magnification greater than 1 means the image is real.\"** Magnification size and real/virtual are independent. A magnifying glass gives $|m| > 1$ for a *virtual* image.\n\n**\"A bigger lens makes a bigger image.\"** Image size is set by $f$, $d_o$ and $d_i$ (via $m$), not by the physical diameter of the lens — diameter affects brightness, not magnification." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["The thin-lens / mirror equation: $1/f = 1/d_o + 1/d_i$.", "Magnification $m = h_i/h_o = -d_i/d_o$; negative $m$ means inverted.", "$d_i > 0$ ⇒ real, inverted, projectable; $d_i < 0$ ⇒ virtual, upright.", "Converging lens / concave mirror: $f > 0$. Diverging lens / convex mirror: $f < 0$ (always virtual, upright, reduced)."], formulas: [{ label: "Thin-lens / mirror equation", tex: "\\dfrac{1}{f} = \\dfrac{1}{d_o} + \\dfrac{1}{d_i}" }, { label: "Magnification", tex: "m = -\\dfrac{d_i}{d_o}" }, { label: "Solved for image distance", tex: "d_i = \\dfrac{f\\,d_o}{d_o - f}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The thin-lens / mirror equation is:", options: ["$\\dfrac{1}{f} = \\dfrac{1}{d_o} + \\dfrac{1}{d_i}$", "$f = d_o + d_i$", "$f = d_o\\,d_i$", "$\\dfrac{1}{f} = d_o - d_i$"], answer: 0, difficulty: 1, explanation: "$1/f = 1/d_o + 1/d_i$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "A real image can be projected onto a screen.", answer: true, difficulty: 2, explanation: "Real images ($d_i > 0$) are formed by rays that actually converge, so they can be caught on a screen." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "A negative magnification ($m < 0$) means the image is:", options: ["inverted", "upright", "virtual", "reduced"], answer: 0, difficulty: 2, explanation: "The sign of $m$ gives orientation: negative is inverted." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Object at $d_o = 30\\,\\text{cm}$, lens $f = 10\\,\\text{cm}$. Image distance $d_i$ in cm?", answer: { value: 15, tolerance: 0.2 }, hint: "$1/d_i = 1/f - 1/d_o$.", explanation: "$1/d_i = 1/10 - 1/30 = 2/30 = 1/15$, so $d_i = 15\\,\\text{cm}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "For that case ($d_o = 30$, $d_i = 15\\,\\text{cm}$), what is the magnification $m$?", answer: { value: -0.5, tolerance: 0.02 }, hint: "$m = -d_i/d_o$.", explanation: "$m = -15/30 = -0.5$ (half size, inverted)." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Object at $d_o = 5\\,\\text{cm}$, converging lens $f = 10\\,\\text{cm}$. Image distance $d_i$ in cm (keep the sign)?", answer: { value: -10, tolerance: 0.3 }, difficulty: 4, hint: "$1/d_i = 1/10 - 1/5$.", explanation: "$1/d_i = (1-2)/10 = -1/10$, so $d_i = -10\\,\\text{cm}$ — a virtual image." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "A diverging lens (negative $f$) always forms a virtual, upright, reduced image.", answer: true, difficulty: 3, hint: "Think of a peephole / convex mirror.", explanation: "For $f < 0$ the image is always virtual, upright, and smaller than the object." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A lens has focal length $f = 0.5\\,\\text{m}$. Its power in dioptres ($P = 1/f$)?", answer: { value: 2, tolerance: 0.05 }, difficulty: 3, hint: "$P = 1/f$ with $f$ in metres.", explanation: "$P = 1/0.5 = +2\\,\\text{D}$." },
    ],
  },

  // ───────────────────── 4. Interference & Diffraction ─────────────────────
  {
    slug: "interference-diffraction",
    title: "Interference & Diffraction",
    tagline: "When waves overlap: bright and dark bands from light itself",
    estMinutes: 17,
    xpReward: 165,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Light Plus Light", sub: "Shine light through two narrow slits and you get not two bright spots but a row of bands. That pattern was the proof that light is a wave — and it follows from one idea: path difference." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "The colours on a soap bubble, the sheen of a CD, the precision of a spectrometer, and the very proof that light is a wave all come from **interference** and **diffraction**. Thomas Young's double-slit experiment in 1801 settled a centuries-old debate by showing light adding to light can produce *darkness* — something only waves can do." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "When two waves overlap, their displacements add — this is **superposition**.\n\n- **Constructive interference**: crests line up with crests, giving a bright result. This happens when the two paths differ by a whole number of wavelengths.\n- **Destructive interference**: a crest lines up with a trough, cancelling out (darkness). This happens at a half-integer number of wavelengths.\n\nThe key quantity is the **path difference** $\\Delta = d\\sin\\theta$ between light from two slits a distance $d$ apart, reaching a screen at angle $\\theta$.\n\n**Double-slit (Young's) condition for bright fringes (maxima):**\n\n$$d\\sin\\theta = m\\lambda, \\qquad m = 0, 1, 2, \\dots$$\n\nHere $m$ is the **order** of the fringe. Dark fringes fall halfway between, at $d\\sin\\theta = (m + \\tfrac12)\\lambda$.\n\n**Diffraction** is the bending and spreading of waves as they pass an edge or a slit. A **diffraction grating** is just thousands of slits per millimetre; it obeys the *same* maxima condition $d\\sin\\theta = m\\lambda$, but with so many slits the bright lines become razor-sharp and widely separated. Because the angle depends on $\\lambda$, a grating splits white light into a clean spectrum — the heart of a spectrometer.\n\nFor a grating, $d$ is the **slit spacing**, the reciprocal of the number of lines per unit length: a grating with $N$ lines per metre has $d = 1/N$." } },
      { kind: "CONCEPT", title: "Derivation: the bright-fringe condition", content: { markdown: "Consider light of wavelength $\\lambda$ from two slits separated by $d$, reaching a distant screen at angle $\\theta$ from the centre line. Geometry shows the light from one slit travels an extra distance — the **path difference** — of\n\n$$\\Delta = d\\sin\\theta.$$\n\nThe two beams arrive **in phase** (crest on crest ⇒ bright) exactly when this extra path is a whole number of wavelengths:\n\n$$d\\sin\\theta = m\\lambda, \\quad m = 0, \\pm 1, \\pm 2, \\dots$$\n\nThey arrive **out of phase** (crest on trough ⇒ dark) when the extra path is a half-integer of wavelengths, $d\\sin\\theta = (m+\\tfrac12)\\lambda$. The central maximum ($m=0$) sits straight ahead, where the path difference is zero for any wavelength." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "First-order angle", problem: "Light of wavelength $\\lambda = 500\\,\\text{nm} = 5.0\\times 10^{-7}\\,\\text{m}$ passes through two slits separated by $d = 1.0\\times 10^{-5}\\,\\text{m}$. Find $\\sin\\theta$ for the first-order ($m=1$) bright fringe.", steps: ["Use $d\\sin\\theta = m\\lambda$, so $\\sin\\theta = m\\lambda/d$.", "$\\sin\\theta = \\dfrac{(1)(5.0\\times 10^{-7})}{1.0\\times 10^{-5}} = 0.050$."], answer: "$\\sin\\theta = 0.050$ (about $2.9^\\circ$)." },
        { title: "Grating spacing", problem: "A diffraction grating has $5000$ lines per centimetre. What is its slit spacing $d$ in metres?", steps: ["$5000$ lines/cm $= 5.0\\times 10^5$ lines/m.", "$d = 1/N = 1/(5.0\\times 10^5) = 2.0\\times 10^{-6}\\,\\text{m}$."], answer: "$d = 2.0\\times 10^{-6}\\,\\text{m}$." },
        { title: "Order of a maximum", problem: "For $d = 2.0\\times 10^{-6}\\,\\text{m}$ and $\\lambda = 5.0\\times 10^{-7}\\,\\text{m}$, what is $\\sin\\theta$ for the second-order ($m=2$) line?", steps: ["$\\sin\\theta = m\\lambda/d = \\dfrac{2(5.0\\times 10^{-7})}{2.0\\times 10^{-6}}$.", "$\\sin\\theta = \\dfrac{1.0\\times 10^{-6}}{2.0\\times 10^{-6}} = 0.50$."], answer: "$\\sin\\theta = 0.50$ (so $\\theta = 30^\\circ$)." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Bright fringes satisfy $d\\sin\\theta = m\\lambda$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Keep wavelengths and spacings in metres; $m$ is the integer order." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: thin-film colours", content: { markdown: "The shifting colours of a soap film or an oil slick come from **thin-film interference**: light reflecting off the top of the film interferes with light reflecting off the bottom, with a path difference set by the film's thickness and refractive index. As the thickness varies, different wavelengths interfere constructively, so you see a rainbow that moves as the film drains. The same principle, run deliberately, makes **anti-reflective coatings** on camera lenses and glasses — a film tuned so that reflected light cancels, letting more light through." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Adding two light beams can only make it brighter.\"** Wave superposition means two beams can *cancel* — destructive interference produces dark fringes. That cancellation is the proof light is a wave.\n\n**\"Diffraction only happens with slits.\"** Any edge, aperture, or obstacle diffracts waves; slits just make the effect tidy and measurable.\n\n**\"A finer grating (more lines) bends light less.\"** More lines per metre means a *smaller* spacing $d$, and since $\\sin\\theta = m\\lambda/d$, a smaller $d$ bends the light to *larger* angles." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Overlapping waves superpose: in phase ⇒ bright (constructive), out of phase ⇒ dark (destructive).", "Path difference $\\Delta = d\\sin\\theta$ sets the outcome.", "Bright fringes (maxima): $d\\sin\\theta = m\\lambda$; dark fringes at half-integer multiples.", "A diffraction grating uses the same condition with tiny spacing $d = 1/N$, giving sharp, well-separated spectral lines."], formulas: [{ label: "Path difference", tex: "\\Delta = d\\sin\\theta" }, { label: "Bright fringes (maxima)", tex: "d\\sin\\theta = m\\lambda" }, { label: "Grating spacing", tex: "d = \\dfrac{1}{N}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Bright fringes in a double-slit pattern occur when the path difference equals:", options: ["a whole number of wavelengths", "a half-integer of wavelengths", "zero only", "the slit width"], answer: 0, difficulty: 2, explanation: "Constructive interference: $d\\sin\\theta = m\\lambda$, a whole number of wavelengths." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Two overlapping light waves can cancel each other to produce darkness.", answer: true, difficulty: 1, explanation: "Destructive interference cancels the waves — this is the hallmark of wave behaviour." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "A diffraction grating with more lines per millimetre has a slit spacing $d$ that is:", options: ["smaller", "larger", "unchanged", "zero"], answer: 0, difficulty: 2, explanation: "$d = 1/N$, so more lines per metre means a smaller spacing." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Double slit: $\\lambda = 5.0\\times 10^{-7}\\,\\text{m}$, $d = 1.0\\times 10^{-5}\\,\\text{m}$. Find $\\sin\\theta$ for $m = 1$.", answer: { value: 0.05, tolerance: 0.002 }, hint: "$\\sin\\theta = m\\lambda/d$.", explanation: "$\\sin\\theta = (1)(5.0\\times 10^{-7})/(1.0\\times 10^{-5}) = 0.050$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A grating has $N = 5.0\\times 10^5$ lines per metre. Its slit spacing $d$, as a multiple of $10^{-6}\\,\\text{m}$ (enter $2.0$ for $2.0\\times 10^{-6}$)?", answer: { value: 2, tolerance: 0.05 }, difficulty: 3, hint: "$d = 1/N$.", explanation: "$d = 1/(5.0\\times 10^5) = 2.0\\times 10^{-6}\\,\\text{m}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Grating $d = 2.0\\times 10^{-6}\\,\\text{m}$, $\\lambda = 5.0\\times 10^{-7}\\,\\text{m}$. Find $\\sin\\theta$ for the second-order ($m=2$) line.", answer: { value: 0.5, tolerance: 0.01 }, difficulty: 3, hint: "$\\sin\\theta = m\\lambda/d$.", explanation: "$\\sin\\theta = 2(5.0\\times 10^{-7})/(2.0\\times 10^{-6}) = 0.50$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "The central maximum ($m = 0$) of a double-slit pattern is located:", options: ["straight ahead, where path difference is zero", "at the largest angle", "only for red light", "never visible"], answer: 0, hint: "Where do both paths have equal length?", explanation: "At $m=0$ the path difference is zero for every wavelength, so the centre is bright." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "A diffraction grating splits white light into a spectrum because the diffraction angle depends on wavelength.", answer: true, difficulty: 3, hint: "$\\sin\\theta = m\\lambda/d$ — does $\\theta$ depend on $\\lambda$?", explanation: "Different wavelengths satisfy $d\\sin\\theta = m\\lambda$ at different angles, separating the colours." },
    ],
  },

  // ───────────────────────────── 5. Polarization ─────────────────────────────
  {
    slug: "polarization",
    title: "Polarization",
    tagline: "Filtering light by the direction its field oscillates",
    estMinutes: 14,
    xpReward: 150,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "The Direction of the Wave", sub: "Light's electric field can wiggle in any direction across the beam. Polarizing filters pick out just one — the trick behind sunglasses, LCD screens, and glare-free photos." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Polarized sunglasses cut glare off water and roads; every LCD and phone screen forms its image with crossed polarizers; photographers use polarizing filters to deepen a blue sky. All of these exploit the fact that light is a **transverse** wave with a *direction* of oscillation that we can select and block." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "Because light is a **transverse** wave, its electric field oscillates in a plane perpendicular to the direction of travel. Ordinary light from the Sun or a bulb is **unpolarized**: the field points in all transverse directions at random.\n\nA **polarizing filter** transmits only the component of the field along its **transmission axis** and absorbs the rest. The light that emerges is **polarized** — its field oscillates along a single direction.\n\n**Unpolarized light through one filter.** A polarizer passes, on average, half the intensity of unpolarized light:\n\n$$I = \\tfrac{1}{2}I_0.$$\n\nThe emerging light is now polarized along the filter's axis.\n\n**Polarized light through a second filter — Malus's law.** If already-polarized light of intensity $I_0$ meets a filter whose axis makes an angle $\\theta$ with the light's polarization, the transmitted intensity is\n\n$$I = I_0 \\cos^2\\theta.$$\n\nReading the extremes:\n\n- $\\theta = 0^\\circ$ (axes aligned): $\\cos^2 0 = 1$, so all the light passes.\n- $\\theta = 90^\\circ$ (**crossed** polarizers): $\\cos^2 90^\\circ = 0$, so **no light** passes — the view goes black.\n- $\\theta = 60^\\circ$: $\\cos^2 60^\\circ = (0.5)^2 = 0.25$, so a quarter passes.\n\nCrossing two polarizers at $90^\\circ$ blocks the beam completely — the surprising demonstration at the heart of this lesson." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "First filter on sunlight", problem: "Unpolarized light of intensity $I_0 = 800\\,\\text{W/m}^2$ passes through a single polarizer. What intensity emerges?", steps: ["A polarizer passes half of unpolarized light: $I = \\tfrac12 I_0$.", "$I = \\tfrac12(800) = 400\\,\\text{W/m}^2$, now polarized along the filter's axis."], answer: "$400\\,\\text{W/m}^2$." },
        { title: "Malus's law at 60°", problem: "Polarized light of intensity $I_0 = 400\\,\\text{W/m}^2$ meets a second polarizer at $\\theta = 60^\\circ$ to its polarization. What gets through?", steps: ["Malus: $I = I_0\\cos^2\\theta$.", "$\\cos 60^\\circ = 0.5$, so $\\cos^2 60^\\circ = 0.25$.", "$I = 400(0.25) = 100\\,\\text{W/m}^2$."], answer: "$100\\,\\text{W/m}^2$." },
        { title: "Crossed polarizers", problem: "Two ideal polarizers are crossed at $90^\\circ$. Polarized light of intensity $I_0$ hits the second. How much passes?", steps: ["$I = I_0\\cos^2 90^\\circ$.", "$\\cos 90^\\circ = 0$, so $I = I_0(0) = 0$."], answer: "Zero — crossed polarizers block the light completely." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "One filter halves unpolarized light; a second follows Malus's law." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Use $I = \\tfrac12 I_0$ for the first filter and $I = I_0\\cos^2\\theta$ thereafter. Helpful values: $\\cos^2 0^\\circ = 1$, $\\cos^2 30^\\circ = 0.75$, $\\cos^2 45^\\circ = 0.5$, $\\cos^2 60^\\circ = 0.25$, $\\cos^2 90^\\circ = 0$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: polarization by reflection and LCDs", content: { markdown: "Light reflecting off a non-metallic surface — water, glass, a road — comes out **partially polarized** horizontally. That's why polarized sunglasses, with a *vertical* transmission axis, cut glare so effectively: the horizontally polarized reflected light is blocked. The angle at which reflection is perfectly polarized is **Brewster's angle**. Liquid-crystal displays push the idea further: an LCD sandwiches a layer of twisting liquid crystals between *crossed* polarizers, and an applied voltage rotates the light's polarization pixel by pixel, switching each one between bright and dark — that's how the screen you're reading forms its image." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A polarizer dims unpolarized light by some random amount.\"** For ideal unpolarized light a single polarizer always passes exactly **half** the intensity, $I = \\tfrac12 I_0$.\n\n**\"Two polarizers always let some light through.\"** When crossed at $90^\\circ$, $\\cos^2 90^\\circ = 0$, so an ideal pair passes **nothing**.\n\n**\"Sound can be polarized too.\"** No — sound is a *longitudinal* wave (it oscillates along its direction of travel), so it has no transverse direction to select. Only transverse waves like light can be polarized." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Light is transverse, so its field has a direction — that direction is its polarization.", "A single polarizer passes half of unpolarized light: $I = \\tfrac12 I_0$, and polarizes it.", "Malus's law: polarized light through a filter at angle $\\theta$ gives $I = I_0\\cos^2\\theta$.", "Crossed polarizers ($\\theta = 90^\\circ$) block the beam entirely; only transverse waves can be polarized."], formulas: [{ label: "Single filter on unpolarized light", tex: "I = \\tfrac{1}{2}I_0" }, { label: "Malus's law", tex: "I = I_0\\cos^2\\theta" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Unpolarized light passing through a single ideal polarizer emerges with what fraction of its intensity?", options: ["one half", "all of it", "none", "one quarter"], answer: 0, difficulty: 2, explanation: "A polarizer passes half of unpolarized light: $I = \\tfrac12 I_0$." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "Two ideal polarizers crossed at 90° block essentially all the light.", answer: true, difficulty: 2, explanation: "$\\cos^2 90^\\circ = 0$, so no light passes." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Malus's law for polarized light through a filter at angle $\\theta$ is:", options: ["$I = I_0\\cos^2\\theta$", "$I = I_0\\sin\\theta$", "$I = I_0\\cos\\theta$", "$I = I_0\\tan^2\\theta$"], answer: 0, difficulty: 2, explanation: "$I = I_0\\cos^2\\theta$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Unpolarized light of intensity $I_0 = 800\\,\\text{W/m}^2$ passes one polarizer. Intensity out, in $\\text{W/m}^2$?", answer: { value: 400, tolerance: 1 }, hint: "$I = \\tfrac12 I_0$.", explanation: "$\\tfrac12(800) = 400\\,\\text{W/m}^2$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Polarized light $I_0 = 400\\,\\text{W/m}^2$ meets a filter at $\\theta = 60^\\circ$. Intensity out ($\\cos^2 60^\\circ = 0.25$), in $\\text{W/m}^2$?", answer: { value: 100, tolerance: 1 }, difficulty: 3, hint: "$I = I_0\\cos^2\\theta$.", explanation: "$400\\times 0.25 = 100\\,\\text{W/m}^2$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Polarized light $I_0 = 200\\,\\text{W/m}^2$ meets a filter at $\\theta = 45^\\circ$. Intensity out ($\\cos^2 45^\\circ = 0.5$), in $\\text{W/m}^2$?", answer: { value: 100, tolerance: 1 }, difficulty: 3, hint: "$I = I_0\\cos^2\\theta$.", explanation: "$200\\times 0.5 = 100\\,\\text{W/m}^2$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Sound waves can be polarized just like light.", answer: false, hint: "Is sound transverse or longitudinal?", explanation: "Sound is longitudinal, so it has no transverse direction to select — only transverse waves can be polarized." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "When a second polarizer's axis is aligned with the light's polarization ($\\theta = 0^\\circ$), the transmitted intensity is:", options: ["$I_0$ (all of it)", "$\\tfrac12 I_0$", "zero", "$\\tfrac14 I_0$"], answer: 0, hint: "$\\cos^2 0^\\circ = 1$.", explanation: "At $\\theta = 0^\\circ$, $\\cos^2 0 = 1$, so all the light passes." },
    ],
  },
];
