import type { LessonSeed } from "../types.js";

/**
 * Galaxy Clusters (graduate): thermodynamics & statistical mechanics — the
 * physics of heat and disorder, governing the hot X-ray gas that fills a
 * cluster. Temperature & thermal expansion; heat, specific & latent heat;
 * the ideal gas law & kinetic theory; the laws of thermodynamics; heat
 * engines & efficiency; and entropy & the second law. NUMERIC-led, with
 * SYMBOLIC used sparingly. All original content.
 */
export const thermodynamicsLessons: LessonSeed[] = [
  // ───────────────────────── 1. Temperature, Heat & Gases ─────────────────────────
  {
    slug: "temperature-heat-and-gases",
    title: "Temperature, Heat & Thermal Expansion",
    tagline: "The motion behind warmth",
    estMinutes: 16,
    xpReward: 170,
    difficulty: 3,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Heat Is Motion", sub: "Temperature measures the average jiggling of particles; heat is energy flowing because of a temperature difference — and that jiggling makes things expand." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "The space between galaxies in a cluster is filled with gas at tens of millions of degrees, glowing in X-rays. Closer to home, bridges have expansion joints, thermometers rely on liquids that swell when warmed, and railway tracks once buckled in summer heat. All of it traces back to one idea: **temperature** is a measure of microscopic motion, and **heat** is the energy that moves because of a temperature difference." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Temperature** measures the average **kinetic energy** of a substance's particles. **Heat** $Q$ is energy transferred *because of* a temperature difference, and it always flows from hot to cold.\n\nThe **absolute (Kelvin)** scale starts at **absolute zero** ($0\\,\\text{K} = -273^\\circ\\text{C}$), where particle motion is minimal. Convert with $T_{\\text{K}} = T_{\\text{C}} + 273$.\n\n**Thermal expansion.** Warm a solid and its particles vibrate more vigorously, pushing each other slightly farther apart, so the object grows. For a rod of original length $L$, the change in length is\n\n$$\\Delta L = \\alpha\\, L\\, \\Delta T,$$\n\nwhere $\\alpha$ is the material's **coefficient of linear expansion** (units $1/^\\circ\\text{C}$) and $\\Delta T$ is the temperature change. The effect is small but real — a $1\\,\\text{km}$ steel bridge can lengthen by tens of centimetres between winter and summer, which is why expansion joints exist." } },
      { kind: "CONCEPT", title: "Derivation: why expansion is linear", content: { markdown: "Near equilibrium, the energy holding two atoms together is a slightly **asymmetric** well — atoms can move apart more easily than they can be squeezed together. As temperature rises and the atoms vibrate with more energy, their *average* separation creeps outward. For modest temperature changes that drift is proportional to $\\Delta T$, and summing over a chain of $N$ atoms makes the whole-rod change proportional to its length $L$. Together that gives $\\Delta L = \\alpha L\\,\\Delta T$, with $\\alpha$ packaging all the atomic-scale details into one measured constant." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Heat flow direction", problem: "Which way does heat flow between a hot and a cold object in contact?", steps: ["Heat always flows hot → cold.", "It continues until both reach the same temperature (thermal equilibrium)."], answer: "From hot to cold, until temperatures equalise." },
        { title: "Celsius to Kelvin", problem: "Convert $27^\\circ\\text{C}$ to kelvin.", steps: ["Add 273: $27 + 273$.", "$= 300\\,\\text{K}$."], answer: "$300\\,\\text{K}$." },
        { title: "A lengthening rail", problem: "A $10\\,\\text{m}$ steel rail ($\\alpha = 1.2\\times 10^{-5}\\,/^\\circ\\text{C}$) warms by $30^\\circ\\text{C}$. How much longer does it get?", steps: ["$\\Delta L = \\alpha L\\,\\Delta T$.", "$= (1.2\\times 10^{-5})(10)(30)$.", "$= 3.6\\times 10^{-3}\\,\\text{m} = 3.6\\,\\text{mm}$."], answer: "About $3.6\\,\\text{mm}$ longer." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Temperature = average KE; heat flows hot→cold; $\\Delta L = \\alpha L\\,\\Delta T$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Convert temperatures and apply the expansion formula." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: area and volume expansion", content: { markdown: "Linear expansion has higher-dimensional cousins. A flat plate expands in **area** with coefficient $\\approx 2\\alpha$, and a solid expands in **volume** with coefficient $\\approx 3\\alpha$, because each independent dimension stretches. Liquids, having no fixed shape, are quoted only by a volume coefficient — which is why a thermometer's liquid column climbs as it warms. Water is the famous exception: between $0^\\circ\\text{C}$ and $4^\\circ\\text{C}$ it *contracts* as it warms, so ice floats and lakes freeze top-down." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Temperature and heat are the same thing.\"** Temperature measures average particle kinetic energy; heat is energy *in transit* due to a temperature difference. A bathtub of warm water holds far more heat than a red-hot spark, despite the spark's higher temperature.\n\n**\"A hole in a heated metal plate shrinks as the plate expands.\"** It actually grows — the metal around the hole expands outward, so the hole enlarges in proportion, just like the rest of the plate.\n\n**\"Cold flows into warm objects.\"** There is no such thing as 'cold' flowing. Only heat flows, and always from hot to cold; an object feels cold because heat is leaving *you*." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Temperature measures average particle kinetic energy; heat flows hot→cold.", "Kelvin starts at absolute zero: $T_{\\text{K}} = T_{\\text{C}} + 273$.", "Thermal expansion: $\\Delta L = \\alpha L\\,\\Delta T$ for a length $L$.", "Area expands as $\\approx 2\\alpha$, volume as $\\approx 3\\alpha$.", "Holes in a heated plate get larger, not smaller."], formulas: [{ label: "Linear expansion", tex: "\\Delta L = \\alpha L\\,\\Delta T" }, { label: "Celsius to Kelvin", tex: "T_{\\text{K}} = T_{\\text{C}} + 273" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Temperature is a measure of the average:", options: ["mass of particles", "kinetic energy of particles", "size of particles", "charge of particles"], answer: 1, difficulty: 1, explanation: "Temperature reflects the average kinetic energy of a substance's particles." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Heat always flows spontaneously:", options: ["cold to hot", "hot to cold", "in both directions equally", "only upward"], answer: 1, difficulty: 1, explanation: "Heat flows from hot to cold until thermal equilibrium is reached." },
      { scope: "CONCEPT_CHECK", kind: "NUMERIC", prompt: "Convert $27^\\circ\\text{C}$ to kelvin.", answer: { value: 300, tolerance: 1 }, difficulty: 2, explanation: "$27 + 273 = 300\\,\\text{K}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Absolute zero is approximately what temperature in degrees Celsius? (Give the magnitude, e.g. 273 for −273.)", answer: { value: 273, tolerance: 1 }, difficulty: 2, hint: "$0\\,\\text{K} = -273^\\circ\\text{C}$.", explanation: "$0\\,\\text{K} \\approx -273^\\circ\\text{C}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A $10\\,\\text{m}$ rail with $\\alpha = 1.2\\times10^{-5}\\,/^\\circ\\text{C}$ warms by $50^\\circ\\text{C}$. Find $\\Delta L$ in millimetres.", answer: { value: 6, tolerance: 0.1 }, difficulty: 3, hint: "$\\Delta L = \\alpha L\\,\\Delta T$, then convert to mm.", explanation: "$(1.2\\times10^{-5})(10)(50) = 6\\times10^{-3}\\,\\text{m} = 6\\,\\text{mm}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the change in length $\\Delta L$ in terms of the expansion coefficient $a$, length $L$, and temperature change $dT$. (Type like `a*L*dT`.)", answer: { expr: "a*L*dT", vars: ["a", "L", "dT"] }, difficulty: 3, hint: "Multiply the coefficient, the length, and the temperature change.", explanation: "$\\Delta L = \\alpha L\\,\\Delta T$ (here written $a\\,L\\,dT$)." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "When a metal plate with a hole is heated, the hole gets smaller.", answer: false, difficulty: 3, hint: "Everything scales up together.", explanation: "The hole expands along with the metal, so it gets larger, not smaller." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "A large tub of warm water and a tiny red-hot spark — which statement is correct?", options: ["The spark contains more heat because it is hotter", "The tub is at a higher temperature", "The tub can hold far more total heat despite a lower temperature", "Heat and temperature are identical here"], answer: 2, difficulty: 3, hint: "Distinguish total energy from temperature.", explanation: "Temperature is intensive; total heat depends on mass too, so the large tub stores far more heat even at a lower temperature." },
    ],
  },

  // ───────────────────────── 2. Heat, Specific Heat & Phase Changes ─────────────────────────
  {
    slug: "heat-specific-heat-and-phase-changes",
    title: "Heat, Specific Heat & Phase Changes",
    tagline: "How much energy it takes to warm — and to melt — matter",
    estMinutes: 17,
    xpReward: 170,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Counting the Calories of Heat", sub: "Why water is slow to boil, why ice keeps a drink cold while it melts, and how to balance the heat books in any mixture." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Engineers sizing a radiator, climatologists explaining why coastal cities have mild weather, and physicists measuring the heat capacity of cluster gas all ask the same question: *how much energy does it take to change a substance's temperature — or its phase?* Water's stubbornly high heat capacity moderates Earth's climate; the energy hidden in melting and boiling runs everything from steam turbines to sweating." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Specific heat capacity** $c$ is the energy needed to raise the temperature of $1\\,\\text{kg}$ of a substance by $1^\\circ\\text{C}$. The heat required to change a mass $m$ by $\\Delta T$ is\n\n$$Q = m\\,c\\,\\Delta T.$$\n\nWater's $c \\approx 4186\\,\\text{J/(kg\\cdot{}^\\circ C)}$ is unusually large, which is why it warms and cools slowly.\n\n**Phase changes** happen at *constant temperature*. While ice melts or water boils, all the added heat goes into rearranging the molecules, not raising the temperature. The energy is the **latent heat**:\n\n$$Q = m\\,L,$$\n\nwhere $L_f$ is the **latent heat of fusion** (melting/freezing) and $L_v$ is the **latent heat of vaporization** (boiling/condensing). For water, $L_f \\approx 3.34\\times10^5\\,\\text{J/kg}$ and $L_v \\approx 2.26\\times10^6\\,\\text{J/kg}$.\n\n**Calorimetry** applies energy conservation to a closed, insulated system: the heat lost by hot objects equals the heat gained by cold ones,\n\n$$\\sum Q = 0 \\quad\\Longleftrightarrow\\quad Q_{\\text{lost}} = Q_{\\text{gained}}.$$" } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Warming water", problem: "How much heat raises $2.0\\,\\text{kg}$ of water by $30^\\circ\\text{C}$? Use $c = 4186\\,\\text{J/(kg\\cdot{}^\\circ C)}$.", steps: ["$Q = m c\\,\\Delta T$.", "$= (2.0)(4186)(30)$.", "$\\approx 2.51\\times10^5\\,\\text{J}$."], answer: "About $2.5\\times10^5\\,\\text{J}$ (251 kJ)." },
        { title: "Melting ice", problem: "How much heat melts $0.50\\,\\text{kg}$ of ice at $0^\\circ\\text{C}$? Use $L_f = 3.34\\times10^5\\,\\text{J/kg}$.", steps: ["Phase change: $Q = m L_f$.", "$= (0.50)(3.34\\times10^5)$.", "$= 1.67\\times10^5\\,\\text{J}$."], answer: "About $1.67\\times10^5\\,\\text{J}$, all at $0^\\circ\\text{C}$." },
        { title: "A simple mixture", problem: "Hot metal loses $8000\\,\\text{J}$ to water in an insulated cup. How much heat does the water gain?", steps: ["Energy is conserved: $Q_{\\text{lost}} = Q_{\\text{gained}}$.", "Water gains exactly what the metal loses."], answer: "$8000\\,\\text{J}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "$Q = mc\\,\\Delta T$ for temperature change; $Q = mL$ for phase change." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Pick $Q=mc\\Delta T$ for warming/cooling and $Q=mL$ for melting/boiling; use calorimetry to balance." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: the heating curve", content: { markdown: "Plot temperature versus heat added for ice taken from below freezing to steam, and you get a staircase. Sloped segments are pure temperature change ($Q=mc\\,\\Delta T$), with the slope set by the phase's specific heat. **Flat plateaus** are the phase changes ($Q=mL$): the temperature stalls at $0^\\circ\\text{C}$ while ice melts and at $100^\\circ\\text{C}$ while water boils, even as energy keeps pouring in. The vaporization plateau is far longer than the fusion one because $L_v$ is nearly seven times $L_f$ — which is why a watched pot takes ages to boil dry." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Adding heat always raises temperature.\"** During a phase change the temperature holds constant; the energy goes into breaking molecular bonds, not speeding particles up. Melting ice stays at $0^\\circ\\text{C}$ until it has fully melted.\n\n**\"Boiling water can be made hotter by turning up the burner.\"** At a fixed pressure, boiling water stays at $100^\\circ\\text{C}$; a bigger flame only boils it away faster, it does not raise the temperature.\n\n**\"A substance with a high specific heat heats up quickly.\"** The opposite — a high $c$ means it takes *more* energy per degree, so it warms (and cools) slowly. That is exactly why water is such a good coolant and climate moderator." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Temperature change: $Q = m c\\,\\Delta T$; specific heat $c$ is energy per kg per degree.", "Phase change at constant temperature: $Q = m L$ (fusion $L_f$, vaporization $L_v$).", "Water's large $c$ makes it slow to heat and a strong climate moderator.", "Calorimetry: in an insulated system $Q_{\\text{lost}} = Q_{\\text{gained}}$.", "On a heating curve, plateaus are phase changes and slopes are temperature changes."], formulas: [{ label: "Sensible heat", tex: "Q = m c\\,\\Delta T" }, { label: "Latent heat", tex: "Q = m L" }, { label: "Calorimetry", tex: "Q_{\\text{lost}} = Q_{\\text{gained}}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The heat needed to change a substance's temperature is given by:", options: ["$Q = mL$", "$Q = mc\\,\\Delta T$", "$Q = \\tfrac12 mv^2$", "$Q = PV$"], answer: 1, difficulty: 2, explanation: "$Q = mc\\,\\Delta T$ governs temperature change; $Q=mL$ is for phase change." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "During melting, the temperature of the ice-water mixture stays constant.", answer: true, difficulty: 2, explanation: "Phase changes occur at constant temperature; the heat goes into breaking bonds." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "In an insulated cup, the heat lost by a hot object equals the heat:", options: ["radiated to space", "gained by the cold object", "destroyed", "converted to mass"], answer: 1, difficulty: 2, explanation: "Calorimetry: energy is conserved, so $Q_{\\text{lost}} = Q_{\\text{gained}}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "How much heat (in joules) raises $0.50\\,\\text{kg}$ of water by $20^\\circ\\text{C}$? Use $c = 4186\\,\\text{J/(kg\\cdot{}^\\circ C)}$.", answer: { value: 41860, tolerance: 100 }, difficulty: 3, hint: "$Q = mc\\,\\Delta T$.", explanation: "$(0.50)(4186)(20) = 41{,}860\\,\\text{J}$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "How much heat (in joules) melts $0.20\\,\\text{kg}$ of ice at $0^\\circ\\text{C}$? Use $L_f = 3.34\\times10^5\\,\\text{J/kg}$.", answer: { value: 66800, tolerance: 200 }, difficulty: 3, hint: "$Q = mL_f$.", explanation: "$(0.20)(3.34\\times10^5) = 66{,}800\\,\\text{J}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the heat $Q$ to change temperature in terms of mass $m$, specific heat $c$, and temperature change $dT$. (Type like `m*c*dT`.)", answer: { expr: "m*c*dT", vars: ["m", "c", "dT"] }, difficulty: 3, hint: "Multiply the three quantities.", explanation: "$Q = m c\\,\\Delta T$ (written $m\\,c\\,dT$)." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Turning up the burner under boiling water makes the water hotter than $100^\\circ\\text{C}$ (at normal pressure).", answer: false, difficulty: 3, hint: "What stays constant during a phase change?", explanation: "Boiling water holds at $100^\\circ\\text{C}$; a bigger flame just boils it away faster." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "For the same mass of water, which requires the most energy?", options: ["Warming it by $50^\\circ\\text{C}$", "Melting it at $0^\\circ\\text{C}$ ($L_f = 3.34\\times10^5$)", "Boiling it away at $100^\\circ\\text{C}$ ($L_v = 2.26\\times10^6$)", "All are equal"], answer: 2, difficulty: 4, hint: "Compare $cL$ products per kg: $c\\cdot50$, $L_f$, $L_v$.", explanation: "Per kg: warming $\\approx 2.1\\times10^5\\,\\text{J}$, melting $3.34\\times10^5\\,\\text{J}$, boiling $2.26\\times10^6\\,\\text{J}$ — vaporization wins by far." },
    ],
  },

  // ───────────────────────── 3. The Ideal Gas Law & Kinetic Theory ─────────────────────────
  {
    slug: "the-ideal-gas-law-and-kinetic-theory",
    title: "The Ideal Gas Law & Kinetic Theory",
    tagline: "Pressure, volume, and temperature from molecules in motion",
    estMinutes: 17,
    xpReward: 175,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Drumming on the Walls", sub: "Pressure is just countless molecules hammering the container — and one tidy equation ties it to temperature and volume." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "The million-degree gas filling a galaxy cluster, the air in a tyre, the helium in a balloon — all obey the same compact rule. The **ideal gas law** links the pressure, volume, and temperature of a gas, and **kinetic theory** explains *why* it works by treating a gas as a swarm of tiny particles in ceaseless random motion." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "For an ideal gas, pressure $P$, volume $V$, amount $n$ (in moles), and absolute temperature $T$ obey the **ideal gas law**:\n\n$$PV = nRT,$$\n\nwhere $R = 8.314\\,\\text{J/(mol\\cdot K)}$ is the universal gas constant. **Temperature must be in kelvin.** Holding the amount fixed, the special cases are:\n\n- **Constant $T$ (Boyle):** $PV$ is constant — squeeze the gas and pressure rises ($P \\propto 1/V$).\n- **Constant $P$ (Charles):** $V \\propto T$ — heat it and it expands.\n- **Constant $V$ (Gay-Lussac):** $P \\propto T$ — heat a sealed rigid tank and pressure climbs.\n\n**Kinetic theory** derives all this from molecules bouncing off the walls. The average translational kinetic energy of a molecule depends only on temperature:\n\n$$\\langle KE\\rangle = \\tfrac{3}{2} k_B T,$$\n\nwhere $k_B$ is Boltzmann's constant. Raise $T$ and the molecules move faster, hit the walls harder and more often, and pressure goes up — exactly what $PV = nRT$ predicts." } },
      { kind: "CONCEPT", title: "Derivation: pressure from collisions", content: { markdown: "Picture one molecule of mass $m$ bouncing between two walls a distance $L$ apart. Each elastic bounce reverses its momentum by $2mv_x$, and it returns every $2L/v_x$ seconds, so it delivers an average force $\\propto m v_x^2 / L$. Sum over all $N$ molecules, average their speeds, and divide by the wall area, and the geometry collapses to\n\n$$P = \\frac{1}{3}\\frac{N}{V} m \\langle v^2\\rangle.$$\n\nIdentifying $\\tfrac12 m\\langle v^2\\rangle$ with $\\tfrac32 k_B T$ turns this straight into $PV = N k_B T = nRT$. Pressure and temperature, born from pure mechanics and counting." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Boyle's behaviour", problem: "At constant temperature, you halve a gas's volume. What happens to the pressure?", steps: ["$PV$ is constant.", "Halving $V$ must double $P$."], answer: "The pressure doubles." },
        { title: "Heating a sealed tank", problem: "A rigid sealed tank of gas is heated from $300\\,\\text{K}$ to $600\\,\\text{K}$. What happens to its pressure?", steps: ["Constant $V$: $P \\propto T$.", "Doubling $T$ doubles $P$."], answer: "The pressure doubles." },
        { title: "Solving for pressure", problem: "Rearrange $PV = nRT$ to find $P$.", steps: ["Divide both sides by $V$.", "$P = nRT/V$."], answer: "$P = \\dfrac{nRT}{V}$." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "$PV = nRT$ with $T$ in kelvin; faster molecules mean higher pressure." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Apply the gas law and the proportionalities; keep temperatures in kelvin." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: the Maxwell–Boltzmann distribution", content: { markdown: "Not all molecules move at the same speed. Their speeds follow the **Maxwell–Boltzmann distribution**, a lopsided bell curve whose spread widens and whose peak shifts to higher speeds as temperature rises. Temperature is precisely a measure of this distribution's width. This statistical picture explains evaporation (the fastest tail of molecules escapes a liquid) and why lighter gases like hydrogen leak out of a planet's atmosphere first — at a given temperature they move faster on average." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"You can use Celsius in $PV = nRT$.\"** No — the law requires the *absolute* (kelvin) temperature. Plugging in $0^\\circ\\text{C}$ as zero would wrongly predict zero pressure.\n\n**\"Heavier gas molecules always move faster.\"** At the same temperature all gases have the same average kinetic energy, so heavier molecules actually move *slower* on average ($v \\propto 1/\\sqrt{m}$).\n\n**\"Real gases obey $PV = nRT$ exactly.\"** It is an idealisation that ignores molecular size and attractions. Real gases deviate at high pressure and low temperature, where those effects matter — that is why gases can be liquefied at all." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Ideal gas law: $PV = nRT$, with $T$ in kelvin and $R = 8.314\\,\\text{J/(mol\\cdot K)}$.", "Constant $T$: $PV$ constant (Boyle); constant $P$: $V\\propto T$ (Charles); constant $V$: $P\\propto T$.", "Kinetic theory: pressure comes from molecular collisions with the walls.", "Average kinetic energy $\\langle KE\\rangle = \\tfrac32 k_B T$ depends only on temperature.", "At a given temperature, heavier molecules move slower on average."], formulas: [{ label: "Ideal gas law", tex: "PV = nRT" }, { label: "Average molecular KE", tex: "\\langle KE\\rangle = \\tfrac{3}{2} k_B T" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The ideal gas law is:", options: ["$PV = nRT$", "$P = IR$", "$E = mc^2$", "$F = ma$"], answer: 0, difficulty: 1, explanation: "$PV = nRT$ relates pressure, volume, amount, and absolute temperature." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The pressure a gas exerts on its container arises from:", options: ["gravity", "molecules colliding with the walls", "magnetism", "light"], answer: 1, difficulty: 2, explanation: "Kinetic theory: countless molecular impacts on the walls produce pressure." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "In $PV = nRT$, the temperature must be expressed in kelvin.", answer: true, difficulty: 2, explanation: "The law uses the absolute temperature; Celsius would give wrong results." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "At constant temperature, halving a gas's volume doubles its pressure.", answer: true, difficulty: 2, hint: "$PV$ stays constant (Boyle's law).", explanation: "$P \\propto 1/V$, so halving $V$ doubles $P$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "A sealed rigid tank of gas is heated from $300\\,\\text{K}$ to $900\\,\\text{K}$. By what factor does its pressure increase?", answer: { value: 3, tolerance: 0.05 }, difficulty: 3, hint: "Constant volume: $P\\propto T$.", explanation: "$900/300 = 3$, so the pressure triples." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Solve the ideal gas law for pressure $P$ in terms of $n$, $R$, $T$, and $V$. (Type like `n*R*T/V`.)", answer: { expr: "n*R*T/V", vars: ["n", "R", "T", "V"] }, difficulty: 3, hint: "Divide $nRT$ by $V$.", explanation: "$P = \\dfrac{nRT}{V}$." },
      { scope: "PRACTICE", kind: "GRAPH", prompt: "At fixed volume and amount (constants set to 1), pressure versus temperature is $P = T$. Enter $P$ as a function of $T$, using $x$ for $T$.", answer: { expr: "x", domain: [0, 5], variable: "x" }, difficulty: 3, hint: "At constant $V$, $P \\propto T$ — a straight line through the origin.", explanation: "At constant volume, pressure is proportional to absolute temperature." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "Two gases are at the same temperature. Compared with the heavier molecules, the lighter molecules move on average:", options: ["slower", "faster", "at the same speed", "not at all"], answer: 1, difficulty: 4, hint: "Same average KE, $\\tfrac12 m v^2$.", explanation: "Equal average kinetic energy means $v \\propto 1/\\sqrt{m}$, so lighter molecules move faster." },
    ],
  },

  // ───────────────────────── 4. The Laws of Thermodynamics ─────────────────────────
  {
    slug: "the-laws-of-thermodynamics",
    title: "The Laws of Thermodynamics",
    tagline: "Four rules that govern energy and heat",
    estMinutes: 16,
    xpReward: 175,
    difficulty: 4,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "You Can't Win, and You Can't Break Even", sub: "Four deceptively simple laws rule every engine, star, and living cell — and forbid the free lunch forever." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "The million-degree gas between galaxies, a car engine, your own metabolism — all obey the same handful of laws. Having met temperature, heat, and gases, we now lay out the **full rulebook of energy**: the foundation of all thermal physics, and the reason perpetual-motion machines are impossible." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "The four laws of thermodynamics:\n\n**Zeroth law.** If two systems are each in thermal equilibrium with a third, they are in equilibrium with each other. This is what makes **temperature** a meaningful, measurable quantity — it is why a thermometer works.\n\n**First law (conservation of energy).** Energy is conserved; you can change a system's internal energy $U$ by adding **heat** $Q$ or by the system doing **work** $W$:\n\n$$\\Delta U = Q - W.$$\n\nYou cannot create energy from nothing — *'you can't win.'*\n\n**Second law (entropy).** The total entropy of an isolated system never decreases; heat flows spontaneously hot → cold; no process is perfectly efficient — *'you can't break even.'* This law gives time its arrow.\n\n**Third law.** As temperature approaches **absolute zero**, entropy approaches a minimum, and absolute zero itself can never be fully reached — *'you can't get out of the game.'*\n\nTogether they bound what any machine, chemical reaction, or living thing can do — among the most universal laws in all of science." } },
      { kind: "CONCEPT", title: "Derivation: signs in the first law", content: { markdown: "The first law is energy bookkeeping. Energy can enter a gas in two ways: heat $Q$ flowing in, and work done *on* it. We instead track $W$ as the work the gas does *on its surroundings* (e.g. pushing a piston out), so that work *leaves* the system. Conservation then reads input minus output:\n\n$$\\Delta U = Q - W.$$\n\nAdd heat and $U$ rises; let the gas expand and do work and $U$ falls. The sign convention is just a choice of which direction we call positive — physicists and chemists sometimes differ, so always check which $W$ is meant." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "First-law bookkeeping", problem: "$500\\,\\text{J}$ of heat is added to a gas while it does $200\\,\\text{J}$ of work. Find $\\Delta U$.", steps: ["$\\Delta U = Q - W$.", "$= 500 - 200 = 300\\,\\text{J}$."], answer: "$\\Delta U = 300\\,\\text{J}$." },
        { title: "Why thermometers work", problem: "Which law guarantees that temperature is well-defined?", steps: ["Thermal equilibrium is transitive.", "That is the zeroth law."], answer: "The zeroth law." },
        { title: "No perfect cold", problem: "Can anything reach absolute zero?", steps: ["Entropy approaches a minimum there.", "The third law forbids fully reaching it."], answer: "No — absolute zero is unreachable." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Zeroth: temperature. First: energy. Second: entropy. Third: absolute zero." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Apply the four laws and the first-law equation $\\Delta U = Q - W$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: statistical mechanics", content: { markdown: "Why do the laws hold? **Statistical mechanics**, built by Boltzmann, explains them from the behaviour of countless particles. Entropy counts the number of microscopic arrangements that look the same large-scale; disordered states have vastly more arrangements, so systems drift toward them simply by probability. Boltzmann's tombstone bears his equation, $S = k \\log W$, linking entropy $S$ to the number of microstates $W$ — heat and disorder, explained by counting." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"The first law lets you build a perpetual-motion machine.\"** The first law only forbids creating energy; a machine that runs forever extracting work would still violate the *second* law. The first law bans 'free' energy, the second bans 'perfectly efficient' energy.\n\n**\"Adding heat to a system always raises its internal energy.\"** Not necessarily — if the system does an equal amount of work while heat flows in ($Q = W$), then $\\Delta U = 0$ and the internal energy is unchanged.\n\n**\"The third law means we can reach absolute zero with a good enough fridge.\"** It says the opposite: every cooling step removes less and less entropy, so absolute zero requires infinitely many steps and can never actually be attained." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Zeroth law: makes temperature meaningful (thermometers work).", "First law: energy is conserved, $\\Delta U = Q - W$ ('you can't win').", "Second law: total entropy never decreases ('you can't break even').", "Third law: absolute zero can never be fully reached.", "Statistical mechanics explains the laws by counting microscopic arrangements."], formulas: [{ label: "First law", tex: "\\Delta U = Q - W" }, { label: "Boltzmann entropy", tex: "S = k \\log W" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "The first law of thermodynamics is essentially:", options: ["entropy increases", "conservation of energy", "temperature is relative", "absolute zero is reachable"], answer: 1, difficulty: 2, explanation: "It states energy is conserved: $\\Delta U = Q - W$." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Which law makes temperature a well-defined quantity?", options: ["zeroth law", "first law", "second law", "third law"], answer: 0, difficulty: 3, explanation: "The zeroth law (transitive equilibrium) underpins temperature and thermometers." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "The third law says absolute zero can never be completely reached.", answer: true, difficulty: 3, explanation: "Entropy approaches a minimum, but absolute zero is unattainable." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "$800\\,\\text{J}$ of heat is added to a gas while it does $300\\,\\text{J}$ of work. Find $\\Delta U$ in joules.", answer: { value: 500, tolerance: 0 }, difficulty: 3, hint: "$\\Delta U = Q - W$.", explanation: "$800 - 300 = 500\\,\\text{J}$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the change in internal energy $U$ from heat $Q$ and work done by the system $W$ (first law). (Type like `Q - W`.)", answer: { expr: "Q - W", vars: ["Q", "W"] }, difficulty: 3, hint: "Energy conservation: input minus output.", explanation: "$\\Delta U = Q - W$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "'You can't win, you can't break even' refers, in order, to the:", options: ["second and third laws", "first and second laws", "zeroth and first laws", "third and first laws"], answer: 1, difficulty: 3, hint: "Energy, then entropy.", explanation: "First law: can't create energy ('win'); second law: can't be perfectly efficient ('break even')." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Statistical mechanics explains entropy by counting microscopic arrangements.", answer: true, difficulty: 4, hint: "Boltzmann's $S = k\\log W$.", explanation: "More microstates means higher entropy; systems drift toward the most probable, disordered states." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "If heat flows into a gas but the gas does an equal amount of work, its internal energy stays the same.", answer: true, difficulty: 4, hint: "Set $Q = W$ in the first law.", explanation: "$\\Delta U = Q - W = 0$ when $Q = W$, so $U$ is unchanged." },
    ],
  },

  // ───────────────────────── 5. Heat Engines & Efficiency Limits ─────────────────────────
  {
    slug: "heat-engines-and-carnot",
    title: "Heat Engines & the Carnot Limit",
    tagline: "Turning heat into work — and the ceiling no engine beats",
    estMinutes: 16,
    xpReward: 175,
    difficulty: 5,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Every Engine Has a Hard Ceiling", sub: "No matter how clever the design, the temperatures it runs between cap how much heat it can turn into work." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Heat engines drove the Industrial Revolution and still generate most of our electricity. The second law sets an unbreakable limit on them — discovered by a young engineer studying steam, and as fundamental as any law in physics. It is why power plants run boilers as hot as their materials allow." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "A **heat engine** takes in heat $Q_h$ from a hot reservoir at temperature $T_h$, converts **some** of it into useful work $W$, and dumps the rest, $Q_c$, into a cold reservoir at $T_c$. It *must* dump some — the second law forbids turning heat entirely into work.\n\n**Efficiency** is what you get out over what you put in:\n\n$$\\eta = \\frac{W}{Q_h} = 1 - \\frac{Q_c}{Q_h}.$$\n\nThe **maximum possible efficiency**, achieved only by an ideal (reversible) **Carnot** engine, depends only on the two absolute temperatures:\n\n$$\\eta_{max} = 1 - \\frac{T_c}{T_h}.$$\n\nLessons from this formula:\n\n- A bigger temperature gap (hotter $T_h$ or colder $T_c$) means higher possible efficiency.\n- Perfect efficiency ($\\eta = 1$) would need $T_c = 0$ (absolute zero) — impossible by the third law.\n- Real engines, with friction and irreversibility, always fall **below** the Carnot limit.\n\nRun an engine in reverse and you get a **refrigerator** or **heat pump**, using work to move heat from cold to hot — paying the entropy bill with the work input." } },
      { kind: "CONCEPT", title: "Derivation: the Carnot limit from entropy", content: { markdown: "A reversible (Carnot) engine produces no net entropy. Over one cycle it absorbs $Q_h$ at $T_h$ and rejects $Q_c$ at $T_c$, and reversibility demands the entropy in equal the entropy out:\n\n$$\\frac{Q_h}{T_h} = \\frac{Q_c}{T_c}\\quad\\Longrightarrow\\quad \\frac{Q_c}{Q_h} = \\frac{T_c}{T_h}.$$\n\nSubstitute into $\\eta = 1 - Q_c/Q_h$ and the efficiency becomes $\\eta_{max} = 1 - T_c/T_h$. Any *real* engine creates extra entropy, which forces it to dump more $Q_c$, so its efficiency is strictly lower. The ceiling depends on temperatures alone — not on the fuel or the design." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Carnot efficiency", problem: "An ideal engine runs between $T_h = 600\\,\\text{K}$ and $T_c = 300\\,\\text{K}$. Maximum efficiency?", steps: ["$\\eta_{max} = 1 - T_c/T_h$.", "$= 1 - 300/600 = 1 - 0.5$.", "$= 0.5$."], answer: "50% — and a real engine between these temperatures does worse." },
        { title: "Why dump heat?", problem: "Why can't an engine turn all its input heat into work?", steps: ["The second law forbids it.", "Some heat must go to the cold reservoir."], answer: "Exhaust heat is unavoidable." },
        { title: "Boosting efficiency", problem: "How do you raise an engine's efficiency ceiling?", steps: ["Increase the temperature gap.", "Raise $T_h$ or lower $T_c$."], answer: "Widen the gap between hot and cold." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "$\\eta_{max} = 1 - T_c/T_h$; perfect efficiency is impossible." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Compute and reason about engine efficiency; keep temperatures in kelvin." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: Carnot's lasting legacy", content: { markdown: "**Sadi Carnot** published his analysis in 1824 and died of cholera at 36, his work nearly forgotten. Yet his idealised engine set the gold standard every real engine is measured against, and his reasoning birthed the second law and the concept of entropy. Remarkably, the Carnot limit depends *only* on temperatures — not on the working substance, design, or fuel. It is a statement about the universe, not about engineering, which is why it has never been beaten." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"A more cleverly engineered engine can beat the Carnot efficiency.\"** No real or ideal engine operating between two given temperatures can exceed $1 - T_c/T_h$; it is a hard limit set by the second law, independent of design.\n\n**\"Carnot efficiency works with Celsius temperatures.\"** It requires absolute (kelvin) temperatures. Using $^\\circ\\text{C}$ — for instance $T_c$ near $0^\\circ\\text{C}$ — would falsely suggest near-perfect efficiency.\n\n**\"A heat pump is less than 100% efficient like an engine.\"** A heat pump can deliver several joules of heat per joule of work (a coefficient of performance above 1) because it *moves* existing heat rather than creating it — that is not a violation of any law." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["A heat engine converts some heat to work and must exhaust the rest to a cold reservoir.", "Efficiency $\\eta = W/Q_h = 1 - Q_c/Q_h$.", "Maximum (Carnot) efficiency: $\\eta_{max} = 1 - T_c/T_h$ (kelvin temperatures).", "A larger hot–cold temperature gap allows higher efficiency; $\\eta = 1$ is impossible.", "Run in reverse, an engine becomes a refrigerator or heat pump."], formulas: [{ label: "Engine efficiency", tex: "\\eta = 1 - \\dfrac{Q_c}{Q_h}" }, { label: "Carnot efficiency", tex: "\\eta_{max} = 1 - \\dfrac{T_c}{T_h}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "A heat engine must:", options: ["turn all heat into work", "exhaust some heat to a cold reservoir", "run at absolute zero", "create energy"], answer: 1, difficulty: 2, explanation: "The second law requires dumping some heat; full conversion is impossible." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "A larger temperature difference between the hot and cold reservoirs allows a higher maximum efficiency.", answer: true, difficulty: 3, explanation: "$\\eta_{max} = 1 - T_c/T_h$ grows as the gap widens." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "100% efficiency is impossible because it would require:", options: ["a faster engine", "the cold reservoir at absolute zero", "more fuel", "a bigger engine"], answer: 1, difficulty: 4, explanation: "$\\eta = 1$ needs $T_c = 0$, forbidden by the third law." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "An ideal engine runs between $800\\,\\text{K}$ and $200\\,\\text{K}$. Maximum efficiency as a decimal?", answer: { value: 0.75, tolerance: 0.01 }, difficulty: 3, hint: "$1 - T_c/T_h = 1 - 200/800$.", explanation: "$1 - 200/800 = 1 - 0.25 = 0.75$." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "An engine takes in $1000\\,\\text{J}$ and exhausts $700\\,\\text{J}$. Its efficiency as a decimal?", answer: { value: 0.3, tolerance: 0.01 }, difficulty: 3, hint: "$\\eta = 1 - Q_c/Q_h$.", explanation: "$1 - 700/1000 = 0.30$." },
      { scope: "PRACTICE", kind: "SYMBOLIC", prompt: "Write the Carnot efficiency in terms of cold and hot temperatures $T_c$ and $T_h$. (Type like `1 - T_c/T_h`.)", answer: { expr: "1 - T_c/T_h", vars: ["T_c", "T_h"] }, difficulty: 4, hint: "One minus the temperature ratio.", explanation: "$\\eta_{max} = 1 - T_c/T_h$." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "Running a heat engine in reverse, using work to move heat from cold to hot, gives a:", options: ["perpetual motion machine", "refrigerator or heat pump", "battery", "turbine"], answer: 1, difficulty: 3, hint: "It pumps heat 'uphill'.", explanation: "A refrigerator/heat pump uses work input to move heat from cold to hot." },
    ],
  },

  // ───────────────────────── 6. Entropy & the Second Law ─────────────────────────
  {
    slug: "entropy-and-the-second-law",
    title: "Entropy & the Second Law",
    tagline: "Why time has a direction",
    estMinutes: 15,
    xpReward: 175,
    difficulty: 5,
    sections: [
      { kind: "HERO", content: { scene: "sun", headline: "Disorder Always Wins", sub: "The one law that knows the difference between past and future: entropy never decreases." } },
      { kind: "CONTEXT", title: "Why this matters", content: { markdown: "Drop a glass and it shatters; you never see shards leap back together. Heat spreads out; it never spontaneously concentrates. This one-way character of nature is the **second law of thermodynamics**, and it is woven from a single quantity: **entropy**. It is the deepest reason the universe distinguishes past from future." } },
      { kind: "CONCEPT", title: "The big idea", content: { markdown: "**Entropy** $S$ measures the disorder of a system — more precisely, the number of microscopic arrangements (microstates) consistent with its overall state.\n\nThe **second law of thermodynamics:** the total entropy of an isolated system never decreases.\n\n$$\\Delta S_{\\text{total}} \\ge 0.$$\n\nFor heat $Q$ exchanged reversibly at absolute temperature $T$, the entropy change is\n\n$$\\Delta S = \\frac{Q}{T}.$$\n\nConsequences:\n\n- Heat flows hot → cold because that spreads energy out, raising total entropy.\n- No engine can convert heat **entirely** into work — some is always 'lost' to entropy. The best possible efficiency is the Carnot limit.\n- Order can increase **locally** (a fridge, a growing organism) only by dumping *more* entropy into the surroundings.\n\nEntropy gives time its **arrow**: the future is the direction of increasing entropy. It is the deep reason perpetual-motion machines are impossible." } },
      { kind: "CONCEPT", title: "Derivation: why hot-to-cold raises entropy", content: { markdown: "Move a small amount of heat $Q$ from a hot body at $T_h$ to a cold body at $T_c$. The hot body loses entropy $Q/T_h$; the cold body gains $Q/T_c$. The net change is\n\n$$\\Delta S = \\frac{Q}{T_c} - \\frac{Q}{T_h}.$$\n\nSince $T_c < T_h$, the term $Q/T_c$ is larger, so $\\Delta S > 0$ — the transfer increases total entropy. Reverse it (cold to hot) and $\\Delta S$ would be negative, which the second law forbids without outside work. That single inequality is why heat only flows downhill in temperature on its own." } },
      { kind: "WORKED_EXAMPLES", title: "Worked examples", content: { examples: [
        { title: "Direction of heat flow", problem: "Why does heat flow hot to cold, never the reverse?", steps: ["Spreading energy raises total entropy.", "$\\Delta S = Q/T_c - Q/T_h > 0$ since $T_c < T_h$."], answer: "Because it increases total entropy." },
        { title: "Engine limit", problem: "Can an engine turn 100% of heat into work?", steps: ["Some heat must be exhausted.", "Entropy forbids full conversion."], answer: "No — never 100% efficient." },
        { title: "Local order", problem: "How can a fridge make things colder (more ordered)?", steps: ["It exports entropy as waste heat.", "Total entropy still rises."], answer: "By increasing entropy elsewhere." },
      ] } },
      { kind: "CONCEPT_CHECK", title: "Quick check", content: { intro: "Total entropy never decreases; $\\Delta S = Q/T$." } },
      { kind: "PRACTICE", title: "Practice problems", content: { intro: "Reason with the second law and compute $\\Delta S = Q/T$." } },
      { kind: "DEEPER_DIVE", title: "Deeper dive: the heat death of the universe", content: { markdown: "Extrapolate the second law to the cosmos: entropy rises relentlessly, energy spreads ever more uniformly, and usable energy dwindles. In the far future the universe approaches a state of maximum entropy — the **heat death** — where everything is the same temperature and no work can be extracted. Galaxy clusters, with their slowly cooling X-ray gas, are part of this grand, irreversible drift toward equilibrium." } },
      { kind: "DEEPER_DIVE", title: "Common misconceptions", content: { markdown: "**\"Entropy can never decrease anywhere.\"** It can decrease *locally* — a freezer makes ice, an organism builds ordered tissue — as long as a *larger* increase happens in the surroundings, keeping the total non-negative.\n\n**\"The second law is just a statement about heat engines.\"** It is far broader: it defines the arrow of time and governs every spontaneous process, from gases mixing to proteins folding.\n\n**\"Life and evolution violate the second law by creating order.\"** They do not. Living things are open systems that consume low-entropy energy (sunlight, food) and export high-entropy waste heat, so the total entropy of organism plus environment still rises." } },
      { kind: "SUMMARY", title: "Summary", content: { takeaways: ["Entropy measures disorder (the number of microscopic arrangements).", "Second law: total entropy of an isolated system never decreases, $\\Delta S_{\\text{total}} \\ge 0$.", "For reversible heat transfer, $\\Delta S = Q/T$.", "Heat flows hot→cold because it raises total entropy; no engine is 100% efficient.", "Order can grow locally only by exporting more entropy; entropy defines time's arrow."], formulas: [{ label: "Second law", tex: "\\Delta S_{\\text{total}} \\ge 0" }, { label: "Entropy change", tex: "\\Delta S = \\dfrac{Q}{T}" }] } },
    ],
    questions: [
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "Entropy is a measure of:", options: ["temperature", "disorder", "pressure", "charge"], answer: 1, difficulty: 1, explanation: "Entropy measures disorder, i.e. the number of microstates." },
      { scope: "CONCEPT_CHECK", kind: "TRUE_FALSE", prompt: "The total entropy of an isolated system can spontaneously decrease.", answer: false, difficulty: 2, explanation: "The second law: total entropy never decreases." },
      { scope: "CONCEPT_CHECK", kind: "MCQ", prompt: "No heat engine can be:", options: ["partly efficient", "100% efficient", "built", "reversed"], answer: 1, difficulty: 2, explanation: "Entropy forbids complete heat-to-work conversion." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "Heat flows from hot to cold because it increases total entropy.", answer: true, difficulty: 2, hint: "Energy spreads out.", explanation: "The spontaneous direction is the one that raises total entropy." },
      { scope: "PRACTICE", kind: "NUMERIC", prompt: "Reversibly add $600\\,\\text{J}$ of heat to a reservoir at $300\\,\\text{K}$. Entropy change in J/K?", answer: { value: 2, tolerance: 0.05 }, difficulty: 3, hint: "$\\Delta S = Q/T$.", explanation: "$600/300 = 2\\,\\text{J/K}$." },
      { scope: "PRACTICE", kind: "TRUE_FALSE", prompt: "A refrigerator can lower entropy locally by increasing it more in the surroundings.", answer: true, difficulty: 3, hint: "The total still rises.", explanation: "Local order is paid for by a greater increase in disorder elsewhere." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "A perpetual-motion machine is impossible because it would violate:", options: ["Ohm's law", "the second law of thermodynamics", "Hooke's law", "Snell's law"], answer: 1, difficulty: 3, hint: "Think entropy and efficiency.", explanation: "It would require total entropy to decrease or 100% efficiency, both forbidden." },
      { scope: "PRACTICE", kind: "MCQ", prompt: "The far-future state of maximum entropy is called the:", options: ["Big Bang", "heat death", "singularity", "main sequence"], answer: 1, difficulty: 3, hint: "Energy fully spread out, no work extractable.", explanation: "Maximum-entropy equilibrium is the heat death of the universe." },
    ],
  },
];
