import type { WorldSeed } from "../types.js";
import { kindergartenParkLessons } from "./kindergarten-park.js";
import { elementarySchoolStLessons } from "./elementary-school-st.js";

/**
 * The City of Numbers — 14 districts, each a branch of mathematics discovered in
 * the streets, shops, and skyline of a living city. Kindergarten Park ships with
 * full content; the rest are charted on the map and populated in later drops.
 */
export const districts: WorldSeed[] = [
  {
    slug: "kindergarten-park",
    name: "Kindergarten Park",
    subtitle: "Where the numbers begin",
    description:
      "A sunny green at the city's edge. Count the ducks, name the shapes in the flower beds, and crack the patterns on the garden path — the very first steps into mathematics.",
    gradeRange: "K–1",
    scaleLabel: "1 Counting Lane",
    palette: { accent: "#22D3A0", glow: "#0E8C6B" },
    lessons: kindergartenParkLessons,
  },
  {
    slug: "elementary-school-st",
    name: "Elementary School St.",
    subtitle: "Adding it all up",
    description: "Chalkboards and lunch counts: addition, subtraction, place value, and two-digit regrouping — the foundations every later number skill is built on.",
    gradeRange: "1–3",
    scaleLabel: "Schoolhouse Row",
    palette: { accent: "#FFB800", glow: "#C77F00" },
    lessons: elementarySchoolStLessons,
  },
  {
    slug: "the-bakery",
    name: "The Bakery",
    subtitle: "Slices, shares, and decimals",
    description: "Warm brick and pastel awnings. Slice the pies and price the loaves to discover fractions and decimals.",
    gradeRange: "3–5",
    scaleLabel: "12 Pastry Place",
    palette: { accent: "#FF9E5C", glow: "#C2569C" },
    lessons: [],
  },
  {
    slug: "the-market",
    name: "The Market",
    subtitle: "Deals, rates, and percents",
    description: "Bustling stalls and bartering crowds: ratios, proportions, and the percentages on every price tag.",
    gradeRange: "5–6",
    scaleLabel: "Market Square",
    palette: { accent: "#22D3A0", glow: "#1E90FF" },
    lessons: [],
  },
  {
    slug: "city-hall-plaza",
    name: "City Hall Plaza",
    subtitle: "Solving for the unknown",
    description: "Civic stone and fountains: the first taste of algebra, where letters stand in for numbers we don't yet know.",
    gradeRange: "6–7",
    scaleLabel: "1 Plaza Way",
    palette: { accent: "#7FB3FF", glow: "#3D6FC9" },
    lessons: [],
  },
  {
    slug: "architects-quarter",
    name: "The Architect's Quarter",
    subtitle: "Lines, angles, and area",
    description: "Drafting tables and blueprints: geometry and measurement, where shapes meet the ruler and protractor.",
    gradeRange: "7–8",
    scaleLabel: "Blueprint Blvd",
    palette: { accent: "#5AD1E6", glow: "#2A6FA3" },
    lessons: [],
  },
  {
    slug: "stock-exchange",
    name: "The Stock Exchange",
    subtitle: "Chance and data",
    description: "Glass and chrome towers: statistics and probability, reading the story hidden inside numbers.",
    gradeRange: "8–9",
    scaleLabel: "Ticker Tower",
    palette: { accent: "#C0C7D0", glow: "#5662B8" },
    lessons: [],
  },
  {
    slug: "engineering-district",
    name: "The Engineering District",
    subtitle: "Functions and machines",
    description: "Steel and steam: advanced algebra and functions — the input-output machines that model the world.",
    gradeRange: "9–10",
    scaleLabel: "Gear Street",
    palette: { accent: "#FF8C42", glow: "#C25A1E" },
    lessons: [],
  },
  {
    slug: "observatory-bridge",
    name: "The Observatory Bridge",
    subtitle: "The shape of waves",
    description: "A span under the stars: trigonometry, where triangles and circles describe everything that turns and oscillates.",
    gradeRange: "10–11",
    scaleLabel: "Starlight Span",
    palette: { accent: "#9AA7FF", glow: "#3E4C8C" },
    lessons: [],
  },
  {
    slug: "university-campus",
    name: "The University Campus",
    subtitle: "Approaching the limit",
    description: "Ivy and lecture halls: pre-calculus and the idea of limits, the threshold of higher mathematics.",
    gradeRange: "11–12",
    scaleLabel: "Scholars' Court",
    palette: { accent: "#E6D8FF", glow: "#6E3FC2" },
    lessons: [],
  },
  {
    slug: "research-lab",
    name: "The Research Lab",
    subtitle: "Change and accumulation",
    description: "Clean white benches: Calculus I & II — derivatives, integrals, and the mathematics of motion itself.",
    gradeRange: "Undergrad",
    scaleLabel: "Newton Wing",
    palette: { accent: "#88F7D4", glow: "#3BAE8C" },
    lessons: [],
  },
  {
    slug: "data-science-tower",
    name: "The Data Science Tower",
    subtitle: "Vectors and matrices",
    description: "Servers humming in violet light: linear algebra, the grid of numbers powering modern AI and graphics.",
    gradeRange: "Undergrad",
    scaleLabel: "Vector Heights",
    palette: { accent: "#B07CFF", glow: "#6B21D6" },
    lessons: [],
  },
  {
    slug: "quantum-institute",
    name: "The Quantum Institute",
    subtitle: "Equations of change",
    description: "Cool labs and chalk dust: differential equations, the language nature uses to describe how things evolve.",
    gradeRange: "Undergrad",
    scaleLabel: "Flux Hall",
    palette: { accent: "#6CF0FF", glow: "#2BA8B8" },
    lessons: [],
  },
  {
    slug: "graduate-school",
    name: "The Graduate School",
    subtitle: "The deep structure",
    description: "Gothic stone and endless libraries: abstract algebra, topology, and real analysis — mathematics at its most pure.",
    gradeRange: "Grad",
    scaleLabel: "Old Quad",
    palette: { accent: "#FFD27A", glow: "#9D86C9" },
    lessons: [],
  },
];
